// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :execrows
INSERT INTO idenqa.api_keys (
    id,
    tenant_id,
    label,
    digest,
    pepper_version,
    requested_scopes,
    resolved_scopes,
    version,
    created_at,
    updated_at,
    expires_at,
    revoked_at,
    retired_at,
    replaces_key_id
) SELECT
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
WHERE EXISTS (
    SELECT 1
    FROM idenqa.tenants
    WHERE id = $2 AND state = 'active'
    FOR UPDATE
)
`

type CreateAPIKeyParams struct {
	ID              string
	TenantID        string
	Label           string
	Digest          []byte
	PepperVersion   int32
	RequestedScopes []string
	ResolvedScopes  []string
	Version         int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	RetiredAt       pgtype.Timestamptz
	ReplacesKeyID   *string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.TenantID,
		arg.Label,
		arg.Digest,
		arg.PepperVersion,
		arg.RequestedScopes,
		arg.ResolvedScopes,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.RetiredAt,
		arg.ReplacesKeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAPIKey = `-- name: FindAPIKey :one
SELECT
    id,
    tenant_id,
    label,
    digest,
    pepper_version,
    requested_scopes,
    resolved_scopes,
    version,
    created_at,
    updated_at,
    expires_at,
    revoked_at,
    retired_at,
    replaces_key_id
FROM idenqa.api_keys
WHERE tenant_id = $1 AND id = $2
`

type FindAPIKeyParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindAPIKey(ctx context.Context, arg FindAPIKeyParams) (IdenqaApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKey, arg.TenantID, arg.ID)
	var i IdenqaApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Label,
		&i.Digest,
		&i.PepperVersion,
		&i.RequestedScopes,
		&i.ResolvedScopes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RetiredAt,
		&i.ReplacesKeyID,
	)
	return i, err
}

const findAPIKeyForVerification = `-- name: FindAPIKeyForVerification :one
SELECT
    api_keys.id, api_keys.tenant_id, api_keys.label, api_keys.digest, api_keys.pepper_version, api_keys.requested_scopes, api_keys.resolved_scopes, api_keys.version, api_keys.created_at, api_keys.updated_at, api_keys.expires_at, api_keys.revoked_at, api_keys.retired_at, api_keys.replaces_key_id,
    tenants.state AS tenant_state
FROM idenqa.api_keys AS api_keys
JOIN idenqa.tenants AS tenants ON tenants.id = api_keys.tenant_id
WHERE api_keys.tenant_id = $1 AND api_keys.id = $2
`

type FindAPIKeyForVerificationParams struct {
	TenantID string
	ID       string
}

type FindAPIKeyForVerificationRow struct {
	IdenqaApiKey IdenqaApiKey
	TenantState  string
}

func (q *Queries) FindAPIKeyForVerification(ctx context.Context, arg FindAPIKeyForVerificationParams) (FindAPIKeyForVerificationRow, error) {
	row := q.db.QueryRow(ctx, findAPIKeyForVerification, arg.TenantID, arg.ID)
	var i FindAPIKeyForVerificationRow
	err := row.Scan(
		&i.IdenqaApiKey.ID,
		&i.IdenqaApiKey.TenantID,
		&i.IdenqaApiKey.Label,
		&i.IdenqaApiKey.Digest,
		&i.IdenqaApiKey.PepperVersion,
		&i.IdenqaApiKey.RequestedScopes,
		&i.IdenqaApiKey.ResolvedScopes,
		&i.IdenqaApiKey.Version,
		&i.IdenqaApiKey.CreatedAt,
		&i.IdenqaApiKey.UpdatedAt,
		&i.IdenqaApiKey.ExpiresAt,
		&i.IdenqaApiKey.RevokedAt,
		&i.IdenqaApiKey.RetiredAt,
		&i.IdenqaApiKey.ReplacesKeyID,
		&i.TenantState,
	)
	return i, err
}

const insertAPIKeyAdminAudit = `-- name: InsertAPIKeyAdminAudit :exec
INSERT INTO idenqa.api_key_admin_audit (
    tenant_id,
    key_id,
    action,
    actor,
    reason,
    occurred_at
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAPIKeyAdminAuditParams struct {
	TenantID   string
	KeyID      *string
	Action     string
	Actor      string
	Reason     string
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) InsertAPIKeyAdminAudit(ctx context.Context, arg InsertAPIKeyAdminAuditParams) error {
	_, err := q.db.Exec(ctx, insertAPIKeyAdminAudit,
		arg.TenantID,
		arg.KeyID,
		arg.Action,
		arg.Actor,
		arg.Reason,
		arg.OccurredAt,
	)
	return err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT
    id,
    tenant_id,
    label,
    digest,
    pepper_version,
    requested_scopes,
    resolved_scopes,
    version,
    created_at,
    updated_at,
    expires_at,
    revoked_at,
    retired_at,
    replaces_key_id
FROM idenqa.api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, tenantID string) ([]IdenqaApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdenqaApiKey
	for rows.Next() {
		var i IdenqaApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Label,
			&i.Digest,
			&i.PepperVersion,
			&i.RequestedScopes,
			&i.ResolvedScopes,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RetiredAt,
			&i.ReplacesKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAPIKeyLifecycle = `-- name: SaveAPIKeyLifecycle :execrows
UPDATE idenqa.api_keys
SET
    version = $1,
    updated_at = $2,
    revoked_at = $3::timestamptz,
    retired_at = $4::timestamptz
WHERE tenant_id = $5
  AND id = $6
  AND version = $7
  AND $1 = $7 + 1
  AND (
      (
          $3::timestamptz IS NOT NULL AND
          revoked_at IS NULL AND
          $3::timestamptz = $2::timestamptz AND
          $4::timestamptz IS NOT DISTINCT FROM retired_at
      ) OR (
          $3::timestamptz IS NULL AND
          revoked_at IS NULL AND
          retired_at IS NULL AND
          $4::timestamptz IS NOT NULL AND
          $4::timestamptz >= $2::timestamptz
      )
  )
`

type SaveAPIKeyLifecycleParams struct {
	NewVersion      int64
	UpdatedAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	RetiredAt       pgtype.Timestamptz
	TenantID        string
	ID              string
	ExpectedVersion int64
}

func (q *Queries) SaveAPIKeyLifecycle(ctx context.Context, arg SaveAPIKeyLifecycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveAPIKeyLifecycle,
		arg.NewVersion,
		arg.UpdatedAt,
		arg.RevokedAt,
		arg.RetiredAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
