// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authority.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindVerificationAuthority = `-- name: BindVerificationAuthority :execrows
UPDATE idenqa.verification_sessions
SET subject_id = $3, authority_id = $4, notice_id = $5
WHERE tenant_id = $1 AND id = $2
  AND subject_id IS NULL AND authority_id IS NULL AND notice_id IS NULL
`

type BindVerificationAuthorityParams struct {
	TenantID    string
	ID          string
	SubjectID   *string
	AuthorityID *string
	NoticeID    *string
}

func (q *Queries) BindVerificationAuthority(ctx context.Context, arg BindVerificationAuthorityParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindVerificationAuthority,
		arg.TenantID,
		arg.ID,
		arg.SubjectID,
		arg.AuthorityID,
		arg.NoticeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createNoticeVersion = `-- name: CreateNoticeVersion :one
INSERT INTO idenqa.notice_versions (
    id, tenant_id, semantic_key, locale, controller_display_name,
    recipient_display_name, title, summary, purpose_copy,
    consequence_copy, effective_at, created_at, created_by, digest
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, tenant_id, semantic_key, locale, controller_display_name, recipient_display_name, title, summary, purpose_copy, consequence_copy, effective_at, created_at, created_by, digest
`

type CreateNoticeVersionParams struct {
	ID                    string
	TenantID              string
	SemanticKey           string
	Locale                string
	ControllerDisplayName string
	RecipientDisplayName  string
	Title                 string
	Summary               string
	PurposeCopy           string
	ConsequenceCopy       string
	EffectiveAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	CreatedBy             string
	Digest                string
}

func (q *Queries) CreateNoticeVersion(ctx context.Context, arg CreateNoticeVersionParams) (IdenqaNoticeVersion, error) {
	row := q.db.QueryRow(ctx, createNoticeVersion,
		arg.ID,
		arg.TenantID,
		arg.SemanticKey,
		arg.Locale,
		arg.ControllerDisplayName,
		arg.RecipientDisplayName,
		arg.Title,
		arg.Summary,
		arg.PurposeCopy,
		arg.ConsequenceCopy,
		arg.EffectiveAt,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.Digest,
	)
	var i IdenqaNoticeVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SemanticKey,
		&i.Locale,
		&i.ControllerDisplayName,
		&i.RecipientDisplayName,
		&i.Title,
		&i.Summary,
		&i.PurposeCopy,
		&i.ConsequenceCopy,
		&i.EffectiveAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Digest,
	)
	return i, err
}

const createProcessingAuthority = `-- name: CreateProcessingAuthority :one
INSERT INTO idenqa.processing_authorities (
    id, tenant_id, subject_id, verification_id, notice_id, category,
    purpose, jurisdiction, policy_pack, consent_required,
    requirement_purposes, evidence_types, recipient_reference,
    recipient_display_name, regions, retention_reference, state, version,
    valid_from, expires_at, created_at, updated_at, created_by,
    restricted_at, withdrawn_at, superseded_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23, $24, $25, $26
)
RETURNING id, tenant_id, subject_id, verification_id, notice_id, category, purpose, jurisdiction, policy_pack, consent_required, requirement_purposes, evidence_types, recipient_reference, recipient_display_name, regions, retention_reference, state, version, valid_from, expires_at, created_at, updated_at, created_by, restricted_at, withdrawn_at, superseded_at
`

type CreateProcessingAuthorityParams struct {
	ID                   string
	TenantID             string
	SubjectID            string
	VerificationID       string
	NoticeID             string
	Category             string
	Purpose              string
	Jurisdiction         string
	PolicyPack           string
	ConsentRequired      bool
	RequirementPurposes  []string
	EvidenceTypes        []string
	RecipientReference   string
	RecipientDisplayName string
	Regions              []string
	RetentionReference   string
	State                string
	Version              int64
	ValidFrom            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            string
	RestrictedAt         pgtype.Timestamptz
	WithdrawnAt          pgtype.Timestamptz
	SupersededAt         pgtype.Timestamptz
}

func (q *Queries) CreateProcessingAuthority(ctx context.Context, arg CreateProcessingAuthorityParams) (IdenqaProcessingAuthority, error) {
	row := q.db.QueryRow(ctx, createProcessingAuthority,
		arg.ID,
		arg.TenantID,
		arg.SubjectID,
		arg.VerificationID,
		arg.NoticeID,
		arg.Category,
		arg.Purpose,
		arg.Jurisdiction,
		arg.PolicyPack,
		arg.ConsentRequired,
		arg.RequirementPurposes,
		arg.EvidenceTypes,
		arg.RecipientReference,
		arg.RecipientDisplayName,
		arg.Regions,
		arg.RetentionReference,
		arg.State,
		arg.Version,
		arg.ValidFrom,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.RestrictedAt,
		arg.WithdrawnAt,
		arg.SupersededAt,
	)
	var i IdenqaProcessingAuthority
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.NoticeID,
		&i.Category,
		&i.Purpose,
		&i.Jurisdiction,
		&i.PolicyPack,
		&i.ConsentRequired,
		&i.RequirementPurposes,
		&i.EvidenceTypes,
		&i.RecipientReference,
		&i.RecipientDisplayName,
		&i.Regions,
		&i.RetentionReference,
		&i.State,
		&i.Version,
		&i.ValidFrom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.RestrictedAt,
		&i.WithdrawnAt,
		&i.SupersededAt,
	)
	return i, err
}

const createSubjectResponse = `-- name: CreateSubjectResponse :one
INSERT INTO idenqa.subject_responses (
    id, tenant_id, authority_id, notice_id, subject_id, verification_id,
    capture_token_id, action, locale, rendered_experience_version, recorded_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, authority_id, notice_id, subject_id, verification_id, capture_token_id, action, locale, rendered_experience_version, recorded_at
`

type CreateSubjectResponseParams struct {
	ID                        string
	TenantID                  string
	AuthorityID               string
	NoticeID                  string
	SubjectID                 string
	VerificationID            string
	CaptureTokenID            string
	Action                    string
	Locale                    string
	RenderedExperienceVersion *string
	RecordedAt                pgtype.Timestamptz
}

func (q *Queries) CreateSubjectResponse(ctx context.Context, arg CreateSubjectResponseParams) (IdenqaSubjectResponse, error) {
	row := q.db.QueryRow(ctx, createSubjectResponse,
		arg.ID,
		arg.TenantID,
		arg.AuthorityID,
		arg.NoticeID,
		arg.SubjectID,
		arg.VerificationID,
		arg.CaptureTokenID,
		arg.Action,
		arg.Locale,
		arg.RenderedExperienceVersion,
		arg.RecordedAt,
	)
	var i IdenqaSubjectResponse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorityID,
		&i.NoticeID,
		&i.SubjectID,
		&i.VerificationID,
		&i.CaptureTokenID,
		&i.Action,
		&i.Locale,
		&i.RenderedExperienceVersion,
		&i.RecordedAt,
	)
	return i, err
}

const createVerificationSubject = `-- name: CreateVerificationSubject :exec
INSERT INTO idenqa.subjects (id, tenant_id, verification_id, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateVerificationSubjectParams struct {
	ID             string
	TenantID       string
	VerificationID string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateVerificationSubject(ctx context.Context, arg CreateVerificationSubjectParams) error {
	_, err := q.db.Exec(ctx, createVerificationSubject,
		arg.ID,
		arg.TenantID,
		arg.VerificationID,
		arg.CreatedAt,
	)
	return err
}

const findLatestSubjectResponse = `-- name: FindLatestSubjectResponse :one
SELECT id, tenant_id, authority_id, notice_id, subject_id, verification_id, capture_token_id, action, locale, rendered_experience_version, recorded_at
FROM idenqa.subject_responses
WHERE tenant_id = $1 AND authority_id = $2
ORDER BY recorded_at DESC, id DESC
LIMIT 1
`

type FindLatestSubjectResponseParams struct {
	TenantID    string
	AuthorityID string
}

func (q *Queries) FindLatestSubjectResponse(ctx context.Context, arg FindLatestSubjectResponseParams) (IdenqaSubjectResponse, error) {
	row := q.db.QueryRow(ctx, findLatestSubjectResponse, arg.TenantID, arg.AuthorityID)
	var i IdenqaSubjectResponse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorityID,
		&i.NoticeID,
		&i.SubjectID,
		&i.VerificationID,
		&i.CaptureTokenID,
		&i.Action,
		&i.Locale,
		&i.RenderedExperienceVersion,
		&i.RecordedAt,
	)
	return i, err
}

const findNoticeVersion = `-- name: FindNoticeVersion :one
SELECT id, tenant_id, semantic_key, locale, controller_display_name, recipient_display_name, title, summary, purpose_copy, consequence_copy, effective_at, created_at, created_by, digest
FROM idenqa.notice_versions
WHERE tenant_id = $1 AND id = $2
`

type FindNoticeVersionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindNoticeVersion(ctx context.Context, arg FindNoticeVersionParams) (IdenqaNoticeVersion, error) {
	row := q.db.QueryRow(ctx, findNoticeVersion, arg.TenantID, arg.ID)
	var i IdenqaNoticeVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SemanticKey,
		&i.Locale,
		&i.ControllerDisplayName,
		&i.RecipientDisplayName,
		&i.Title,
		&i.Summary,
		&i.PurposeCopy,
		&i.ConsequenceCopy,
		&i.EffectiveAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Digest,
	)
	return i, err
}

const findProcessingAuthority = `-- name: FindProcessingAuthority :one
SELECT id, tenant_id, subject_id, verification_id, notice_id, category, purpose, jurisdiction, policy_pack, consent_required, requirement_purposes, evidence_types, recipient_reference, recipient_display_name, regions, retention_reference, state, version, valid_from, expires_at, created_at, updated_at, created_by, restricted_at, withdrawn_at, superseded_at
FROM idenqa.processing_authorities
WHERE tenant_id = $1 AND id = $2
`

type FindProcessingAuthorityParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindProcessingAuthority(ctx context.Context, arg FindProcessingAuthorityParams) (IdenqaProcessingAuthority, error) {
	row := q.db.QueryRow(ctx, findProcessingAuthority, arg.TenantID, arg.ID)
	var i IdenqaProcessingAuthority
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.NoticeID,
		&i.Category,
		&i.Purpose,
		&i.Jurisdiction,
		&i.PolicyPack,
		&i.ConsentRequired,
		&i.RequirementPurposes,
		&i.EvidenceTypes,
		&i.RecipientReference,
		&i.RecipientDisplayName,
		&i.Regions,
		&i.RetentionReference,
		&i.State,
		&i.Version,
		&i.ValidFrom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.RestrictedAt,
		&i.WithdrawnAt,
		&i.SupersededAt,
	)
	return i, err
}

const findProcessingAuthorityByVerification = `-- name: FindProcessingAuthorityByVerification :one
SELECT id, tenant_id, subject_id, verification_id, notice_id, category, purpose, jurisdiction, policy_pack, consent_required, requirement_purposes, evidence_types, recipient_reference, recipient_display_name, regions, retention_reference, state, version, valid_from, expires_at, created_at, updated_at, created_by, restricted_at, withdrawn_at, superseded_at
FROM idenqa.processing_authorities
WHERE tenant_id = $1 AND verification_id = $2
`

type FindProcessingAuthorityByVerificationParams struct {
	TenantID       string
	VerificationID string
}

func (q *Queries) FindProcessingAuthorityByVerification(ctx context.Context, arg FindProcessingAuthorityByVerificationParams) (IdenqaProcessingAuthority, error) {
	row := q.db.QueryRow(ctx, findProcessingAuthorityByVerification, arg.TenantID, arg.VerificationID)
	var i IdenqaProcessingAuthority
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.NoticeID,
		&i.Category,
		&i.Purpose,
		&i.Jurisdiction,
		&i.PolicyPack,
		&i.ConsentRequired,
		&i.RequirementPurposes,
		&i.EvidenceTypes,
		&i.RecipientReference,
		&i.RecipientDisplayName,
		&i.Regions,
		&i.RetentionReference,
		&i.State,
		&i.Version,
		&i.ValidFrom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.RestrictedAt,
		&i.WithdrawnAt,
		&i.SupersededAt,
	)
	return i, err
}

const findSubjectResponse = `-- name: FindSubjectResponse :one
SELECT id, tenant_id, authority_id, notice_id, subject_id, verification_id, capture_token_id, action, locale, rendered_experience_version, recorded_at
FROM idenqa.subject_responses
WHERE tenant_id = $1 AND id = $2
`

type FindSubjectResponseParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindSubjectResponse(ctx context.Context, arg FindSubjectResponseParams) (IdenqaSubjectResponse, error) {
	row := q.db.QueryRow(ctx, findSubjectResponse, arg.TenantID, arg.ID)
	var i IdenqaSubjectResponse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthorityID,
		&i.NoticeID,
		&i.SubjectID,
		&i.VerificationID,
		&i.CaptureTokenID,
		&i.Action,
		&i.Locale,
		&i.RenderedExperienceVersion,
		&i.RecordedAt,
	)
	return i, err
}

const insertAuthorityAudit = `-- name: InsertAuthorityAudit :exec
INSERT INTO idenqa.authority_audit (
    tenant_id, authority_id, aggregate_version, action,
    actor_type, actor_id, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuthorityAuditParams struct {
	TenantID         string
	AuthorityID      string
	AggregateVersion int64
	Action           string
	ActorType        string
	ActorID          string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) InsertAuthorityAudit(ctx context.Context, arg InsertAuthorityAuditParams) error {
	_, err := q.db.Exec(ctx, insertAuthorityAudit,
		arg.TenantID,
		arg.AuthorityID,
		arg.AggregateVersion,
		arg.Action,
		arg.ActorType,
		arg.ActorID,
		arg.OccurredAt,
	)
	return err
}

const insertNoticeVersionAudit = `-- name: InsertNoticeVersionAudit :exec
INSERT INTO idenqa.notice_version_audit (
    tenant_id, notice_id, action, actor_key_id, occurred_at
) VALUES ($1, $2, $3, $4, $5)
`

type InsertNoticeVersionAuditParams struct {
	TenantID   string
	NoticeID   string
	Action     string
	ActorKeyID string
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) InsertNoticeVersionAudit(ctx context.Context, arg InsertNoticeVersionAuditParams) error {
	_, err := q.db.Exec(ctx, insertNoticeVersionAudit,
		arg.TenantID,
		arg.NoticeID,
		arg.Action,
		arg.ActorKeyID,
		arg.OccurredAt,
	)
	return err
}

const lockVerificationForAuthority = `-- name: LockVerificationForAuthority :one
SELECT id, tenant_id, requirements, expires_at, authority_id
FROM idenqa.verification_sessions
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockVerificationForAuthorityParams struct {
	TenantID string
	ID       string
}

type LockVerificationForAuthorityRow struct {
	ID           string
	TenantID     string
	Requirements []byte
	ExpiresAt    pgtype.Timestamptz
	AuthorityID  *string
}

func (q *Queries) LockVerificationForAuthority(ctx context.Context, arg LockVerificationForAuthorityParams) (LockVerificationForAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockVerificationForAuthority, arg.TenantID, arg.ID)
	var i LockVerificationForAuthorityRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Requirements,
		&i.ExpiresAt,
		&i.AuthorityID,
	)
	return i, err
}

const transitionProcessingAuthority = `-- name: TransitionProcessingAuthority :one
UPDATE idenqa.processing_authorities
SET state = $4,
    version = $5,
    updated_at = $6,
    restricted_at = $7,
    withdrawn_at = $8,
    superseded_at = $9
WHERE tenant_id = $1 AND id = $2 AND version = $3 AND state = 'active'
RETURNING id, tenant_id, subject_id, verification_id, notice_id, category, purpose, jurisdiction, policy_pack, consent_required, requirement_purposes, evidence_types, recipient_reference, recipient_display_name, regions, retention_reference, state, version, valid_from, expires_at, created_at, updated_at, created_by, restricted_at, withdrawn_at, superseded_at
`

type TransitionProcessingAuthorityParams struct {
	TenantID     string
	ID           string
	Version      int64
	State        string
	Version_2    int64
	UpdatedAt    pgtype.Timestamptz
	RestrictedAt pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
	SupersededAt pgtype.Timestamptz
}

func (q *Queries) TransitionProcessingAuthority(ctx context.Context, arg TransitionProcessingAuthorityParams) (IdenqaProcessingAuthority, error) {
	row := q.db.QueryRow(ctx, transitionProcessingAuthority,
		arg.TenantID,
		arg.ID,
		arg.Version,
		arg.State,
		arg.Version_2,
		arg.UpdatedAt,
		arg.RestrictedAt,
		arg.WithdrawnAt,
		arg.SupersededAt,
	)
	var i IdenqaProcessingAuthority
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.NoticeID,
		&i.Category,
		&i.Purpose,
		&i.Jurisdiction,
		&i.PolicyPack,
		&i.ConsentRequired,
		&i.RequirementPurposes,
		&i.EvidenceTypes,
		&i.RecipientReference,
		&i.RecipientDisplayName,
		&i.Regions,
		&i.RetentionReference,
		&i.State,
		&i.Version,
		&i.ValidFrom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.RestrictedAt,
		&i.WithdrawnAt,
		&i.SupersededAt,
	)
	return i, err
}
