// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capture_profile.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCaptureProfile = `-- name: CreateCaptureProfile :exec
INSERT INTO idenqa.capture_profiles (
    id, tenant_id, name, state, version, latest_revision, draft_revision,
    published_revision, created_at, updated_at, deactivated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateCaptureProfileParams struct {
	ID                string
	TenantID          string
	Name              string
	State             string
	Version           int64
	LatestRevision    int32
	DraftRevision     *int32
	PublishedRevision *int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeactivatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateCaptureProfile(ctx context.Context, arg CreateCaptureProfileParams) error {
	_, err := q.db.Exec(ctx, createCaptureProfile,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.State,
		arg.Version,
		arg.LatestRevision,
		arg.DraftRevision,
		arg.PublishedRevision,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeactivatedAt,
	)
	return err
}

const createCaptureProfileRevision = `-- name: CreateCaptureProfileRevision :exec
INSERT INTO idenqa.capture_profile_revisions (
    tenant_id, profile_id, revision, state, schema_version,
    registry_schema_version, registry_revision, registry_digest,
    document, digest, created_at, updated_at, published_at, ended_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateCaptureProfileRevisionParams struct {
	TenantID              string
	ProfileID             string
	Revision              int32
	State                 string
	SchemaVersion         int32
	RegistrySchemaVersion int32
	RegistryRevision      int32
	RegistryDigest        string
	Document              []byte
	Digest                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PublishedAt           pgtype.Timestamptz
	EndedAt               pgtype.Timestamptz
}

func (q *Queries) CreateCaptureProfileRevision(ctx context.Context, arg CreateCaptureProfileRevisionParams) error {
	_, err := q.db.Exec(ctx, createCaptureProfileRevision,
		arg.TenantID,
		arg.ProfileID,
		arg.Revision,
		arg.State,
		arg.SchemaVersion,
		arg.RegistrySchemaVersion,
		arg.RegistryRevision,
		arg.RegistryDigest,
		arg.Document,
		arg.Digest,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.EndedAt,
	)
	return err
}

const findCaptureProfile = `-- name: FindCaptureProfile :one
SELECT id, tenant_id, name, state, version, latest_revision, draft_revision, published_revision, created_at, updated_at, deactivated_at
FROM idenqa.capture_profiles
WHERE tenant_id = $1 AND id = $2
`

type FindCaptureProfileParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindCaptureProfile(ctx context.Context, arg FindCaptureProfileParams) (IdenqaCaptureProfile, error) {
	row := q.db.QueryRow(ctx, findCaptureProfile, arg.TenantID, arg.ID)
	var i IdenqaCaptureProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.Version,
		&i.LatestRevision,
		&i.DraftRevision,
		&i.PublishedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const findCaptureProfileRevision = `-- name: FindCaptureProfileRevision :one
SELECT tenant_id, profile_id, revision, state, schema_version, registry_schema_version, registry_revision, registry_digest, document, digest, created_at, updated_at, published_at, ended_at
FROM idenqa.capture_profile_revisions
WHERE tenant_id = $1 AND profile_id = $2 AND revision = $3
`

type FindCaptureProfileRevisionParams struct {
	TenantID  string
	ProfileID string
	Revision  int32
}

func (q *Queries) FindCaptureProfileRevision(ctx context.Context, arg FindCaptureProfileRevisionParams) (IdenqaCaptureProfileRevision, error) {
	row := q.db.QueryRow(ctx, findCaptureProfileRevision, arg.TenantID, arg.ProfileID, arg.Revision)
	var i IdenqaCaptureProfileRevision
	err := row.Scan(
		&i.TenantID,
		&i.ProfileID,
		&i.Revision,
		&i.State,
		&i.SchemaVersion,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Document,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.EndedAt,
	)
	return i, err
}

const insertCaptureProfileAudit = `-- name: InsertCaptureProfileAudit :exec
INSERT INTO idenqa.capture_profile_audit (
    tenant_id, profile_id, aggregate_version, revision, action, actor_key_id, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertCaptureProfileAuditParams struct {
	TenantID         string
	ProfileID        string
	AggregateVersion int64
	Revision         *int32
	Action           string
	ActorKeyID       string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) InsertCaptureProfileAudit(ctx context.Context, arg InsertCaptureProfileAuditParams) error {
	_, err := q.db.Exec(ctx, insertCaptureProfileAudit,
		arg.TenantID,
		arg.ProfileID,
		arg.AggregateVersion,
		arg.Revision,
		arg.Action,
		arg.ActorKeyID,
		arg.OccurredAt,
	)
	return err
}

const listCaptureProfilesAfter = `-- name: ListCaptureProfilesAfter :many
SELECT id, tenant_id, name, state, version, latest_revision, draft_revision, published_revision, created_at, updated_at, deactivated_at
FROM idenqa.capture_profiles
WHERE tenant_id = $1 AND (created_at, id) < (
    $2::timestamptz,
    $3::text
)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListCaptureProfilesAfterParams struct {
	TenantID       string
	AfterCreatedAt pgtype.Timestamptz
	AfterID        string
	PageSize       int32
}

func (q *Queries) ListCaptureProfilesAfter(ctx context.Context, arg ListCaptureProfilesAfterParams) ([]IdenqaCaptureProfile, error) {
	rows, err := q.db.Query(ctx, listCaptureProfilesAfter,
		arg.TenantID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdenqaCaptureProfile
	for rows.Next() {
		var i IdenqaCaptureProfile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.State,
			&i.Version,
			&i.LatestRevision,
			&i.DraftRevision,
			&i.PublishedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaptureProfilesFirst = `-- name: ListCaptureProfilesFirst :many
SELECT id, tenant_id, name, state, version, latest_revision, draft_revision, published_revision, created_at, updated_at, deactivated_at
FROM idenqa.capture_profiles
WHERE tenant_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListCaptureProfilesFirstParams struct {
	TenantID string
	Limit    int32
}

func (q *Queries) ListCaptureProfilesFirst(ctx context.Context, arg ListCaptureProfilesFirstParams) ([]IdenqaCaptureProfile, error) {
	rows, err := q.db.Query(ctx, listCaptureProfilesFirst, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdenqaCaptureProfile
	for rows.Next() {
		var i IdenqaCaptureProfile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.State,
			&i.Version,
			&i.LatestRevision,
			&i.DraftRevision,
			&i.PublishedRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeactivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishCaptureProfileRevision = `-- name: PublishCaptureProfileRevision :one
UPDATE idenqa.capture_profile_revisions
SET state = 'published', updated_at = $4, published_at = $4
WHERE tenant_id = $1 AND profile_id = $2 AND revision = $3 AND state = 'draft'
RETURNING tenant_id, profile_id, revision, state, schema_version, registry_schema_version, registry_revision, registry_digest, document, digest, created_at, updated_at, published_at, ended_at
`

type PublishCaptureProfileRevisionParams struct {
	TenantID  string
	ProfileID string
	Revision  int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) PublishCaptureProfileRevision(ctx context.Context, arg PublishCaptureProfileRevisionParams) (IdenqaCaptureProfileRevision, error) {
	row := q.db.QueryRow(ctx, publishCaptureProfileRevision,
		arg.TenantID,
		arg.ProfileID,
		arg.Revision,
		arg.UpdatedAt,
	)
	var i IdenqaCaptureProfileRevision
	err := row.Scan(
		&i.TenantID,
		&i.ProfileID,
		&i.Revision,
		&i.State,
		&i.SchemaVersion,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Document,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.EndedAt,
	)
	return i, err
}

const saveCaptureProfile = `-- name: SaveCaptureProfile :one
UPDATE idenqa.capture_profiles
SET name = $3,
    state = $4,
    version = $5,
    latest_revision = $6,
    draft_revision = $7,
    published_revision = $8,
    updated_at = $9,
    deactivated_at = $10
WHERE tenant_id = $1 AND id = $2 AND version = $11
RETURNING id, tenant_id, name, state, version, latest_revision, draft_revision, published_revision, created_at, updated_at, deactivated_at
`

type SaveCaptureProfileParams struct {
	TenantID          string
	ID                string
	Name              string
	State             string
	Version           int64
	LatestRevision    int32
	DraftRevision     *int32
	PublishedRevision *int32
	UpdatedAt         pgtype.Timestamptz
	DeactivatedAt     pgtype.Timestamptz
	ExpectedVersion   int64
}

func (q *Queries) SaveCaptureProfile(ctx context.Context, arg SaveCaptureProfileParams) (IdenqaCaptureProfile, error) {
	row := q.db.QueryRow(ctx, saveCaptureProfile,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.State,
		arg.Version,
		arg.LatestRevision,
		arg.DraftRevision,
		arg.PublishedRevision,
		arg.UpdatedAt,
		arg.DeactivatedAt,
		arg.ExpectedVersion,
	)
	var i IdenqaCaptureProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.Version,
		&i.LatestRevision,
		&i.DraftRevision,
		&i.PublishedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const saveCaptureProfileDraft = `-- name: SaveCaptureProfileDraft :one
UPDATE idenqa.capture_profile_revisions
SET schema_version = $4,
    registry_schema_version = $5,
    registry_revision = $6,
    registry_digest = $7,
    document = $8,
    digest = $9,
    updated_at = $10
WHERE tenant_id = $1 AND profile_id = $2 AND revision = $3 AND state = 'draft'
RETURNING tenant_id, profile_id, revision, state, schema_version, registry_schema_version, registry_revision, registry_digest, document, digest, created_at, updated_at, published_at, ended_at
`

type SaveCaptureProfileDraftParams struct {
	TenantID              string
	ProfileID             string
	Revision              int32
	SchemaVersion         int32
	RegistrySchemaVersion int32
	RegistryRevision      int32
	RegistryDigest        string
	Document              []byte
	Digest                string
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) SaveCaptureProfileDraft(ctx context.Context, arg SaveCaptureProfileDraftParams) (IdenqaCaptureProfileRevision, error) {
	row := q.db.QueryRow(ctx, saveCaptureProfileDraft,
		arg.TenantID,
		arg.ProfileID,
		arg.Revision,
		arg.SchemaVersion,
		arg.RegistrySchemaVersion,
		arg.RegistryRevision,
		arg.RegistryDigest,
		arg.Document,
		arg.Digest,
		arg.UpdatedAt,
	)
	var i IdenqaCaptureProfileRevision
	err := row.Scan(
		&i.TenantID,
		&i.ProfileID,
		&i.Revision,
		&i.State,
		&i.SchemaVersion,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Document,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.EndedAt,
	)
	return i, err
}

const supersedeCaptureProfileRevision = `-- name: SupersedeCaptureProfileRevision :one
UPDATE idenqa.capture_profile_revisions
SET state = 'superseded', updated_at = $4, ended_at = $4
WHERE tenant_id = $1 AND profile_id = $2 AND revision = $3 AND state = 'published'
RETURNING tenant_id, profile_id, revision, state, schema_version, registry_schema_version, registry_revision, registry_digest, document, digest, created_at, updated_at, published_at, ended_at
`

type SupersedeCaptureProfileRevisionParams struct {
	TenantID  string
	ProfileID string
	Revision  int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SupersedeCaptureProfileRevision(ctx context.Context, arg SupersedeCaptureProfileRevisionParams) (IdenqaCaptureProfileRevision, error) {
	row := q.db.QueryRow(ctx, supersedeCaptureProfileRevision,
		arg.TenantID,
		arg.ProfileID,
		arg.Revision,
		arg.UpdatedAt,
	)
	var i IdenqaCaptureProfileRevision
	err := row.Scan(
		&i.TenantID,
		&i.ProfileID,
		&i.Revision,
		&i.State,
		&i.SchemaVersion,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Document,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.EndedAt,
	)
	return i, err
}

const withdrawCaptureProfileRevision = `-- name: WithdrawCaptureProfileRevision :one
UPDATE idenqa.capture_profile_revisions
SET state = 'withdrawn', updated_at = $4, ended_at = $4
WHERE tenant_id = $1 AND profile_id = $2 AND revision = $3 AND state = 'draft'
RETURNING tenant_id, profile_id, revision, state, schema_version, registry_schema_version, registry_revision, registry_digest, document, digest, created_at, updated_at, published_at, ended_at
`

type WithdrawCaptureProfileRevisionParams struct {
	TenantID  string
	ProfileID string
	Revision  int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) WithdrawCaptureProfileRevision(ctx context.Context, arg WithdrawCaptureProfileRevisionParams) (IdenqaCaptureProfileRevision, error) {
	row := q.db.QueryRow(ctx, withdrawCaptureProfileRevision,
		arg.TenantID,
		arg.ProfileID,
		arg.Revision,
		arg.UpdatedAt,
	)
	var i IdenqaCaptureProfileRevision
	err := row.Scan(
		&i.TenantID,
		&i.ProfileID,
		&i.Revision,
		&i.State,
		&i.SchemaVersion,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Document,
		&i.Digest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.EndedAt,
	)
	return i, err
}
