// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection.sql

package sqlgen

import (
	"context"
)

const checkConnection = `-- name: CheckConnection :one
SELECT 1::bigint AS value
`

func (q *Queries) CheckConnection(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, checkConnection)
	var value int64
	err := row.Scan(&value)
	return value, err
}
