// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence_reconciliation.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvidenceObjectReconciliation = `-- name: CreateEvidenceObjectReconciliation :execrows
INSERT INTO idenqa.evidence_object_reconciliations (
    tenant_id, upload_id, evidence_id, upload_attempt,
    object_key, object_version, object_size, object_checksum,
    state, version, claim, available_at, lease_expires_at,
    created_at, updated_at, resolved_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (tenant_id, upload_id, upload_attempt) DO NOTHING
`

type CreateEvidenceObjectReconciliationParams struct {
	TenantID       string
	UploadID       string
	EvidenceID     string
	UploadAttempt  int32
	ObjectKey      string
	ObjectVersion  string
	ObjectSize     int64
	ObjectChecksum string
	State          string
	Version        int64
	Claim          int32
	AvailableAt    pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

func (q *Queries) CreateEvidenceObjectReconciliation(ctx context.Context, arg CreateEvidenceObjectReconciliationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createEvidenceObjectReconciliation,
		arg.TenantID,
		arg.UploadID,
		arg.EvidenceID,
		arg.UploadAttempt,
		arg.ObjectKey,
		arg.ObjectVersion,
		arg.ObjectSize,
		arg.ObjectChecksum,
		arg.State,
		arg.Version,
		arg.Claim,
		arg.AvailableAt,
		arg.LeaseExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ResolvedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findEvidenceObjectReconciliation = `-- name: FindEvidenceObjectReconciliation :one
SELECT tenant_id, upload_id, evidence_id, upload_attempt, object_key, object_version, object_size, object_checksum, state, version, claim, available_at, lease_expires_at, created_at, updated_at, resolved_at
FROM idenqa.evidence_object_reconciliations
WHERE tenant_id = $1 AND upload_id = $2 AND upload_attempt = $3
`

type FindEvidenceObjectReconciliationParams struct {
	TenantID      string
	UploadID      string
	UploadAttempt int32
}

func (q *Queries) FindEvidenceObjectReconciliation(ctx context.Context, arg FindEvidenceObjectReconciliationParams) (IdenqaEvidenceObjectReconciliation, error) {
	row := q.db.QueryRow(ctx, findEvidenceObjectReconciliation, arg.TenantID, arg.UploadID, arg.UploadAttempt)
	var i IdenqaEvidenceObjectReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.UploadID,
		&i.EvidenceID,
		&i.UploadAttempt,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.ObjectSize,
		&i.ObjectChecksum,
		&i.State,
		&i.Version,
		&i.Claim,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertEvidenceObjectReconciliationAudit = `-- name: InsertEvidenceObjectReconciliationAudit :exec
INSERT INTO idenqa.evidence_object_reconciliation_audit (
    tenant_id, upload_id, upload_attempt, aggregate_version,
    claim, action, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEvidenceObjectReconciliationAuditParams struct {
	TenantID         string
	UploadID         string
	UploadAttempt    int32
	AggregateVersion int64
	Claim            int32
	Action           string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) InsertEvidenceObjectReconciliationAudit(ctx context.Context, arg InsertEvidenceObjectReconciliationAuditParams) error {
	_, err := q.db.Exec(ctx, insertEvidenceObjectReconciliationAudit,
		arg.TenantID,
		arg.UploadID,
		arg.UploadAttempt,
		arg.AggregateVersion,
		arg.Claim,
		arg.Action,
		arg.OccurredAt,
	)
	return err
}

const isEvidenceObjectReferenced = `-- name: IsEvidenceObjectReferenced :one
SELECT EXISTS (
    SELECT 1
    FROM idenqa.evidence_assets AS asset
    WHERE asset.tenant_id = $1
      AND asset.object_key = $2
      AND asset.object_version = $3
    UNION ALL
    SELECT 1
    FROM idenqa.evidence_object_reconciliations AS reconciliation
    WHERE reconciliation.tenant_id = $1
      AND reconciliation.object_key = $2
      AND reconciliation.object_version = $3
      AND reconciliation.state IN ('pending', 'claimed', 'retained')
) AS referenced
`

type IsEvidenceObjectReferencedParams struct {
	TenantID      string
	ObjectKey     string
	ObjectVersion string
}

func (q *Queries) IsEvidenceObjectReferenced(ctx context.Context, arg IsEvidenceObjectReferencedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEvidenceObjectReferenced, arg.TenantID, arg.ObjectKey, arg.ObjectVersion)
	var referenced bool
	err := row.Scan(&referenced)
	return referenced, err
}

const lockEvidenceObjectReconciliation = `-- name: LockEvidenceObjectReconciliation :one
SELECT tenant_id, upload_id, evidence_id, upload_attempt, object_key, object_version, object_size, object_checksum, state, version, claim, available_at, lease_expires_at, created_at, updated_at, resolved_at
FROM idenqa.evidence_object_reconciliations
WHERE tenant_id = $1 AND upload_id = $2 AND upload_attempt = $3
FOR UPDATE
`

type LockEvidenceObjectReconciliationParams struct {
	TenantID      string
	UploadID      string
	UploadAttempt int32
}

func (q *Queries) LockEvidenceObjectReconciliation(ctx context.Context, arg LockEvidenceObjectReconciliationParams) (IdenqaEvidenceObjectReconciliation, error) {
	row := q.db.QueryRow(ctx, lockEvidenceObjectReconciliation, arg.TenantID, arg.UploadID, arg.UploadAttempt)
	var i IdenqaEvidenceObjectReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.UploadID,
		&i.EvidenceID,
		&i.UploadAttempt,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.ObjectSize,
		&i.ObjectChecksum,
		&i.State,
		&i.Version,
		&i.Claim,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const lockNextEvidenceObjectReconciliation = `-- name: LockNextEvidenceObjectReconciliation :one
SELECT tenant_id, upload_id, evidence_id, upload_attempt, object_key, object_version, object_size, object_checksum, state, version, claim, available_at, lease_expires_at, created_at, updated_at, resolved_at
FROM idenqa.evidence_object_reconciliations
WHERE tenant_id = $1
  AND ((state = 'pending' AND available_at <= $2)
    OR (state = 'claimed' AND lease_expires_at <= $2))
ORDER BY COALESCE(lease_expires_at, available_at), upload_id, upload_attempt
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type LockNextEvidenceObjectReconciliationParams struct {
	TenantID    string
	AvailableAt pgtype.Timestamptz
}

func (q *Queries) LockNextEvidenceObjectReconciliation(ctx context.Context, arg LockNextEvidenceObjectReconciliationParams) (IdenqaEvidenceObjectReconciliation, error) {
	row := q.db.QueryRow(ctx, lockNextEvidenceObjectReconciliation, arg.TenantID, arg.AvailableAt)
	var i IdenqaEvidenceObjectReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.UploadID,
		&i.EvidenceID,
		&i.UploadAttempt,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.ObjectSize,
		&i.ObjectChecksum,
		&i.State,
		&i.Version,
		&i.Claim,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const retainEvidenceObjectReconciliationForAcceptance = `-- name: RetainEvidenceObjectReconciliationForAcceptance :one
UPDATE idenqa.evidence_object_reconciliations
SET state = 'retained',
    version = version + 1,
    lease_expires_at = NULL,
    updated_at = $9,
    resolved_at = $9
WHERE tenant_id = $1 AND upload_id = $2 AND upload_attempt = $3
  AND evidence_id = $4 AND object_key = $5 AND object_version = $6
  AND object_size = $7 AND object_checksum = $8 AND state = 'pending'
RETURNING tenant_id, upload_id, evidence_id, upload_attempt, object_key, object_version, object_size, object_checksum, state, version, claim, available_at, lease_expires_at, created_at, updated_at, resolved_at
`

type RetainEvidenceObjectReconciliationForAcceptanceParams struct {
	TenantID       string
	UploadID       string
	UploadAttempt  int32
	EvidenceID     string
	ObjectKey      string
	ObjectVersion  string
	ObjectSize     int64
	ObjectChecksum string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) RetainEvidenceObjectReconciliationForAcceptance(ctx context.Context, arg RetainEvidenceObjectReconciliationForAcceptanceParams) (IdenqaEvidenceObjectReconciliation, error) {
	row := q.db.QueryRow(ctx, retainEvidenceObjectReconciliationForAcceptance,
		arg.TenantID,
		arg.UploadID,
		arg.UploadAttempt,
		arg.EvidenceID,
		arg.ObjectKey,
		arg.ObjectVersion,
		arg.ObjectSize,
		arg.ObjectChecksum,
		arg.UpdatedAt,
	)
	var i IdenqaEvidenceObjectReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.UploadID,
		&i.EvidenceID,
		&i.UploadAttempt,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.ObjectSize,
		&i.ObjectChecksum,
		&i.State,
		&i.Version,
		&i.Claim,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const transitionEvidenceObjectReconciliation = `-- name: TransitionEvidenceObjectReconciliation :one
UPDATE idenqa.evidence_object_reconciliations
SET state = $5,
    version = $6,
    claim = $7,
    available_at = $8,
    lease_expires_at = $9,
    updated_at = $10,
    resolved_at = $11
WHERE tenant_id = $1 AND upload_id = $2 AND upload_attempt = $3 AND version = $4
RETURNING tenant_id, upload_id, evidence_id, upload_attempt, object_key, object_version, object_size, object_checksum, state, version, claim, available_at, lease_expires_at, created_at, updated_at, resolved_at
`

type TransitionEvidenceObjectReconciliationParams struct {
	TenantID       string
	UploadID       string
	UploadAttempt  int32
	Version        int64
	State          string
	Version_2      int64
	Claim          int32
	AvailableAt    pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

func (q *Queries) TransitionEvidenceObjectReconciliation(ctx context.Context, arg TransitionEvidenceObjectReconciliationParams) (IdenqaEvidenceObjectReconciliation, error) {
	row := q.db.QueryRow(ctx, transitionEvidenceObjectReconciliation,
		arg.TenantID,
		arg.UploadID,
		arg.UploadAttempt,
		arg.Version,
		arg.State,
		arg.Version_2,
		arg.Claim,
		arg.AvailableAt,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ResolvedAt,
	)
	var i IdenqaEvidenceObjectReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.UploadID,
		&i.EvidenceID,
		&i.UploadAttempt,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.ObjectSize,
		&i.ObjectChecksum,
		&i.State,
		&i.Version,
		&i.Claim,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
