// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence_upload.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeVerificationCapture = `-- name: CompleteVerificationCapture :execrows
UPDATE idenqa.verification_sessions
SET capture_completed_at = COALESCE(capture_completed_at, $1),
    updated_at = GREATEST(updated_at, $1)
WHERE tenant_id = $2
  AND id = $3
  AND capture_completed_at IS NULL
`

type CompleteVerificationCaptureParams struct {
	CompletedAt    pgtype.Timestamptz
	TenantID       string
	VerificationID string
}

func (q *Queries) CompleteVerificationCapture(ctx context.Context, arg CompleteVerificationCaptureParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeVerificationCapture, arg.CompletedAt, arg.TenantID, arg.VerificationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEvidenceUploadIntent = `-- name: CreateEvidenceUploadIntent :exec
INSERT INTO idenqa.evidence_upload_intents (
    id, tenant_id, capture_token_id, subject_id, verification_id, evidence_id,
    authority_id, response_id, profile_id, profile_revision, profile_digest,
    registry_schema_version, registry_revision, registry_digest,
    requirement_key, purpose, evidence_type, artefact, acquisition_method,
    assurances, encryption_purpose, allowed_media_types, maximum_bytes,
    expected_bytes, expected_digest, media_type, region, retention_class,
    state, version, attempt, attempt_timeout_milliseconds, lease_expires_at,
    created_at, updated_at, expires_at, accepted_at, rejection_reason,
    fallback_condition
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35, $36, $37, $38, $39
)
`

type CreateEvidenceUploadIntentParams struct {
	ID                         string
	TenantID                   string
	CaptureTokenID             string
	SubjectID                  string
	VerificationID             string
	EvidenceID                 string
	AuthorityID                string
	ResponseID                 string
	ProfileID                  string
	ProfileRevision            int32
	ProfileDigest              string
	RegistrySchemaVersion      int32
	RegistryRevision           int32
	RegistryDigest             string
	RequirementKey             string
	Purpose                    string
	EvidenceType               string
	Artefact                   string
	AcquisitionMethod          string
	Assurances                 []string
	EncryptionPurpose          string
	AllowedMediaTypes          []string
	MaximumBytes               int64
	ExpectedBytes              int64
	ExpectedDigest             string
	MediaType                  string
	Region                     string
	RetentionClass             string
	State                      string
	Version                    int64
	Attempt                    int32
	AttemptTimeoutMilliseconds int64
	LeaseExpiresAt             pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	ExpiresAt                  pgtype.Timestamptz
	AcceptedAt                 pgtype.Timestamptz
	RejectionReason            *string
	FallbackCondition          *string
}

func (q *Queries) CreateEvidenceUploadIntent(ctx context.Context, arg CreateEvidenceUploadIntentParams) error {
	_, err := q.db.Exec(ctx, createEvidenceUploadIntent,
		arg.ID,
		arg.TenantID,
		arg.CaptureTokenID,
		arg.SubjectID,
		arg.VerificationID,
		arg.EvidenceID,
		arg.AuthorityID,
		arg.ResponseID,
		arg.ProfileID,
		arg.ProfileRevision,
		arg.ProfileDigest,
		arg.RegistrySchemaVersion,
		arg.RegistryRevision,
		arg.RegistryDigest,
		arg.RequirementKey,
		arg.Purpose,
		arg.EvidenceType,
		arg.Artefact,
		arg.AcquisitionMethod,
		arg.Assurances,
		arg.EncryptionPurpose,
		arg.AllowedMediaTypes,
		arg.MaximumBytes,
		arg.ExpectedBytes,
		arg.ExpectedDigest,
		arg.MediaType,
		arg.Region,
		arg.RetentionClass,
		arg.State,
		arg.Version,
		arg.Attempt,
		arg.AttemptTimeoutMilliseconds,
		arg.LeaseExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.AcceptedAt,
		arg.RejectionReason,
		arg.FallbackCondition,
	)
	return err
}

const findEvidenceUploadIntent = `-- name: FindEvidenceUploadIntent :one
SELECT id, tenant_id, capture_token_id, subject_id, verification_id, evidence_id, authority_id, response_id, profile_id, profile_revision, profile_digest, registry_schema_version, registry_revision, registry_digest, requirement_key, purpose, evidence_type, artefact, acquisition_method, assurances, encryption_purpose, allowed_media_types, maximum_bytes, expected_bytes, expected_digest, media_type, region, retention_class, state, version, attempt, attempt_timeout_milliseconds, lease_expires_at, created_at, updated_at, expires_at, accepted_at, rejection_reason, fallback_condition
FROM idenqa.evidence_upload_intents
WHERE tenant_id = $1 AND id = $2
`

type FindEvidenceUploadIntentParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindEvidenceUploadIntent(ctx context.Context, arg FindEvidenceUploadIntentParams) (IdenqaEvidenceUploadIntent, error) {
	row := q.db.QueryRow(ctx, findEvidenceUploadIntent, arg.TenantID, arg.ID)
	var i IdenqaEvidenceUploadIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CaptureTokenID,
		&i.SubjectID,
		&i.VerificationID,
		&i.EvidenceID,
		&i.AuthorityID,
		&i.ResponseID,
		&i.ProfileID,
		&i.ProfileRevision,
		&i.ProfileDigest,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.RequirementKey,
		&i.Purpose,
		&i.EvidenceType,
		&i.Artefact,
		&i.AcquisitionMethod,
		&i.Assurances,
		&i.EncryptionPurpose,
		&i.AllowedMediaTypes,
		&i.MaximumBytes,
		&i.ExpectedBytes,
		&i.ExpectedDigest,
		&i.MediaType,
		&i.Region,
		&i.RetentionClass,
		&i.State,
		&i.Version,
		&i.Attempt,
		&i.AttemptTimeoutMilliseconds,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectionReason,
		&i.FallbackCondition,
	)
	return i, err
}

const insertEvidenceUploadIntentAudit = `-- name: InsertEvidenceUploadIntentAudit :exec
INSERT INTO idenqa.evidence_upload_intent_audit (
    tenant_id, upload_id, aggregate_version, attempt,
    action, principal_id, reason, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEvidenceUploadIntentAuditParams struct {
	TenantID         string
	UploadID         string
	AggregateVersion int64
	Attempt          int32
	Action           string
	PrincipalID      string
	Reason           *string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) InsertEvidenceUploadIntentAudit(ctx context.Context, arg InsertEvidenceUploadIntentAuditParams) error {
	_, err := q.db.Exec(ctx, insertEvidenceUploadIntentAudit,
		arg.TenantID,
		arg.UploadID,
		arg.AggregateVersion,
		arg.Attempt,
		arg.Action,
		arg.PrincipalID,
		arg.Reason,
		arg.OccurredAt,
	)
	return err
}

const listAcceptedEvidenceUploadIntents = `-- name: ListAcceptedEvidenceUploadIntents :many
SELECT evidence_upload_intents.id, evidence_upload_intents.tenant_id, evidence_upload_intents.capture_token_id, evidence_upload_intents.subject_id, evidence_upload_intents.verification_id, evidence_upload_intents.evidence_id, evidence_upload_intents.authority_id, evidence_upload_intents.response_id, evidence_upload_intents.profile_id, evidence_upload_intents.profile_revision, evidence_upload_intents.profile_digest, evidence_upload_intents.registry_schema_version, evidence_upload_intents.registry_revision, evidence_upload_intents.registry_digest, evidence_upload_intents.requirement_key, evidence_upload_intents.purpose, evidence_upload_intents.evidence_type, evidence_upload_intents.artefact, evidence_upload_intents.acquisition_method, evidence_upload_intents.assurances, evidence_upload_intents.encryption_purpose, evidence_upload_intents.allowed_media_types, evidence_upload_intents.maximum_bytes, evidence_upload_intents.expected_bytes, evidence_upload_intents.expected_digest, evidence_upload_intents.media_type, evidence_upload_intents.region, evidence_upload_intents.retention_class, evidence_upload_intents.state, evidence_upload_intents.version, evidence_upload_intents.attempt, evidence_upload_intents.attempt_timeout_milliseconds, evidence_upload_intents.lease_expires_at, evidence_upload_intents.created_at, evidence_upload_intents.updated_at, evidence_upload_intents.expires_at, evidence_upload_intents.accepted_at, evidence_upload_intents.rejection_reason, evidence_upload_intents.fallback_condition
FROM idenqa.evidence_upload_intents
WHERE evidence_upload_intents.tenant_id = $1
  AND (evidence_upload_intents.capture_token_id = $2 OR EXISTS (
    SELECT 1 FROM idenqa.capture_recovery_uploads recovery
    WHERE recovery.tenant_id=evidence_upload_intents.tenant_id AND recovery.new_token_id=$2
      AND recovery.upload_id=evidence_upload_intents.id AND recovery.disposition='retained'
  ))
  AND EXISTS(SELECT 1 FROM idenqa.capture_tokens token WHERE token.tenant_id=evidence_upload_intents.tenant_id AND token.id=$2 AND token.verification_id=$3 AND token.revoked_at IS NULL)
  AND evidence_upload_intents.verification_id = $3
  AND evidence_upload_intents.state = 'accepted'
ORDER BY evidence_upload_intents.accepted_at, evidence_upload_intents.id
LIMIT $4
`

type ListAcceptedEvidenceUploadIntentsParams struct {
	TenantID       string
	CaptureTokenID string
	VerificationID string
	Limit          int32
}

func (q *Queries) ListAcceptedEvidenceUploadIntents(ctx context.Context, arg ListAcceptedEvidenceUploadIntentsParams) ([]IdenqaEvidenceUploadIntent, error) {
	rows, err := q.db.Query(ctx, listAcceptedEvidenceUploadIntents,
		arg.TenantID,
		arg.CaptureTokenID,
		arg.VerificationID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdenqaEvidenceUploadIntent
	for rows.Next() {
		var i IdenqaEvidenceUploadIntent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CaptureTokenID,
			&i.SubjectID,
			&i.VerificationID,
			&i.EvidenceID,
			&i.AuthorityID,
			&i.ResponseID,
			&i.ProfileID,
			&i.ProfileRevision,
			&i.ProfileDigest,
			&i.RegistrySchemaVersion,
			&i.RegistryRevision,
			&i.RegistryDigest,
			&i.RequirementKey,
			&i.Purpose,
			&i.EvidenceType,
			&i.Artefact,
			&i.AcquisitionMethod,
			&i.Assurances,
			&i.EncryptionPurpose,
			&i.AllowedMediaTypes,
			&i.MaximumBytes,
			&i.ExpectedBytes,
			&i.ExpectedDigest,
			&i.MediaType,
			&i.Region,
			&i.RetentionClass,
			&i.State,
			&i.Version,
			&i.Attempt,
			&i.AttemptTimeoutMilliseconds,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RejectionReason,
			&i.FallbackCondition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadCaptureProgressPublication = `-- name: LoadCaptureProgressPublication :one
SELECT
    sessions.requirements,
    tokens.expires_at AS capture_token_expires_at,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'requirement_key', uploads.requirement_key,
                'artefact', uploads.artefact,
                'acquisition_method', uploads.acquisition_method
            )
            ORDER BY uploads.accepted_at, uploads.id
        ) FILTER (WHERE uploads.state = 'accepted'),
        '[]'::jsonb
    )::text AS accepted_bindings
FROM idenqa.verification_sessions AS sessions
JOIN idenqa.capture_tokens AS tokens
  ON tokens.tenant_id = sessions.tenant_id
 AND tokens.verification_id = sessions.id
LEFT JOIN idenqa.evidence_upload_intents AS uploads
  ON uploads.tenant_id = sessions.tenant_id
 AND uploads.verification_id = sessions.id
 AND (uploads.capture_token_id = tokens.id OR EXISTS (
 SELECT 1 FROM idenqa.capture_recovery_uploads recovery
 WHERE recovery.tenant_id=uploads.tenant_id AND recovery.new_token_id=tokens.id
 AND recovery.upload_id=uploads.id AND recovery.disposition='retained'))
WHERE sessions.tenant_id = $1
  AND sessions.id = $2
  AND tokens.id = $3
  AND tokens.revoked_at IS NULL
GROUP BY sessions.requirements, tokens.expires_at
`

type LoadCaptureProgressPublicationParams struct {
	TenantID       string
	VerificationID string
	CaptureTokenID string
}

type LoadCaptureProgressPublicationRow struct {
	Requirements          []byte
	CaptureTokenExpiresAt pgtype.Timestamptz
	AcceptedBindings      string
}

func (q *Queries) LoadCaptureProgressPublication(ctx context.Context, arg LoadCaptureProgressPublicationParams) (LoadCaptureProgressPublicationRow, error) {
	row := q.db.QueryRow(ctx, loadCaptureProgressPublication, arg.TenantID, arg.VerificationID, arg.CaptureTokenID)
	var i LoadCaptureProgressPublicationRow
	err := row.Scan(&i.Requirements, &i.CaptureTokenExpiresAt, &i.AcceptedBindings)
	return i, err
}

const lockCaptureTokenForUpload = `-- name: LockCaptureTokenForUpload :one
SELECT id, tenant_id, verification_id, key_version, issued_at, expires_at, revoked_at, native_application_id, native_proof_key_digest, native_bound_at FROM idenqa.capture_tokens
WHERE tenant_id = $1 AND id = $2 AND verification_id = $3
FOR SHARE
`

type LockCaptureTokenForUploadParams struct {
	TenantID       string
	ID             string
	VerificationID string
}

func (q *Queries) LockCaptureTokenForUpload(ctx context.Context, arg LockCaptureTokenForUploadParams) (IdenqaCaptureToken, error) {
	row := q.db.QueryRow(ctx, lockCaptureTokenForUpload, arg.TenantID, arg.ID, arg.VerificationID)
	var i IdenqaCaptureToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VerificationID,
		&i.KeyVersion,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.NativeApplicationID,
		&i.NativeProofKeyDigest,
		&i.NativeBoundAt,
	)
	return i, err
}

const lockEvidenceUploadIntent = `-- name: LockEvidenceUploadIntent :one
SELECT id, tenant_id, capture_token_id, subject_id, verification_id, evidence_id, authority_id, response_id, profile_id, profile_revision, profile_digest, registry_schema_version, registry_revision, registry_digest, requirement_key, purpose, evidence_type, artefact, acquisition_method, assurances, encryption_purpose, allowed_media_types, maximum_bytes, expected_bytes, expected_digest, media_type, region, retention_class, state, version, attempt, attempt_timeout_milliseconds, lease_expires_at, created_at, updated_at, expires_at, accepted_at, rejection_reason, fallback_condition
FROM idenqa.evidence_upload_intents
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockEvidenceUploadIntentParams struct {
	TenantID string
	ID       string
}

func (q *Queries) LockEvidenceUploadIntent(ctx context.Context, arg LockEvidenceUploadIntentParams) (IdenqaEvidenceUploadIntent, error) {
	row := q.db.QueryRow(ctx, lockEvidenceUploadIntent, arg.TenantID, arg.ID)
	var i IdenqaEvidenceUploadIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CaptureTokenID,
		&i.SubjectID,
		&i.VerificationID,
		&i.EvidenceID,
		&i.AuthorityID,
		&i.ResponseID,
		&i.ProfileID,
		&i.ProfileRevision,
		&i.ProfileDigest,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.RequirementKey,
		&i.Purpose,
		&i.EvidenceType,
		&i.Artefact,
		&i.AcquisitionMethod,
		&i.Assurances,
		&i.EncryptionPurpose,
		&i.AllowedMediaTypes,
		&i.MaximumBytes,
		&i.ExpectedBytes,
		&i.ExpectedDigest,
		&i.MediaType,
		&i.Region,
		&i.RetentionClass,
		&i.State,
		&i.Version,
		&i.Attempt,
		&i.AttemptTimeoutMilliseconds,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectionReason,
		&i.FallbackCondition,
	)
	return i, err
}

const lockVerificationForUpload = `-- name: LockVerificationForUpload :one
SELECT id, tenant_id, state, version, source_profile_id, source_profile_revision, source_profile_digest, requirements, created_at, updated_at, expires_at, subject_id, authority_id, notice_id, region, policy_id, decision_id, capture_completed_at, completed_decision_id, expiry_discovered_at, failure_class, failure_code FROM idenqa.verification_sessions
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockVerificationForUploadParams struct {
	TenantID string
	ID       string
}

func (q *Queries) LockVerificationForUpload(ctx context.Context, arg LockVerificationForUploadParams) (IdenqaVerificationSession, error) {
	row := q.db.QueryRow(ctx, lockVerificationForUpload, arg.TenantID, arg.ID)
	var i IdenqaVerificationSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.State,
		&i.Version,
		&i.SourceProfileID,
		&i.SourceProfileRevision,
		&i.SourceProfileDigest,
		&i.Requirements,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.SubjectID,
		&i.AuthorityID,
		&i.NoticeID,
		&i.Region,
		&i.PolicyID,
		&i.DecisionID,
		&i.CaptureCompletedAt,
		&i.CompletedDecisionID,
		&i.ExpiryDiscoveredAt,
		&i.FailureClass,
		&i.FailureCode,
	)
	return i, err
}

const transitionEvidenceUploadIntent = `-- name: TransitionEvidenceUploadIntent :one
UPDATE idenqa.evidence_upload_intents
SET state = $4,
    version = $5,
    attempt = $6,
    lease_expires_at = $7,
    updated_at = $8,
    accepted_at = $9,
    rejection_reason = $10
WHERE tenant_id = $1 AND id = $2 AND version = $3
RETURNING id, tenant_id, capture_token_id, subject_id, verification_id, evidence_id, authority_id, response_id, profile_id, profile_revision, profile_digest, registry_schema_version, registry_revision, registry_digest, requirement_key, purpose, evidence_type, artefact, acquisition_method, assurances, encryption_purpose, allowed_media_types, maximum_bytes, expected_bytes, expected_digest, media_type, region, retention_class, state, version, attempt, attempt_timeout_milliseconds, lease_expires_at, created_at, updated_at, expires_at, accepted_at, rejection_reason, fallback_condition
`

type TransitionEvidenceUploadIntentParams struct {
	TenantID        string
	ID              string
	Version         int64
	State           string
	Version_2       int64
	Attempt         int32
	LeaseExpiresAt  pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	AcceptedAt      pgtype.Timestamptz
	RejectionReason *string
}

func (q *Queries) TransitionEvidenceUploadIntent(ctx context.Context, arg TransitionEvidenceUploadIntentParams) (IdenqaEvidenceUploadIntent, error) {
	row := q.db.QueryRow(ctx, transitionEvidenceUploadIntent,
		arg.TenantID,
		arg.ID,
		arg.Version,
		arg.State,
		arg.Version_2,
		arg.Attempt,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.AcceptedAt,
		arg.RejectionReason,
	)
	var i IdenqaEvidenceUploadIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CaptureTokenID,
		&i.SubjectID,
		&i.VerificationID,
		&i.EvidenceID,
		&i.AuthorityID,
		&i.ResponseID,
		&i.ProfileID,
		&i.ProfileRevision,
		&i.ProfileDigest,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.RequirementKey,
		&i.Purpose,
		&i.EvidenceType,
		&i.Artefact,
		&i.AcquisitionMethod,
		&i.Assurances,
		&i.EncryptionPurpose,
		&i.AllowedMediaTypes,
		&i.MaximumBytes,
		&i.ExpectedBytes,
		&i.ExpectedDigest,
		&i.MediaType,
		&i.Region,
		&i.RetentionClass,
		&i.State,
		&i.Version,
		&i.Attempt,
		&i.AttemptTimeoutMilliseconds,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectionReason,
		&i.FallbackCondition,
	)
	return i, err
}
