// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence_grant.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeniedEvidenceGrantRedemption = `-- name: CreateDeniedEvidenceGrantRedemption :exec
INSERT INTO idenqa.evidence_grant_redemptions (
    id, tenant_id, grant_id, runner_identity, workload_version, claimed_use,
    denial_reason, attempted_at
) VALUES ($1, $2, $3, $4, $5, NULL, $6, $7)
`

type CreateDeniedEvidenceGrantRedemptionParams struct {
	ID              string
	TenantID        string
	GrantID         string
	RunnerIdentity  string
	WorkloadVersion string
	DenialReason    *string
	AttemptedAt     pgtype.Timestamptz
}

func (q *Queries) CreateDeniedEvidenceGrantRedemption(ctx context.Context, arg CreateDeniedEvidenceGrantRedemptionParams) error {
	_, err := q.db.Exec(ctx, createDeniedEvidenceGrantRedemption,
		arg.ID,
		arg.TenantID,
		arg.GrantID,
		arg.RunnerIdentity,
		arg.WorkloadVersion,
		arg.DenialReason,
		arg.AttemptedAt,
	)
	return err
}

const createEvidenceGrantRedemptionOutcome = `-- name: CreateEvidenceGrantRedemptionOutcome :execrows
INSERT INTO idenqa.evidence_grant_redemption_outcomes (
    tenant_id, redemption_id, grant_id, outcome, denial_reason, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, redemption_id) DO NOTHING
`

type CreateEvidenceGrantRedemptionOutcomeParams struct {
	TenantID     string
	RedemptionID string
	GrantID      string
	Outcome      string
	DenialReason *string
	OccurredAt   pgtype.Timestamptz
}

func (q *Queries) CreateEvidenceGrantRedemptionOutcome(ctx context.Context, arg CreateEvidenceGrantRedemptionOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, createEvidenceGrantRedemptionOutcome,
		arg.TenantID,
		arg.RedemptionID,
		arg.GrantID,
		arg.Outcome,
		arg.DenialReason,
		arg.OccurredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEvidenceProcessingGrant = `-- name: CreateEvidenceProcessingGrant :exec
INSERT INTO idenqa.evidence_processing_grants (
    id, tenant_id, subject_id, verification_id, evidence_id, requirement_key,
    authority_id, response_id, check_reference, runner_identity, workload_version,
    purpose, operation, permitted_variants, region, recipient_reference,
    output_destination, policy_reference, maximum_uses, uses, created_at,
    expires_at, revoked_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
)
`

type CreateEvidenceProcessingGrantParams struct {
	ID                 string
	TenantID           string
	SubjectID          string
	VerificationID     string
	EvidenceID         string
	RequirementKey     string
	AuthorityID        string
	ResponseID         string
	CheckReference     string
	RunnerIdentity     string
	WorkloadVersion    string
	Purpose            string
	Operation          string
	PermittedVariants  []string
	Region             string
	RecipientReference string
	OutputDestination  string
	PolicyReference    string
	MaximumUses        int32
	Uses               int32
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
}

func (q *Queries) CreateEvidenceProcessingGrant(ctx context.Context, arg CreateEvidenceProcessingGrantParams) error {
	_, err := q.db.Exec(ctx, createEvidenceProcessingGrant,
		arg.ID,
		arg.TenantID,
		arg.SubjectID,
		arg.VerificationID,
		arg.EvidenceID,
		arg.RequirementKey,
		arg.AuthorityID,
		arg.ResponseID,
		arg.CheckReference,
		arg.RunnerIdentity,
		arg.WorkloadVersion,
		arg.Purpose,
		arg.Operation,
		arg.PermittedVariants,
		arg.Region,
		arg.RecipientReference,
		arg.OutputDestination,
		arg.PolicyReference,
		arg.MaximumUses,
		arg.Uses,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}

const createPendingEvidenceGrantRedemption = `-- name: CreatePendingEvidenceGrantRedemption :exec
INSERT INTO idenqa.evidence_grant_redemptions (
    id, tenant_id, grant_id, runner_identity, workload_version, claimed_use,
    denial_reason, attempted_at
) VALUES ($1, $2, $3, $4, $5, $6, NULL, $7)
`

type CreatePendingEvidenceGrantRedemptionParams struct {
	ID              string
	TenantID        string
	GrantID         string
	RunnerIdentity  string
	WorkloadVersion string
	ClaimedUse      *int32
	AttemptedAt     pgtype.Timestamptz
}

func (q *Queries) CreatePendingEvidenceGrantRedemption(ctx context.Context, arg CreatePendingEvidenceGrantRedemptionParams) error {
	_, err := q.db.Exec(ctx, createPendingEvidenceGrantRedemption,
		arg.ID,
		arg.TenantID,
		arg.GrantID,
		arg.RunnerIdentity,
		arg.WorkloadVersion,
		arg.ClaimedUse,
		arg.AttemptedAt,
	)
	return err
}

const findEvidenceGrantRedemption = `-- name: FindEvidenceGrantRedemption :one
SELECT id, tenant_id, grant_id, runner_identity, workload_version, claimed_use, denial_reason, attempted_at FROM idenqa.evidence_grant_redemptions
WHERE tenant_id = $1 AND id = $2
`

type FindEvidenceGrantRedemptionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindEvidenceGrantRedemption(ctx context.Context, arg FindEvidenceGrantRedemptionParams) (IdenqaEvidenceGrantRedemption, error) {
	row := q.db.QueryRow(ctx, findEvidenceGrantRedemption, arg.TenantID, arg.ID)
	var i IdenqaEvidenceGrantRedemption
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GrantID,
		&i.RunnerIdentity,
		&i.WorkloadVersion,
		&i.ClaimedUse,
		&i.DenialReason,
		&i.AttemptedAt,
	)
	return i, err
}

const findEvidenceGrantRedemptionOutcome = `-- name: FindEvidenceGrantRedemptionOutcome :one
SELECT tenant_id, redemption_id, grant_id, outcome, denial_reason, occurred_at FROM idenqa.evidence_grant_redemption_outcomes
WHERE tenant_id = $1 AND redemption_id = $2 AND grant_id = $3
`

type FindEvidenceGrantRedemptionOutcomeParams struct {
	TenantID     string
	RedemptionID string
	GrantID      string
}

func (q *Queries) FindEvidenceGrantRedemptionOutcome(ctx context.Context, arg FindEvidenceGrantRedemptionOutcomeParams) (IdenqaEvidenceGrantRedemptionOutcome, error) {
	row := q.db.QueryRow(ctx, findEvidenceGrantRedemptionOutcome, arg.TenantID, arg.RedemptionID, arg.GrantID)
	var i IdenqaEvidenceGrantRedemptionOutcome
	err := row.Scan(
		&i.TenantID,
		&i.RedemptionID,
		&i.GrantID,
		&i.Outcome,
		&i.DenialReason,
		&i.OccurredAt,
	)
	return i, err
}

const findEvidenceProcessingGrant = `-- name: FindEvidenceProcessingGrant :one
SELECT id, tenant_id, subject_id, verification_id, evidence_id, requirement_key, authority_id, response_id, check_reference, runner_identity, workload_version, purpose, operation, permitted_variants, region, recipient_reference, output_destination, policy_reference, maximum_uses, uses, created_at, expires_at, revoked_at FROM idenqa.evidence_processing_grants
WHERE tenant_id = $1 AND id = $2
`

type FindEvidenceProcessingGrantParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindEvidenceProcessingGrant(ctx context.Context, arg FindEvidenceProcessingGrantParams) (IdenqaEvidenceProcessingGrant, error) {
	row := q.db.QueryRow(ctx, findEvidenceProcessingGrant, arg.TenantID, arg.ID)
	var i IdenqaEvidenceProcessingGrant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.EvidenceID,
		&i.RequirementKey,
		&i.AuthorityID,
		&i.ResponseID,
		&i.CheckReference,
		&i.RunnerIdentity,
		&i.WorkloadVersion,
		&i.Purpose,
		&i.Operation,
		&i.PermittedVariants,
		&i.Region,
		&i.RecipientReference,
		&i.OutputDestination,
		&i.PolicyReference,
		&i.MaximumUses,
		&i.Uses,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const incrementEvidenceProcessingGrantUse = `-- name: IncrementEvidenceProcessingGrantUse :one
UPDATE idenqa.evidence_processing_grants
SET uses = uses + 1
WHERE tenant_id = $1 AND id = $2 AND uses = $3
RETURNING id, tenant_id, subject_id, verification_id, evidence_id, requirement_key, authority_id, response_id, check_reference, runner_identity, workload_version, purpose, operation, permitted_variants, region, recipient_reference, output_destination, policy_reference, maximum_uses, uses, created_at, expires_at, revoked_at
`

type IncrementEvidenceProcessingGrantUseParams struct {
	TenantID string
	ID       string
	Uses     int32
}

func (q *Queries) IncrementEvidenceProcessingGrantUse(ctx context.Context, arg IncrementEvidenceProcessingGrantUseParams) (IdenqaEvidenceProcessingGrant, error) {
	row := q.db.QueryRow(ctx, incrementEvidenceProcessingGrantUse, arg.TenantID, arg.ID, arg.Uses)
	var i IdenqaEvidenceProcessingGrant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.EvidenceID,
		&i.RequirementKey,
		&i.AuthorityID,
		&i.ResponseID,
		&i.CheckReference,
		&i.RunnerIdentity,
		&i.WorkloadVersion,
		&i.Purpose,
		&i.Operation,
		&i.PermittedVariants,
		&i.Region,
		&i.RecipientReference,
		&i.OutputDestination,
		&i.PolicyReference,
		&i.MaximumUses,
		&i.Uses,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertEvidenceGrantAccessAttemptAudit = `-- name: InsertEvidenceGrantAccessAttemptAudit :exec
INSERT INTO idenqa.evidence_grant_access_attempt_audit (
    tenant_id, presented_grant_id, redemption_id, runner_identity,
    workload_version, decision, denial_reason, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEvidenceGrantAccessAttemptAuditParams struct {
	TenantID         string
	PresentedGrantID string
	RedemptionID     string
	RunnerIdentity   string
	WorkloadVersion  string
	Decision         string
	DenialReason     *string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) InsertEvidenceGrantAccessAttemptAudit(ctx context.Context, arg InsertEvidenceGrantAccessAttemptAuditParams) error {
	_, err := q.db.Exec(ctx, insertEvidenceGrantAccessAttemptAudit,
		arg.TenantID,
		arg.PresentedGrantID,
		arg.RedemptionID,
		arg.RunnerIdentity,
		arg.WorkloadVersion,
		arg.Decision,
		arg.DenialReason,
		arg.OccurredAt,
	)
	return err
}

const insertEvidenceProcessingGrantAudit = `-- name: InsertEvidenceProcessingGrantAudit :exec
INSERT INTO idenqa.evidence_processing_grant_audit (
    tenant_id, grant_id, aggregate_version, action, principal_type,
    principal_id, tenant_actor_type, tenant_actor_id, reason, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertEvidenceProcessingGrantAuditParams struct {
	TenantID         string
	GrantID          string
	AggregateVersion int32
	Action           string
	PrincipalType    string
	PrincipalID      string
	TenantActorType  string
	TenantActorID    string
	Reason           string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) InsertEvidenceProcessingGrantAudit(ctx context.Context, arg InsertEvidenceProcessingGrantAuditParams) error {
	_, err := q.db.Exec(ctx, insertEvidenceProcessingGrantAudit,
		arg.TenantID,
		arg.GrantID,
		arg.AggregateVersion,
		arg.Action,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.TenantActorType,
		arg.TenantActorID,
		arg.Reason,
		arg.OccurredAt,
	)
	return err
}

const lockEvidenceGrantRedemptionID = `-- name: LockEvidenceGrantRedemptionID :one
SELECT true
FROM pg_advisory_xact_lock(hashtextextended(
    concat_ws(E'\x1f', 'evidence_grant_redemption', $1::text,
              $2::text),
    0
))
`

type LockEvidenceGrantRedemptionIDParams struct {
	TenantID     string
	RedemptionID string
}

func (q *Queries) LockEvidenceGrantRedemptionID(ctx context.Context, arg LockEvidenceGrantRedemptionIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockEvidenceGrantRedemptionID, arg.TenantID, arg.RedemptionID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const lockEvidenceProcessingGrant = `-- name: LockEvidenceProcessingGrant :one
SELECT id, tenant_id, subject_id, verification_id, evidence_id, requirement_key, authority_id, response_id, check_reference, runner_identity, workload_version, purpose, operation, permitted_variants, region, recipient_reference, output_destination, policy_reference, maximum_uses, uses, created_at, expires_at, revoked_at FROM idenqa.evidence_processing_grants
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockEvidenceProcessingGrantParams struct {
	TenantID string
	ID       string
}

func (q *Queries) LockEvidenceProcessingGrant(ctx context.Context, arg LockEvidenceProcessingGrantParams) (IdenqaEvidenceProcessingGrant, error) {
	row := q.db.QueryRow(ctx, lockEvidenceProcessingGrant, arg.TenantID, arg.ID)
	var i IdenqaEvidenceProcessingGrant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.EvidenceID,
		&i.RequirementKey,
		&i.AuthorityID,
		&i.ResponseID,
		&i.CheckReference,
		&i.RunnerIdentity,
		&i.WorkloadVersion,
		&i.Purpose,
		&i.Operation,
		&i.PermittedVariants,
		&i.Region,
		&i.RecipientReference,
		&i.OutputDestination,
		&i.PolicyReference,
		&i.MaximumUses,
		&i.Uses,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeEvidenceProcessingGrant = `-- name: RevokeEvidenceProcessingGrant :one
UPDATE idenqa.evidence_processing_grants
SET revoked_at = $3
WHERE tenant_id = $1 AND id = $2 AND revoked_at IS NULL
RETURNING id, tenant_id, subject_id, verification_id, evidence_id, requirement_key, authority_id, response_id, check_reference, runner_identity, workload_version, purpose, operation, permitted_variants, region, recipient_reference, output_destination, policy_reference, maximum_uses, uses, created_at, expires_at, revoked_at
`

type RevokeEvidenceProcessingGrantParams struct {
	TenantID  string
	ID        string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeEvidenceProcessingGrant(ctx context.Context, arg RevokeEvidenceProcessingGrantParams) (IdenqaEvidenceProcessingGrant, error) {
	row := q.db.QueryRow(ctx, revokeEvidenceProcessingGrant, arg.TenantID, arg.ID, arg.RevokedAt)
	var i IdenqaEvidenceProcessingGrant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.EvidenceID,
		&i.RequirementKey,
		&i.AuthorityID,
		&i.ResponseID,
		&i.CheckReference,
		&i.RunnerIdentity,
		&i.WorkloadVersion,
		&i.Purpose,
		&i.Operation,
		&i.PermittedVariants,
		&i.Region,
		&i.RecipientReference,
		&i.OutputDestination,
		&i.PolicyReference,
		&i.MaximumUses,
		&i.Uses,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
