// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvidenceAsset = `-- name: CreateEvidenceAsset :exec
INSERT INTO idenqa.evidence_assets (
    id, tenant_id, subject_id, verification_id, requirement_key, evidence_type,
    artefact, acquisition_method, assurances, registry_schema_version,
    registry_revision, registry_digest, region, retention_class, content_revision,
    object_key, object_version, ciphertext_size, ciphertext_checksum,
    envelope_format_version, content_algorithm, key_purpose, key_provider,
    key_reference, key_version, key_algorithm, wrapped_key,
    context_schema_version, context_digest, plaintext_digest, media_type,
    integrity, state, version, created_at, updated_at, quarantine_reason, quarantined_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35, $36, $37, $38
)
`

type CreateEvidenceAssetParams struct {
	ID                    string
	TenantID              string
	SubjectID             string
	VerificationID        string
	RequirementKey        string
	EvidenceType          string
	Artefact              string
	AcquisitionMethod     string
	Assurances            []string
	RegistrySchemaVersion int32
	RegistryRevision      int32
	RegistryDigest        string
	Region                string
	RetentionClass        string
	ContentRevision       int32
	ObjectKey             string
	ObjectVersion         string
	CiphertextSize        int64
	CiphertextChecksum    string
	EnvelopeFormatVersion int32
	ContentAlgorithm      string
	KeyPurpose            string
	KeyProvider           string
	KeyReference          string
	KeyVersion            string
	KeyAlgorithm          string
	WrappedKey            []byte
	ContextSchemaVersion  int32
	ContextDigest         string
	PlaintextDigest       string
	MediaType             string
	Integrity             string
	State                 string
	Version               int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	QuarantineReason      *string
	QuarantinedAt         pgtype.Timestamptz
}

func (q *Queries) CreateEvidenceAsset(ctx context.Context, arg CreateEvidenceAssetParams) error {
	_, err := q.db.Exec(ctx, createEvidenceAsset,
		arg.ID,
		arg.TenantID,
		arg.SubjectID,
		arg.VerificationID,
		arg.RequirementKey,
		arg.EvidenceType,
		arg.Artefact,
		arg.AcquisitionMethod,
		arg.Assurances,
		arg.RegistrySchemaVersion,
		arg.RegistryRevision,
		arg.RegistryDigest,
		arg.Region,
		arg.RetentionClass,
		arg.ContentRevision,
		arg.ObjectKey,
		arg.ObjectVersion,
		arg.CiphertextSize,
		arg.CiphertextChecksum,
		arg.EnvelopeFormatVersion,
		arg.ContentAlgorithm,
		arg.KeyPurpose,
		arg.KeyProvider,
		arg.KeyReference,
		arg.KeyVersion,
		arg.KeyAlgorithm,
		arg.WrappedKey,
		arg.ContextSchemaVersion,
		arg.ContextDigest,
		arg.PlaintextDigest,
		arg.MediaType,
		arg.Integrity,
		arg.State,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.QuarantineReason,
		arg.QuarantinedAt,
	)
	return err
}

const findEvidenceAsset = `-- name: FindEvidenceAsset :one
SELECT id, tenant_id, subject_id, verification_id, requirement_key, evidence_type, artefact, acquisition_method, assurances, registry_schema_version, registry_revision, registry_digest, region, retention_class, content_revision, object_key, object_version, ciphertext_size, ciphertext_checksum, envelope_format_version, content_algorithm, key_purpose, key_provider, key_reference, key_version, key_algorithm, wrapped_key, context_schema_version, context_digest, plaintext_digest, media_type, integrity, state, version, created_at, updated_at, quarantine_reason, quarantined_at FROM idenqa.evidence_assets
WHERE tenant_id = $1 AND id = $2
`

type FindEvidenceAssetParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindEvidenceAsset(ctx context.Context, arg FindEvidenceAssetParams) (IdenqaEvidenceAsset, error) {
	row := q.db.QueryRow(ctx, findEvidenceAsset, arg.TenantID, arg.ID)
	var i IdenqaEvidenceAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.RequirementKey,
		&i.EvidenceType,
		&i.Artefact,
		&i.AcquisitionMethod,
		&i.Assurances,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Region,
		&i.RetentionClass,
		&i.ContentRevision,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.CiphertextSize,
		&i.CiphertextChecksum,
		&i.EnvelopeFormatVersion,
		&i.ContentAlgorithm,
		&i.KeyPurpose,
		&i.KeyProvider,
		&i.KeyReference,
		&i.KeyVersion,
		&i.KeyAlgorithm,
		&i.WrappedKey,
		&i.ContextSchemaVersion,
		&i.ContextDigest,
		&i.PlaintextDigest,
		&i.MediaType,
		&i.Integrity,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuarantineReason,
		&i.QuarantinedAt,
	)
	return i, err
}

const insertEvidenceAssetAudit = `-- name: InsertEvidenceAssetAudit :exec
INSERT INTO idenqa.evidence_asset_audit (
    tenant_id, evidence_id, aggregate_version, action, reason, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEvidenceAssetAuditParams struct {
	TenantID         string
	EvidenceID       string
	AggregateVersion int64
	Action           string
	Reason           *string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) InsertEvidenceAssetAudit(ctx context.Context, arg InsertEvidenceAssetAuditParams) error {
	_, err := q.db.Exec(ctx, insertEvidenceAssetAudit,
		arg.TenantID,
		arg.EvidenceID,
		arg.AggregateVersion,
		arg.Action,
		arg.Reason,
		arg.OccurredAt,
	)
	return err
}

const insertEvidenceKeyRewrapAudit = `-- name: InsertEvidenceKeyRewrapAudit :exec
INSERT INTO idenqa.evidence_key_rewrap_audit (
    tenant_id, evidence_id, aggregate_version,
    previous_key_provider, previous_key_reference, previous_key_version, previous_key_algorithm,
    new_key_provider, new_key_reference, new_key_version, new_key_algorithm,
    principal_type, principal_id, tenant_actor_type, tenant_actor_id, reason, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17
)
`

type InsertEvidenceKeyRewrapAuditParams struct {
	TenantID             string
	EvidenceID           string
	AggregateVersion     int64
	PreviousKeyProvider  string
	PreviousKeyReference string
	PreviousKeyVersion   string
	PreviousKeyAlgorithm string
	NewKeyProvider       string
	NewKeyReference      string
	NewKeyVersion        string
	NewKeyAlgorithm      string
	PrincipalType        string
	PrincipalID          string
	TenantActorType      string
	TenantActorID        string
	Reason               string
	OccurredAt           pgtype.Timestamptz
}

func (q *Queries) InsertEvidenceKeyRewrapAudit(ctx context.Context, arg InsertEvidenceKeyRewrapAuditParams) error {
	_, err := q.db.Exec(ctx, insertEvidenceKeyRewrapAudit,
		arg.TenantID,
		arg.EvidenceID,
		arg.AggregateVersion,
		arg.PreviousKeyProvider,
		arg.PreviousKeyReference,
		arg.PreviousKeyVersion,
		arg.PreviousKeyAlgorithm,
		arg.NewKeyProvider,
		arg.NewKeyReference,
		arg.NewKeyVersion,
		arg.NewKeyAlgorithm,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.TenantActorType,
		arg.TenantActorID,
		arg.Reason,
		arg.OccurredAt,
	)
	return err
}

const listEvidenceAssetAudit = `-- name: ListEvidenceAssetAudit :many
SELECT aggregate_version, action, reason, occurred_at
FROM idenqa.evidence_asset_audit
WHERE tenant_id = $1
  AND evidence_id = $2
ORDER BY aggregate_version ASC
LIMIT $3
`

type ListEvidenceAssetAuditParams struct {
	TenantID   string
	EvidenceID string
	PageLimit  int32
}

type ListEvidenceAssetAuditRow struct {
	AggregateVersion int64
	Action           string
	Reason           *string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) ListEvidenceAssetAudit(ctx context.Context, arg ListEvidenceAssetAuditParams) ([]ListEvidenceAssetAuditRow, error) {
	rows, err := q.db.Query(ctx, listEvidenceAssetAudit, arg.TenantID, arg.EvidenceID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEvidenceAssetAuditRow
	for rows.Next() {
		var i ListEvidenceAssetAuditRow
		if err := rows.Scan(
			&i.AggregateVersion,
			&i.Action,
			&i.Reason,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEvidenceAssetForKeyRewrap = `-- name: LockEvidenceAssetForKeyRewrap :one
SELECT id, tenant_id, subject_id, verification_id, requirement_key, evidence_type, artefact, acquisition_method, assurances, registry_schema_version, registry_revision, registry_digest, region, retention_class, content_revision, object_key, object_version, ciphertext_size, ciphertext_checksum, envelope_format_version, content_algorithm, key_purpose, key_provider, key_reference, key_version, key_algorithm, wrapped_key, context_schema_version, context_digest, plaintext_digest, media_type, integrity, state, version, created_at, updated_at, quarantine_reason, quarantined_at FROM idenqa.evidence_assets
WHERE tenant_id = $1 AND id = $2 AND version = $3
FOR UPDATE
`

type LockEvidenceAssetForKeyRewrapParams struct {
	TenantID string
	ID       string
	Version  int64
}

func (q *Queries) LockEvidenceAssetForKeyRewrap(ctx context.Context, arg LockEvidenceAssetForKeyRewrapParams) (IdenqaEvidenceAsset, error) {
	row := q.db.QueryRow(ctx, lockEvidenceAssetForKeyRewrap, arg.TenantID, arg.ID, arg.Version)
	var i IdenqaEvidenceAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.RequirementKey,
		&i.EvidenceType,
		&i.Artefact,
		&i.AcquisitionMethod,
		&i.Assurances,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Region,
		&i.RetentionClass,
		&i.ContentRevision,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.CiphertextSize,
		&i.CiphertextChecksum,
		&i.EnvelopeFormatVersion,
		&i.ContentAlgorithm,
		&i.KeyPurpose,
		&i.KeyProvider,
		&i.KeyReference,
		&i.KeyVersion,
		&i.KeyAlgorithm,
		&i.WrappedKey,
		&i.ContextSchemaVersion,
		&i.ContextDigest,
		&i.PlaintextDigest,
		&i.MediaType,
		&i.Integrity,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuarantineReason,
		&i.QuarantinedAt,
	)
	return i, err
}

const rewrapEvidenceAssetKey = `-- name: RewrapEvidenceAssetKey :one
UPDATE idenqa.evidence_assets
SET key_provider = $4, key_reference = $5, key_version = $6,
    key_algorithm = $7, wrapped_key = $8, version = $9, updated_at = $10
WHERE tenant_id = $1 AND id = $2 AND version = $3
RETURNING id, tenant_id, subject_id, verification_id, requirement_key, evidence_type, artefact, acquisition_method, assurances, registry_schema_version, registry_revision, registry_digest, region, retention_class, content_revision, object_key, object_version, ciphertext_size, ciphertext_checksum, envelope_format_version, content_algorithm, key_purpose, key_provider, key_reference, key_version, key_algorithm, wrapped_key, context_schema_version, context_digest, plaintext_digest, media_type, integrity, state, version, created_at, updated_at, quarantine_reason, quarantined_at
`

type RewrapEvidenceAssetKeyParams struct {
	TenantID     string
	ID           string
	Version      int64
	KeyProvider  string
	KeyReference string
	KeyVersion   string
	KeyAlgorithm string
	WrappedKey   []byte
	Version_2    int64
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) RewrapEvidenceAssetKey(ctx context.Context, arg RewrapEvidenceAssetKeyParams) (IdenqaEvidenceAsset, error) {
	row := q.db.QueryRow(ctx, rewrapEvidenceAssetKey,
		arg.TenantID,
		arg.ID,
		arg.Version,
		arg.KeyProvider,
		arg.KeyReference,
		arg.KeyVersion,
		arg.KeyAlgorithm,
		arg.WrappedKey,
		arg.Version_2,
		arg.UpdatedAt,
	)
	var i IdenqaEvidenceAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.RequirementKey,
		&i.EvidenceType,
		&i.Artefact,
		&i.AcquisitionMethod,
		&i.Assurances,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Region,
		&i.RetentionClass,
		&i.ContentRevision,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.CiphertextSize,
		&i.CiphertextChecksum,
		&i.EnvelopeFormatVersion,
		&i.ContentAlgorithm,
		&i.KeyPurpose,
		&i.KeyProvider,
		&i.KeyReference,
		&i.KeyVersion,
		&i.KeyAlgorithm,
		&i.WrappedKey,
		&i.ContextSchemaVersion,
		&i.ContextDigest,
		&i.PlaintextDigest,
		&i.MediaType,
		&i.Integrity,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuarantineReason,
		&i.QuarantinedAt,
	)
	return i, err
}

const transitionEvidenceAsset = `-- name: TransitionEvidenceAsset :one
UPDATE idenqa.evidence_assets
SET integrity = $4, state = $5, version = $6, updated_at = $7,
    quarantine_reason = $8, quarantined_at = $9
WHERE tenant_id = $1 AND id = $2 AND version = $3 AND state = 'available'
RETURNING id, tenant_id, subject_id, verification_id, requirement_key, evidence_type, artefact, acquisition_method, assurances, registry_schema_version, registry_revision, registry_digest, region, retention_class, content_revision, object_key, object_version, ciphertext_size, ciphertext_checksum, envelope_format_version, content_algorithm, key_purpose, key_provider, key_reference, key_version, key_algorithm, wrapped_key, context_schema_version, context_digest, plaintext_digest, media_type, integrity, state, version, created_at, updated_at, quarantine_reason, quarantined_at
`

type TransitionEvidenceAssetParams struct {
	TenantID         string
	ID               string
	Version          int64
	Integrity        string
	State            string
	Version_2        int64
	UpdatedAt        pgtype.Timestamptz
	QuarantineReason *string
	QuarantinedAt    pgtype.Timestamptz
}

func (q *Queries) TransitionEvidenceAsset(ctx context.Context, arg TransitionEvidenceAssetParams) (IdenqaEvidenceAsset, error) {
	row := q.db.QueryRow(ctx, transitionEvidenceAsset,
		arg.TenantID,
		arg.ID,
		arg.Version,
		arg.Integrity,
		arg.State,
		arg.Version_2,
		arg.UpdatedAt,
		arg.QuarantineReason,
		arg.QuarantinedAt,
	)
	var i IdenqaEvidenceAsset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectID,
		&i.VerificationID,
		&i.RequirementKey,
		&i.EvidenceType,
		&i.Artefact,
		&i.AcquisitionMethod,
		&i.Assurances,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Region,
		&i.RetentionClass,
		&i.ContentRevision,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.CiphertextSize,
		&i.CiphertextChecksum,
		&i.EnvelopeFormatVersion,
		&i.ContentAlgorithm,
		&i.KeyPurpose,
		&i.KeyProvider,
		&i.KeyReference,
		&i.KeyVersion,
		&i.KeyAlgorithm,
		&i.WrappedKey,
		&i.ContextSchemaVersion,
		&i.ContextDigest,
		&i.PlaintextDigest,
		&i.MediaType,
		&i.Integrity,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QuarantineReason,
		&i.QuarantinedAt,
	)
	return i, err
}
