// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyRecord = `-- name: CompleteIdempotencyRecord :one
UPDATE idenqa.idempotency_records
SET state = 'completed', result_status = $6, result = $7, completed_at = $8
WHERE tenant_id = $1 AND principal_id = $2 AND operation = $3 AND
      idempotency_key = $4 AND request_fingerprint = $5 AND state = 'pending'
RETURNING tenant_id, principal_id, operation, idempotency_key, request_fingerprint, state, result_status, result, created_at, completed_at, expires_at, principal_type
`

type CompleteIdempotencyRecordParams struct {
	TenantID           string
	PrincipalID        string
	Operation          string
	IdempotencyKey     string
	RequestFingerprint []byte
	ResultStatus       *int32
	Result             []byte
	CompletedAt        pgtype.Timestamptz
}

func (q *Queries) CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (IdenqaIdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyRecord,
		arg.TenantID,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.ResultStatus,
		arg.Result,
		arg.CompletedAt,
	)
	var i IdenqaIdempotencyRecord
	err := row.Scan(
		&i.TenantID,
		&i.PrincipalID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.State,
		&i.ResultStatus,
		&i.Result,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.PrincipalType,
	)
	return i, err
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :execrows
INSERT INTO idenqa.idempotency_records (
    tenant_id, principal_id, operation, idempotency_key, request_fingerprint,
    state, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, 'pending', $6, $7)
ON CONFLICT (tenant_id, principal_id, operation, idempotency_key) DO NOTHING
`

type CreateIdempotencyRecordParams struct {
	TenantID           string
	PrincipalID        string
	Operation          string
	IdempotencyKey     string
	RequestFingerprint []byte
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, createIdempotencyRecord,
		arg.TenantID,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyRecord = `-- name: DeleteExpiredIdempotencyRecord :exec
DELETE FROM idenqa.idempotency_records
WHERE tenant_id = $1 AND principal_id = $2 AND operation = $3 AND
      idempotency_key = $4 AND expires_at <= $5
`

type DeleteExpiredIdempotencyRecordParams struct {
	TenantID       string
	PrincipalID    string
	Operation      string
	IdempotencyKey string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) DeleteExpiredIdempotencyRecord(ctx context.Context, arg DeleteExpiredIdempotencyRecordParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyRecord,
		arg.TenantID,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.ExpiresAt,
	)
	return err
}

const findIdempotencyRecord = `-- name: FindIdempotencyRecord :one
SELECT tenant_id, principal_id, operation, idempotency_key, request_fingerprint, state, result_status, result, created_at, completed_at, expires_at, principal_type
FROM idenqa.idempotency_records
WHERE tenant_id = $1 AND principal_id = $2 AND operation = $3 AND idempotency_key = $4
`

type FindIdempotencyRecordParams struct {
	TenantID       string
	PrincipalID    string
	Operation      string
	IdempotencyKey string
}

func (q *Queries) FindIdempotencyRecord(ctx context.Context, arg FindIdempotencyRecordParams) (IdenqaIdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, findIdempotencyRecord,
		arg.TenantID,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i IdenqaIdempotencyRecord
	err := row.Scan(
		&i.TenantID,
		&i.PrincipalID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.State,
		&i.ResultStatus,
		&i.Result,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.PrincipalType,
	)
	return i, err
}

const tryIdempotencyLock = `-- name: TryIdempotencyLock :one
SELECT pg_try_advisory_xact_lock(hashtextextended(
    concat_ws(
        E'\x1f',
        $1::text,
        $2::text,
        $3::text,
        $4::text
    ),
    0
))
`

type TryIdempotencyLockParams struct {
	TenantID       string
	PrincipalID    string
	Operation      string
	IdempotencyKey string
}

func (q *Queries) TryIdempotencyLock(ctx context.Context, arg TryIdempotencyLockParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryIdempotencyLock,
		arg.TenantID,
		arg.PrincipalID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
