// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdenqaApiKey struct {
	ID              string
	TenantID        string
	Label           string
	Digest          []byte
	PepperVersion   int32
	RequestedScopes []string
	ResolvedScopes  []string
	Version         int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	RetiredAt       pgtype.Timestamptz
	ReplacesKeyID   *string
}

type IdenqaApiKeyAdminAudit struct {
	Sequence   int64
	TenantID   string
	KeyID      *string
	Action     string
	Actor      string
	Reason     string
	OccurredAt pgtype.Timestamptz
}

type IdenqaAuditCheckpoint struct {
	TenantID        string
	ThroughSequence int64
	ChainHash       string
	KeyID           string
	CreatedAt       pgtype.Timestamptz
	Signature       string
}

type IdenqaAuditHead struct {
	TenantID     string
	LastSequence int64
	LastHash     string
}

type IdenqaAuditKey struct {
	KeyID     string
	PublicKey []byte
	ValidFrom pgtype.Timestamptz
	RetiredAt pgtype.Timestamptz
}

type IdenqaAuditRecord struct {
	TenantID     string
	Sequence     int64
	EventID      string
	EventType    string
	AggregateID  string
	ActorID      string
	OccurredAt   pgtype.Timestamptz
	EventDigest  string
	PreviousHash string
	Hash         string
}

type IdenqaAuthorityAudit struct {
	TenantID         string
	AuthorityID      string
	AggregateVersion int64
	Action           string
	ActorType        string
	ActorID          string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaCaptureProfile struct {
	ID                string
	TenantID          string
	Name              string
	State             string
	Version           int64
	LatestRevision    int32
	DraftRevision     *int32
	PublishedRevision *int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeactivatedAt     pgtype.Timestamptz
}

type IdenqaCaptureProfileAudit struct {
	TenantID         string
	ProfileID        string
	AggregateVersion int64
	Revision         *int32
	Action           string
	ActorKeyID       string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaCaptureProfileRevision struct {
	TenantID              string
	ProfileID             string
	Revision              int32
	State                 string
	SchemaVersion         int32
	RegistrySchemaVersion int32
	RegistryRevision      int32
	RegistryDigest        string
	Document              []byte
	Digest                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PublishedAt           pgtype.Timestamptz
	EndedAt               pgtype.Timestamptz
}

type IdenqaCaptureToken struct {
	ID             string
	TenantID       string
	VerificationID string
	KeyVersion     int32
	IssuedAt       pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type IdenqaEvidenceAsset struct {
	ID                    string
	TenantID              string
	SubjectID             string
	VerificationID        string
	RequirementKey        string
	EvidenceType          string
	Artefact              string
	AcquisitionMethod     string
	Assurances            []string
	RegistrySchemaVersion int32
	RegistryRevision      int32
	RegistryDigest        string
	Region                string
	RetentionClass        string
	ContentRevision       int32
	ObjectKey             string
	ObjectVersion         string
	CiphertextSize        int64
	CiphertextChecksum    string
	EnvelopeFormatVersion int32
	ContentAlgorithm      string
	KeyPurpose            string
	KeyProvider           string
	KeyReference          string
	KeyVersion            string
	KeyAlgorithm          string
	WrappedKey            []byte
	ContextSchemaVersion  int32
	ContextDigest         string
	PlaintextDigest       string
	MediaType             string
	Integrity             string
	State                 string
	Version               int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	QuarantineReason      *string
	QuarantinedAt         pgtype.Timestamptz
}

type IdenqaEvidenceAssetAudit struct {
	TenantID         string
	EvidenceID       string
	AggregateVersion int64
	Action           string
	Reason           *string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaEvidenceGrantAccessAttemptAudit struct {
	Sequence         int64
	TenantID         string
	PresentedGrantID string
	RedemptionID     string
	RunnerIdentity   string
	WorkloadVersion  string
	Decision         string
	DenialReason     *string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaEvidenceGrantRedemption struct {
	ID              string
	TenantID        string
	GrantID         string
	RunnerIdentity  string
	WorkloadVersion string
	ClaimedUse      *int32
	DenialReason    *string
	AttemptedAt     pgtype.Timestamptz
}

type IdenqaEvidenceGrantRedemptionOutcome struct {
	TenantID     string
	RedemptionID string
	GrantID      string
	Outcome      string
	DenialReason *string
	OccurredAt   pgtype.Timestamptz
}

type IdenqaEvidenceKeyRewrapAudit struct {
	TenantID             string
	EvidenceID           string
	AggregateVersion     int64
	PreviousKeyProvider  string
	PreviousKeyReference string
	PreviousKeyVersion   string
	PreviousKeyAlgorithm string
	NewKeyProvider       string
	NewKeyReference      string
	NewKeyVersion        string
	NewKeyAlgorithm      string
	PrincipalType        string
	PrincipalID          string
	TenantActorType      string
	TenantActorID        string
	Reason               string
	OccurredAt           pgtype.Timestamptz
}

type IdenqaEvidenceObjectReconciliation struct {
	TenantID       string
	UploadID       string
	EvidenceID     string
	UploadAttempt  int32
	ObjectKey      string
	ObjectVersion  string
	ObjectSize     int64
	ObjectChecksum string
	State          string
	Version        int64
	Claim          int32
	AvailableAt    pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

type IdenqaEvidenceObjectReconciliationAudit struct {
	TenantID         string
	UploadID         string
	UploadAttempt    int32
	AggregateVersion int64
	Claim            int32
	Action           string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaEvidenceProcessingGrant struct {
	ID                 string
	TenantID           string
	SubjectID          string
	VerificationID     string
	EvidenceID         string
	RequirementKey     string
	AuthorityID        string
	ResponseID         string
	CheckReference     string
	RunnerIdentity     string
	WorkloadVersion    string
	Purpose            string
	Operation          string
	PermittedVariants  []string
	Region             string
	RecipientReference string
	OutputDestination  string
	PolicyReference    string
	MaximumUses        int32
	Uses               int32
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
}

type IdenqaEvidenceProcessingGrantAudit struct {
	TenantID         string
	GrantID          string
	AggregateVersion int32
	Action           string
	PrincipalType    string
	PrincipalID      string
	TenantActorType  string
	TenantActorID    string
	Reason           string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaEvidenceUploadIntent struct {
	ID                         string
	TenantID                   string
	CaptureTokenID             string
	SubjectID                  string
	VerificationID             string
	EvidenceID                 string
	AuthorityID                string
	ResponseID                 string
	ProfileID                  string
	ProfileRevision            int32
	ProfileDigest              string
	RegistrySchemaVersion      int32
	RegistryRevision           int32
	RegistryDigest             string
	RequirementKey             string
	Purpose                    string
	EvidenceType               string
	Artefact                   string
	AcquisitionMethod          string
	Assurances                 []string
	EncryptionPurpose          string
	AllowedMediaTypes          []string
	MaximumBytes               int64
	ExpectedBytes              int64
	ExpectedDigest             string
	MediaType                  string
	Region                     string
	RetentionClass             string
	State                      string
	Version                    int64
	Attempt                    int32
	AttemptTimeoutMilliseconds int64
	LeaseExpiresAt             pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	ExpiresAt                  pgtype.Timestamptz
	AcceptedAt                 pgtype.Timestamptz
	RejectionReason            *string
	FallbackCondition          *string
}

type IdenqaEvidenceUploadIntentAudit struct {
	TenantID         string
	UploadID         string
	AggregateVersion int64
	Attempt          int32
	Action           string
	PrincipalID      string
	Reason           *string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaIdempotencyRecord struct {
	TenantID           string
	PrincipalID        string
	Operation          string
	IdempotencyKey     string
	RequestFingerprint []byte
	State              string
	ResultStatus       *int32
	Result             []byte
	CreatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	PrincipalType      *string
}

type IdenqaNoticeVersion struct {
	ID                    string
	TenantID              string
	SemanticKey           string
	Locale                string
	ControllerDisplayName string
	RecipientDisplayName  string
	Title                 string
	Summary               string
	PurposeCopy           string
	ConsequenceCopy       string
	EffectiveAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	CreatedBy             string
	Digest                string
}

type IdenqaNoticeVersionAudit struct {
	TenantID   string
	NoticeID   string
	Action     string
	ActorKeyID string
	OccurredAt pgtype.Timestamptz
}

type IdenqaOutboxEvent struct {
	ID               string
	TenantID         string
	AggregateType    string
	AggregateID      string
	AggregateVersion int64
	EventType        string
	SchemaVersion    int32
	Payload          []byte
	OccurredAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	PublishedAt      pgtype.Timestamptz
}

type IdenqaPolicy struct {
	TenantID          string
	ID                string
	ActivationVersion int64
	ActiveRevision    *int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type IdenqaPolicyActivation struct {
	TenantID          string
	PolicyID          string
	ActivationVersion int64
	Revision          int64
	PreviousRevision  *int64
	ActorKeyID        string
	ActivatedAt       pgtype.Timestamptz
}

type IdenqaPolicyEvaluation struct {
	TenantID         string
	VerificationID   string
	SnapshotDigest   string
	EvaluationDigest string
	Selected         string
	Outcome          *string
	Assurance        *string
	Canonical        string
}

type IdenqaPolicyRevision struct {
	TenantID        string
	PolicyID        string
	Revision        int64
	SchemaMajor     int32
	SchemaMinor     int32
	Digest          string
	EvaluatorMajor  int32
	EvaluatorMinor  int32
	EvaluatorDigest string
	Canonical       string
	CreatedAt       pgtype.Timestamptz
}

type IdenqaPolicySnapshot struct {
	TenantID          string
	VerificationID    string
	SnapshotDigest    string
	PolicyID          string
	PolicyRevision    int64
	PolicySchemaMajor int32
	PolicySchemaMinor int32
	PolicyDigest      string
	EvaluatorMajor    int32
	EvaluatorMinor    int32
	EvaluatorDigest   string
	AuthorityID       string
	AcknowledgementID string
	Region            string
	EvaluatedAt       pgtype.Timestamptz
	Canonical         string
}

type IdenqaProcessingAuthority struct {
	ID                   string
	TenantID             string
	SubjectID            string
	VerificationID       string
	NoticeID             string
	Category             string
	Purpose              string
	Jurisdiction         string
	PolicyPack           string
	ConsentRequired      bool
	RequirementPurposes  []string
	EvidenceTypes        []string
	RecipientReference   string
	RecipientDisplayName string
	Regions              []string
	RetentionReference   string
	State                string
	Version              int64
	ValidFrom            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            string
	RestrictedAt         pgtype.Timestamptz
	WithdrawnAt          pgtype.Timestamptz
	SupersededAt         pgtype.Timestamptz
}

type IdenqaRealtimeAcknowledgement struct {
	TenantID           string
	VerificationID     string
	CaptureTokenID     string
	AcknowledgedCursor int64
	UpdatedAt          pgtype.Timestamptz
}

type IdenqaRealtimeClientCommand struct {
	CommandID          string
	TenantID           string
	VerificationID     string
	CaptureTokenID     string
	RequestFingerprint []byte
	MessageType        string
	StepState          string
	RequirementKey     string
	Artefact           string
	AcquisitionMethod  string
	ResultCode         *string
	Disposition        string
	RejectionCode      *string
	OccurredAt         pgtype.Timestamptz
	ReceivedAt         pgtype.Timestamptz
}

type IdenqaRealtimeEvent struct {
	EventID        string
	TenantID       string
	VerificationID string
	Cursor         int64
	MessageType    string
	CommandID      *string
	CorrelationID  *string
	CausationID    *string
	Payload        []byte
	OccurredAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type IdenqaRealtimeStream struct {
	TenantID           string
	VerificationID     string
	LatestCursor       int64
	LatestExpiresAt    pgtype.Timestamptz
	RetainedFromCursor int64
	UpdatedAt          pgtype.Timestamptz
}

type IdenqaSubject struct {
	ID             string
	TenantID       string
	VerificationID string
	CreatedAt      pgtype.Timestamptz
}

type IdenqaSubjectResponse struct {
	ID                        string
	TenantID                  string
	AuthorityID               string
	NoticeID                  string
	SubjectID                 string
	VerificationID            string
	CaptureTokenID            string
	Action                    string
	Locale                    string
	RenderedExperienceVersion *string
	RecordedAt                pgtype.Timestamptz
}

type IdenqaTenant struct {
	ID         string
	State      string
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
}

type IdenqaTenantAdminAudit struct {
	Sequence   int64
	TenantID   string
	Action     string
	Actor      string
	Reason     string
	OccurredAt pgtype.Timestamptz
}

type IdenqaVerificationAttempt struct {
	ID                     string
	TenantID               string
	VerificationID         string
	CheckID                string
	AttemptNumber          int32
	Fence                  int64
	RunnerKind             string
	RunnerID               string
	RunnerVersion          string
	PackageDigest          string
	ContractMajor          int32
	ContractMinor          int32
	RequestDigest          string
	ConfigurationDigest    string
	State                  string
	StartedAt              pgtype.Timestamptz
	Deadline               pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	FailureClass           *string
	FailureCode            *string
	RetryDisposition       *string
	RetryAfterMilliseconds *int64
	ResultDigest           *string
}

type IdenqaVerificationAttemptDiagnostic struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	Kind           string
	Code           string
	RecordedAt     pgtype.Timestamptz
}

type IdenqaVerificationCheck struct {
	ID             string
	TenantID       string
	VerificationID string
	Name           string
	State          string
	Outcome        *string
	Version        int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type IdenqaVerificationDecision struct {
	ID               string
	TenantID         string
	VerificationID   string
	SnapshotDigest   string
	EvaluationDigest string
	DecisionDigest   string
	Selected         string
	Outcome          string
	Actor            string
	SupersedesID     *string
	DecidedAt        pgtype.Timestamptz
	Canonical        string
}

type IdenqaVerificationObservation struct {
	ID                  string
	TenantID            string
	VerificationID      string
	CheckID             string
	AttemptID           string
	RunnerKind          string
	RunnerID            string
	RunnerVersion       string
	PackageDigest       string
	ContractMajor       int32
	ContractMinor       int32
	RequestDigest       string
	ConfigurationDigest string
	SignalName          string
	SignalOutcome       string
	ReasonCodes         []string
	RecordedAt          pgtype.Timestamptz
}

type IdenqaVerificationReconciliation struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	Reason         string
	Status         string
	ClaimToken     *string
	LeaseExpiresAt pgtype.Timestamptz
	ClaimCount     int32
	AvailableAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

type IdenqaVerificationResultInbox struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	ResultDigest   string
	ReceivedAt     pgtype.Timestamptz
}

type IdenqaVerificationSession struct {
	ID                    string
	TenantID              string
	State                 string
	Version               int64
	SourceProfileID       string
	SourceProfileRevision int32
	SourceProfileDigest   string
	Requirements          []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	SubjectID             *string
	AuthorityID           *string
	NoticeID              *string
	Region                *string
	PolicyID              *string
	DecisionID            *string
	CaptureCompletedAt    pgtype.Timestamptz
}

type IdenqaVerificationSessionAudit struct {
	TenantID         string
	VerificationID   string
	AggregateVersion int64
	Action           string
	ActorKeyID       string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaWebhookDelivery struct {
	TenantID      string
	ID            string
	EndpointID    string
	EventID       string
	EventType     string
	Body          []byte
	BodyDigest    string
	State         string
	AttemptCount  int32
	MaxAttempts   int32
	NextAttemptAt pgtype.Timestamptz
	DeliveredAt   pgtype.Timestamptz
	ReplayOf      *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type IdenqaWebhookDeliveryAttempt struct {
	TenantID           string
	DeliveryID         string
	AttemptNumber      int32
	SecretVersion      int64
	SignatureTimestamp int64
	StatusCode         int32
	ErrorClass         string
	RetryAfterMs       int64
	CompletedAt        pgtype.Timestamptz
}

type IdenqaWebhookEndpoint struct {
	TenantID                 string
	ID                       string
	Url                      string
	SecretVersion            int64
	PreviousSecretVersion    *int64
	PreviousSecretValidUntil pgtype.Timestamptz
	DisabledAt               pgtype.Timestamptz
	DisabledReason           *string
	Version                  int64
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type IdenqaWebhookSecret struct {
	TenantID   string
	EndpointID string
	Version    int64
	Provider   string
	Reference  string
	KeyVersion string
	Algorithm  string
	Ciphertext []byte
	CreatedAt  pgtype.Timestamptz
}

type IdenqaWebsocketConnectionTicket struct {
	ID             string
	TenantID       string
	VerificationID string
	CaptureTokenID string
	Digest         []byte
	DigestVersion  int32
	ClientKind     string
	ClientIdentity string
	Region         string
	Protocol       string
	IssuedAt       pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RedeemedAt     pgtype.Timestamptz
	ConnectionID   *string
}
