// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdenqaAcceptedCommand struct {
	ID             string
	ProposalID     string
	TenantID       string
	VerificationID *string
	Kind           string
	Args           []byte
	ModelID        string
	ModelVersion   string
	PromptVersion  string
	CreatedAt      pgtype.Timestamptz
	ExecutedAt     pgtype.Timestamptz
	PolicyID       *string
}

type IdenqaApiKey struct {
	ID              string
	TenantID        string
	Label           string
	Digest          []byte
	PepperVersion   int32
	RequestedScopes []string
	ResolvedScopes  []string
	Version         int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	RetiredAt       pgtype.Timestamptz
	ReplacesKeyID   *string
}

type IdenqaApiKeyAdminAudit struct {
	Sequence   int64
	TenantID   string
	KeyID      *string
	Action     string
	Actor      string
	Reason     string
	OccurredAt pgtype.Timestamptz
}

type IdenqaAppeal struct {
	TenantID              string
	ID                    string
	CaseID                string
	ChallengedDecisionID  string
	OriginalReviewers     []byte
	AssignedReviewer      *string
	State                 string
	Outcome               *string
	ReasonCode            *string
	SupersedingDecisionID *string
	Deadline              pgtype.Timestamptz
	Version               int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RequestedBy           *string
}

type IdenqaAssuranceProfile struct {
	TenantID   string
	Name       string
	Revision   int64
	Digest     string
	Canonical  string
	ActorKeyID string
	CreatedAt  pgtype.Timestamptz
}

type IdenqaAuditCheckpoint struct {
	TenantID        string
	ThroughSequence int64
	ChainHash       string
	KeyID           string
	CreatedAt       pgtype.Timestamptz
	Signature       string
}

type IdenqaAuditHead struct {
	TenantID     string
	LastSequence int64
	LastHash     string
}

type IdenqaAuditKey struct {
	KeyID     string
	PublicKey []byte
	ValidFrom pgtype.Timestamptz
	RetiredAt pgtype.Timestamptz
}

type IdenqaAuditRecord struct {
	TenantID     string
	Sequence     int64
	EventID      string
	EventType    string
	AggregateID  string
	ActorID      string
	OccurredAt   pgtype.Timestamptz
	EventDigest  string
	PreviousHash string
	Hash         string
}

type IdenqaAuthorityAudit struct {
	TenantID         string
	AuthorityID      string
	AggregateVersion int64
	Action           string
	ActorType        string
	ActorID          string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaBreakGlassRequest struct {
	TenantID          string
	ID                string
	Requester         string
	Reason            string
	Permissions       []byte
	DurationSeconds   int64
	State             string
	Version           int64
	RequestedAt       pgtype.Timestamptz
	ApprovalExpiresAt pgtype.Timestamptz
	ApprovedAt        pgtype.Timestamptz
	ApprovedBy        *string
	UsableUntil       pgtype.Timestamptz
	DeniedAt          pgtype.Timestamptz
	DeniedBy          *string
	RevokedAt         pgtype.Timestamptz
	RevokedBy         *string
	RevocationReason  *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type IdenqaBreakGlassUse struct {
	TenantID   string
	RequestID  string
	Sequence   int64
	Permission string
	Target     string
	Actor      string
	UsedAt     pgtype.Timestamptz
}

type IdenqaCaptureProfile struct {
	ID                string
	TenantID          string
	Name              string
	State             string
	Version           int64
	LatestRevision    int32
	DraftRevision     *int32
	PublishedRevision *int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeactivatedAt     pgtype.Timestamptz
}

type IdenqaCaptureProfileAudit struct {
	TenantID         string
	ProfileID        string
	AggregateVersion int64
	Revision         *int32
	Action           string
	ActorKeyID       string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaCaptureProfileRevision struct {
	TenantID              string
	ProfileID             string
	Revision              int32
	State                 string
	SchemaVersion         int32
	RegistrySchemaVersion int32
	RegistryRevision      int32
	RegistryDigest        string
	Document              []byte
	Digest                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PublishedAt           pgtype.Timestamptz
	EndedAt               pgtype.Timestamptz
}

type IdenqaCaptureRecovery struct {
	TenantID       string
	VerificationID string
	OldTokenID     string
	NewTokenID     string
	RecordedAt     pgtype.Timestamptz
}

type IdenqaCaptureRecoveryUpload struct {
	TenantID    string
	NewTokenID  string
	UploadID    string
	Disposition string
}

type IdenqaCaptureToken struct {
	ID                   string
	TenantID             string
	VerificationID       string
	KeyVersion           int32
	IssuedAt             pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
	NativeApplicationID  *string
	NativeProofKeyDigest *string
	NativeBoundAt        pgtype.Timestamptz
}

type IdenqaDeletionRequest struct {
	TenantID               string
	ID                     string
	AggregateID            string
	Region                 string
	State                  string
	BackupExpiresAt        pgtype.Timestamptz
	FailureClass           *string
	Version                int64
	RequestedAt            pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	BackupRetentionSeconds int64
}

type IdenqaDeletionTarget struct {
	TenantID         string
	DeletionID       string
	Kind             string
	Reference        string
	Region           string
	Attempts         int32
	DeletedAt        pgtype.Timestamptz
	LastFailureClass *string
}

type IdenqaDeletionTombstone struct {
	TenantID    string
	DeletionID  string
	AggregateID string
	Region      string
	TargetCount int32
	ProofDigest string
	CompletedAt pgtype.Timestamptz
	RetainUntil pgtype.Timestamptz
}

type IdenqaEvidenceAsset struct {
	ID                    string
	TenantID              string
	SubjectID             string
	VerificationID        string
	RequirementKey        string
	EvidenceType          string
	Artefact              string
	AcquisitionMethod     string
	Assurances            []string
	RegistrySchemaVersion int32
	RegistryRevision      int32
	RegistryDigest        string
	Region                string
	RetentionClass        string
	ContentRevision       int32
	ObjectKey             string
	ObjectVersion         string
	CiphertextSize        int64
	CiphertextChecksum    string
	EnvelopeFormatVersion int32
	ContentAlgorithm      string
	KeyPurpose            string
	KeyProvider           string
	KeyReference          string
	KeyVersion            string
	KeyAlgorithm          string
	WrappedKey            []byte
	ContextSchemaVersion  int32
	ContextDigest         string
	PlaintextDigest       string
	MediaType             string
	Integrity             string
	State                 string
	Version               int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	QuarantineReason      *string
	QuarantinedAt         pgtype.Timestamptz
}

type IdenqaEvidenceAssetAudit struct {
	TenantID         string
	EvidenceID       string
	AggregateVersion int64
	Action           string
	Reason           *string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaEvidenceGrantAccessAttemptAudit struct {
	Sequence         int64
	TenantID         string
	PresentedGrantID string
	RedemptionID     string
	RunnerIdentity   string
	WorkloadVersion  string
	Decision         string
	DenialReason     *string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaEvidenceGrantRedemption struct {
	ID              string
	TenantID        string
	GrantID         string
	RunnerIdentity  string
	WorkloadVersion string
	ClaimedUse      *int32
	DenialReason    *string
	AttemptedAt     pgtype.Timestamptz
}

type IdenqaEvidenceGrantRedemptionOutcome struct {
	TenantID     string
	RedemptionID string
	GrantID      string
	Outcome      string
	DenialReason *string
	OccurredAt   pgtype.Timestamptz
}

type IdenqaEvidenceKeyRewrapAudit struct {
	TenantID             string
	EvidenceID           string
	AggregateVersion     int64
	PreviousKeyProvider  string
	PreviousKeyReference string
	PreviousKeyVersion   string
	PreviousKeyAlgorithm string
	NewKeyProvider       string
	NewKeyReference      string
	NewKeyVersion        string
	NewKeyAlgorithm      string
	PrincipalType        string
	PrincipalID          string
	TenantActorType      string
	TenantActorID        string
	Reason               string
	OccurredAt           pgtype.Timestamptz
}

type IdenqaEvidenceObjectReconciliation struct {
	TenantID       string
	UploadID       string
	EvidenceID     string
	UploadAttempt  int32
	ObjectKey      string
	ObjectVersion  string
	ObjectSize     int64
	ObjectChecksum string
	State          string
	Version        int64
	Claim          int32
	AvailableAt    pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

type IdenqaEvidenceObjectReconciliationAudit struct {
	TenantID         string
	UploadID         string
	UploadAttempt    int32
	AggregateVersion int64
	Claim            int32
	Action           string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaEvidenceProcessingGrant struct {
	ID                 string
	TenantID           string
	SubjectID          string
	VerificationID     string
	EvidenceID         string
	RequirementKey     string
	AuthorityID        string
	ResponseID         string
	CheckReference     string
	RunnerIdentity     string
	WorkloadVersion    string
	Purpose            string
	Operation          string
	PermittedVariants  []string
	Region             string
	RecipientReference string
	OutputDestination  string
	PolicyReference    string
	MaximumUses        int32
	Uses               int32
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
}

type IdenqaEvidenceProcessingGrantAudit struct {
	TenantID         string
	GrantID          string
	AggregateVersion int32
	Action           string
	PrincipalType    string
	PrincipalID      string
	TenantActorType  string
	TenantActorID    string
	Reason           string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaEvidenceUploadIntent struct {
	ID                         string
	TenantID                   string
	CaptureTokenID             string
	SubjectID                  string
	VerificationID             string
	EvidenceID                 string
	AuthorityID                string
	ResponseID                 string
	ProfileID                  string
	ProfileRevision            int32
	ProfileDigest              string
	RegistrySchemaVersion      int32
	RegistryRevision           int32
	RegistryDigest             string
	RequirementKey             string
	Purpose                    string
	EvidenceType               string
	Artefact                   string
	AcquisitionMethod          string
	Assurances                 []string
	EncryptionPurpose          string
	AllowedMediaTypes          []string
	MaximumBytes               int64
	ExpectedBytes              int64
	ExpectedDigest             string
	MediaType                  string
	Region                     string
	RetentionClass             string
	State                      string
	Version                    int64
	Attempt                    int32
	AttemptTimeoutMilliseconds int64
	LeaseExpiresAt             pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	ExpiresAt                  pgtype.Timestamptz
	AcceptedAt                 pgtype.Timestamptz
	RejectionReason            *string
	FallbackCondition          *string
}

type IdenqaEvidenceUploadIntentAudit struct {
	TenantID         string
	UploadID         string
	AggregateVersion int64
	Attempt          int32
	Action           string
	PrincipalID      string
	Reason           *string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaExperience struct {
	TenantID         string
	ID               string
	State            string
	Revision         int64
	LatestVersion    int32
	ApprovedVersion  int32
	PublishedVersion int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type IdenqaExperienceEvent struct {
	TenantID      string
	ExperienceID  string
	Sequence      int64
	Operation     string
	FromState     *string
	ToState       string
	Version       int32
	TargetVersion int32
	ActorID       string
	Reason        *string
	Digest        string
	OccurredAt    pgtype.Timestamptz
}

type IdenqaExperienceRevision struct {
	TenantID     string
	ExperienceID string
	Version      int32
	State        string
	Document     []byte
	Digest       string
	KeyID        string
	Signature    string
	ActorID      string
	CreatedAt    pgtype.Timestamptz
}

type IdenqaExperienceSessionPin struct {
	TenantID             string
	VerificationID       string
	ExperienceID         string
	Version              int32
	Locale               string
	TenantCopyVersion    string
	MandatoryCopyVersion string
	Source               string
	Digest               string
	KeyID                string
	PinnedAt             pgtype.Timestamptz
}

type IdenqaExperienceTargeting struct {
	TenantID       string
	ExperienceID   string
	Version        int32
	RuleIndex      int32
	Workflow       *string
	Countries      []byte
	ApplicationIds []byte
	Origins        []byte
	SdkVersionMin  *string
	SdkVersionMax  *string
	Specificity    int32
}

type IdenqaFraudConfiguration struct {
	TenantID      string
	Version       int64
	Configuration []byte
	Digest        string
	ActorKeyID    string
	RecordedAt    pgtype.Timestamptz
}

type IdenqaFraudKey struct {
	TenantID   string
	Region     string
	KeyVersion int64
	WrappedKey []byte
}

type IdenqaFraudLink struct {
	TenantID             string
	VerificationID       string
	EvidenceID           string
	Kind                 string
	Namespace            string
	Token                string
	Region               string
	SourceReference      string
	SourceClass          string
	ActorKeyID           *string
	ConfigurationVersion int64
	ObservedAt           pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
}

type IdenqaFraudProposal struct {
	TenantID      string
	ReceiptDigest string
	Digest        string
	Proposal      []byte
	ActorKeyID    string
	RecordedAt    pgtype.Timestamptz
}

type IdenqaFraudReceipt struct {
	TenantID             string
	VerificationID       string
	Digest               string
	ConfigurationVersion int64
	Receipt              []byte
	RecordedAt           pgtype.Timestamptz
}

type IdenqaGenerativeModelRegistry struct {
	TenantID  string
	ModelID   string
	Version   int64
	Digest    string
	CreatedAt pgtype.Timestamptz
	ActorID   string
}

type IdenqaHmacKey struct {
	TenantID    string
	Domain      string
	Version     int64
	ID          string
	State       string
	WrappedKey  []byte
	CreatedAt   pgtype.Timestamptz
	RetiredAt   pgtype.Timestamptz
	RewrappedAt pgtype.Timestamptz
}

type IdenqaHmacKeyDomain struct {
	TenantID      string
	Domain        string
	Generation    int64
	ActiveVersion *int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type IdenqaIdempotencyRecord struct {
	TenantID           string
	PrincipalID        string
	Operation          string
	IdempotencyKey     string
	RequestFingerprint []byte
	State              string
	ResultStatus       *int32
	Result             []byte
	CreatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	PrincipalType      *string
}

type IdenqaIdentityConfiguration struct {
	TenantID      string
	Region        string
	Version       int64
	Configuration []byte
	Digest        string
	ActorKeyID    string
	RecordedAt    pgtype.Timestamptz
}

type IdenqaIdentityCurrent struct {
	TenantID  string
	SubjectID string
	Kind      string
	Name      string
	SeriesID  string
	RecordID  string
}

type IdenqaIdentityIdentifierToken struct {
	TenantID   string
	SubjectID  string
	RecordID   string
	Region     string
	Namespace  string
	Issuer     string
	KeyVersion int64
	Token      string
}

type IdenqaIdentityKey struct {
	TenantID   string
	Region     string
	Version    int64
	WrappedKey []byte
}

type IdenqaIdentityReceipt struct {
	TenantID       string
	VerificationID string
	SubjectID      *string
	Digest         string
	Receipt        []byte
	RecordedAt     pgtype.Timestamptz
}

type IdenqaIdentityRecord struct {
	TenantID       string
	ID             string
	SubjectID      string
	VerificationID string
	Kind           string
	Name           string
	Sequence       int64
	SeriesID       string
	Supersedes     *string
	Metadata       []byte
	RecordedAt     pgtype.Timestamptz
	RetainUntil    pgtype.Timestamptz
}

type IdenqaIdentityRecordEdge struct {
	TenantID  string
	SubjectID string
	RecordID  string
	SourceID  string
}

type IdenqaIdentityRecordEvidence struct {
	TenantID       string
	SubjectID      string
	VerificationID string
	RecordID       string
	EvidenceID     string
}

type IdenqaIdentityRecordValue struct {
	TenantID   string
	RecordID   string
	SubjectID  string
	Ciphertext []byte
}

type IdenqaIdentitySubject struct {
	TenantID       string
	ID             string
	Region         string
	State          string
	Version        int64
	ExternalCipher []byte
	ExternalToken  *string
	WrappedKey     []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletionID     *string
	ErasedAt       pgtype.Timestamptz
}

type IdenqaIdentitySubjectVerification struct {
	TenantID       string
	SubjectID      string
	VerificationID string
	ActorKeyID     string
	LinkedAt       pgtype.Timestamptz
}

type IdenqaImpactAssessment struct {
	ID         string
	TenantID   string
	Kind       string
	Assessment string
	RiskLevel  string
	CreatedAt  pgtype.Timestamptz
	ActorID    string
}

type IdenqaKeyDestructionSchedule struct {
	ID                 string
	VerificationID     string
	Provider           string
	Reference          string
	Version            string
	Algorithm          string
	Mode               string
	ProviderDeletionAt pgtype.Timestamptz
	Actor              string
	Reason             string
	CreatedAt          pgtype.Timestamptz
}

type IdenqaKeyDestructionVerification struct {
	ID         string
	Provider   string
	Reference  string
	Version    string
	Algorithm  string
	State      string
	Counts     []byte
	Total      int64
	Verifier   string
	Reason     string
	Digest     string
	VerifiedAt pgtype.Timestamptz
}

type IdenqaKeyRecoveryCeremony struct {
	ID              string
	Kind            string
	Class           string
	TenantID        *string
	TargetProvider  string
	TargetReference string
	TargetVersion   string
	TargetAlgorithm string
	State           string
	Version         int64
	StartedBy       string
	StartedAt       pgtype.Timestamptz
	ApproveBy       pgtype.Timestamptz
	ApprovedBy      *string
	ApprovedAt      pgtype.Timestamptz
	UsableUntil     pgtype.Timestamptz
	CompletedBy     *string
	CompletedAt     pgtype.Timestamptz
	AbortedBy       *string
	AbortedAt       pgtype.Timestamptz
	AbortReason     *string
	Receipt         []byte
	Reason          string
	UpdatedAt       pgtype.Timestamptz
}

type IdenqaKeyRewrapAudit struct {
	Class        string
	Generation   int64
	Sequence     int64
	Epoch        []byte
	CursorTenant string
	CursorObject string
	NextTenant   string
	NextObject   string
	Processed    int32
	Rewrapped    int32
	Skipped      int32
	Failed       int32
	Status       string
	ErrorClass   *string
	OccurredAt   pgtype.Timestamptz
}

type IdenqaKeyRewrapState struct {
	Class               string
	EpochKey            string
	Epoch               []byte
	Generation          int64
	Status              string
	CursorTenant        string
	CursorObject        string
	Processed           int64
	Rewrapped           int64
	Skipped             int64
	Failed              int64
	ConsecutiveFailures int32
	LastError           *string
	NextAttemptAt       pgtype.Timestamptz
	StartedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type IdenqaLegalHold struct {
	TenantID    string
	ID          string
	AggregateID string
	Authority   string
	Reason      string
	StartsAt    pgtype.Timestamptz
	ReviewAt    pgtype.Timestamptz
	ReleasedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type IdenqaModelDispatch struct {
	TenantID      string
	AttemptID     string
	RequestDigest string
	ClaimedAt     pgtype.Timestamptz
	ResultBody    []byte
}

type IdenqaModelRegistry struct {
	TenantID string
	Name     string
	Version  int64
	State    []byte
}

type IdenqaModelRegistryHistory struct {
	TenantID   string
	Name       string
	Version    int64
	ActorKeyID string
	Receipt    []byte
}

type IdenqaModelRegistryRevision struct {
	TenantID string
	Name     string
	Kind     string
	Revision int64
	Digest   string
	Document []byte
}

type IdenqaModelRequest struct {
	TenantID          string
	AttemptID         string
	VerificationID    string
	CheckID           string
	RequestDigest     string
	RequestBody       []byte
	RegistryName      *string
	RegistryVersion   *int64
	RegistrySelection []byte
}

type IdenqaNoticeVersion struct {
	ID                    string
	TenantID              string
	SemanticKey           string
	Locale                string
	ControllerDisplayName string
	RecipientDisplayName  string
	Title                 string
	Summary               string
	PurposeCopy           string
	ConsequenceCopy       string
	EffectiveAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	CreatedBy             string
	Digest                string
}

type IdenqaNoticeVersionAudit struct {
	TenantID   string
	NoticeID   string
	Action     string
	ActorKeyID string
	OccurredAt pgtype.Timestamptz
}

type IdenqaOutboxEvent struct {
	ID               string
	TenantID         string
	AggregateType    string
	AggregateID      string
	AggregateVersion int64
	EventType        string
	SchemaVersion    int32
	Payload          []byte
	OccurredAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	PublishedAt      pgtype.Timestamptz
}

type IdenqaOutcomeToken struct {
	ID             string
	TenantID       string
	VerificationID string
	KeyVersion     int32
	IssuedAt       pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

type IdenqaPackReleaseHistory struct {
	Country           string
	Revision          int64
	TransitionVersion int64
	Operation         string
	PreviousState     string
	State             string
	PackDigest        string
	Reason            string
	Actor             string
	RecordedAt        pgtype.Timestamptz
}

type IdenqaPackReleaseState struct {
	Country           string
	Revision          int64
	State             string
	Digest            string
	TransitionVersion int64
	UpdatedAt         pgtype.Timestamptz
}

type IdenqaPolicy struct {
	TenantID          string
	ID                string
	ActivationVersion int64
	ActiveRevision    *int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type IdenqaPolicyActivation struct {
	TenantID          string
	PolicyID          string
	ActivationVersion int64
	Revision          int64
	PreviousRevision  *int64
	ActorKeyID        string
	ActivatedAt       pgtype.Timestamptz
}

type IdenqaPolicyAssuranceAssignment struct {
	TenantID        string
	PolicyID        string
	Version         int64
	ProfileName     *string
	ProfileRevision *int64
	ProfileDigest   *string
}

type IdenqaPolicyEvaluation struct {
	TenantID         string
	VerificationID   string
	SnapshotDigest   string
	EvaluationDigest string
	Selected         string
	Outcome          *string
	Assurance        *string
	Canonical        string
}

type IdenqaPolicyRevision struct {
	TenantID        string
	PolicyID        string
	Revision        int64
	SchemaMajor     int32
	SchemaMinor     int32
	Digest          string
	EvaluatorMajor  int32
	EvaluatorMinor  int32
	EvaluatorDigest string
	Canonical       string
	CreatedAt       pgtype.Timestamptz
}

type IdenqaPolicyRoutingReceipt struct {
	TenantID         string
	RequestID        string
	VerificationID   string
	SnapshotDigest   string
	EvaluationDigest string
	RequestedAt      pgtype.Timestamptz
	LifecycleEventID string
}

type IdenqaPolicySnapshot struct {
	TenantID          string
	VerificationID    string
	SnapshotDigest    string
	PolicyID          string
	PolicyRevision    int64
	PolicySchemaMajor int32
	PolicySchemaMinor int32
	PolicyDigest      string
	EvaluatorMajor    int32
	EvaluatorMinor    int32
	EvaluatorDigest   string
	AuthorityID       string
	AcknowledgementID string
	Region            string
	EvaluatedAt       pgtype.Timestamptz
	Canonical         string
}

type IdenqaPrivacyDisclosure struct {
	TenantID    string
	ID          string
	RequestID   string
	Recipient   string
	Purpose     string
	DataClass   string
	LegalBasis  string
	Region      string
	Reference   string
	DisclosedAt pgtype.Timestamptz
	Version     int64
}

type IdenqaPrivacyRequest struct {
	TenantID        string
	ID              string
	Type            string
	State           string
	Channel         string
	SubjectID       *string
	VerificationID  *string
	Region          string
	Payload         []byte
	ReasonCode      *string
	FailureClass    *string
	EffectKind      *string
	EffectReference *string
	EffectDigest    *string
	ExpiresAt       pgtype.Timestamptz
	RequestedAt     pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int64
}

type IdenqaPrivacyRequestDecision struct {
	TenantID   string
	RequestID  string
	ID         string
	Outcome    string
	ReasonCode string
	ActorID    string
	DecidedAt  pgtype.Timestamptz
	Version    int64
}

type IdenqaPrivacyRequestEvent struct {
	TenantID    string
	RequestID   string
	Sequence    int64
	EventType   string
	FromState   string
	ToState     string
	ReasonCode  *string
	ActorDigest *string
	Detail      *string
	Digest      string
	OccurredAt  pgtype.Timestamptz
}

type IdenqaPrivacyRestriction struct {
	TenantID       string
	ID             string
	RequestID      string
	SubjectID      string
	Scope          string
	Purpose        *string
	ReasonCode     string
	Region         string
	State          string
	StartsAt       pgtype.Timestamptz
	LiftedAt       pgtype.Timestamptz
	LiftReasonCode *string
	Version        int64
}

type IdenqaProcessingAuthority struct {
	ID                   string
	TenantID             string
	SubjectID            string
	VerificationID       string
	NoticeID             string
	Category             string
	Purpose              string
	Jurisdiction         string
	PolicyPack           string
	ConsentRequired      bool
	RequirementPurposes  []string
	EvidenceTypes        []string
	RecipientReference   string
	RecipientDisplayName string
	Regions              []string
	RetentionReference   string
	State                string
	Version              int64
	ValidFrom            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CreatedBy            string
	RestrictedAt         pgtype.Timestamptz
	WithdrawnAt          pgtype.Timestamptz
	SupersededAt         pgtype.Timestamptz
}

type IdenqaProcessorInventory struct {
	TenantID          string
	ID                string
	Name              string
	Role              string
	Purpose           string
	DataClasses       []byte
	Regions           []byte
	TransferMechanism string
	Version           int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type IdenqaProcessorInventoryRevision struct {
	TenantID          string
	ID                string
	Version           int64
	Name              string
	Role              string
	Purpose           string
	DataClasses       []byte
	Regions           []byte
	TransferMechanism string
	RecordedAt        pgtype.Timestamptz
}

type IdenqaPromptRegistry struct {
	TenantID  string
	PromptID  string
	Version   int64
	Content   string
	Digest    string
	ModelID   string
	CreatedAt pgtype.Timestamptz
	ActorID   string
	Sensitive bool
}

type IdenqaProposal struct {
	ID             string
	TenantID       string
	VerificationID *string
	Mode           string
	Status         string
	Actions        []byte
	EvidenceRefs   []byte
	SignalRefs     []byte
	ModelID        string
	ModelVersion   string
	PromptVersion  string
	ContextDigest  string
	ExpiresAt      pgtype.Timestamptz
	Supersedes     *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int64
	ActorID        string
	Reason         *string
	PolicyID       *string
}

type IdenqaProposalModeConfig struct {
	TenantID         string
	Workflow         string
	Mode             string
	AllowListVersion string
	AllowedKinds     []byte
	CostDailyLimit   int32
	PromptID         *string
	Version          int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type IdenqaProviderAsyncOperation struct {
	TenantID       string
	AttemptID      string
	RequestDigest  string
	ProviderJobID  *string
	Fence          int64
	LeaseExpiresAt pgtype.Timestamptz
	NextPollAt     pgtype.Timestamptz
}

type IdenqaProviderCallbackReceipt struct {
	TenantID            string
	AttemptID           string
	VerificationID      string
	CheckID             string
	ProviderJobID       *string
	ProviderReplayID    string
	ConfigurationDigest string
	ProgressDigest      string
	ResultDigest        *string
	ProgressBody        []byte
	ReceivedAt          pgtype.Timestamptz
}

type IdenqaProviderDispatch struct {
	TenantID      string
	AttemptID     string
	RequestDigest string
	ClaimedAt     pgtype.Timestamptz
	ResultBody    []byte
}

type IdenqaProviderDispatchAdmission struct {
	TenantID    string
	LimitKey    string
	WindowStart pgtype.Timestamptz
	Admitted    int64
}

type IdenqaProviderDispatchLease struct {
	TenantID   string
	LimitKey   string
	LeaseID    string
	AcquiredAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type IdenqaProviderHealthSnapshot struct {
	TenantID                  string
	AdapterID                 string
	ProviderID                string
	RegistrationID            *string
	Region                    string
	State                     string
	ReasonCode                string
	BreakerState              string
	BreakerSince              pgtype.Timestamptz
	WindowSeconds             int32
	CompletedDispatches       int64
	FailedDispatches          int64
	FailureRatio              float64
	FailureClasses            []byte
	AsyncUnresolvedDispatches int64
	AsyncExpiredDispatches    int64
	CallbacksAdopted          int64
	ObservedAt                pgtype.Timestamptz
	Version                   int64
}

type IdenqaProviderRegistration struct {
	TenantID          string
	ID                string
	AdapterID         string
	Region            string
	Configuration     []byte
	Inputs            []byte
	SelfieRequirement *string
	Restrictions      []byte
	Enabled           bool
	Version           int64
	ActorKeyID        string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type IdenqaProviderRegistrationHistory struct {
	TenantID       string
	RegistrationID string
	Version        int64
	ActorKeyID     string
	Operation      string
	Reason         string
	Receipt        []byte
}

type IdenqaProviderRequest struct {
	TenantID            string
	AttemptID           string
	VerificationID      string
	CheckID             string
	RequestDigest       string
	RequestBody         []byte
	CallbackTokenDigest *string
}

type IdenqaRealtimeAcknowledgement struct {
	TenantID           string
	VerificationID     string
	CaptureTokenID     string
	AcknowledgedCursor int64
	UpdatedAt          pgtype.Timestamptz
}

type IdenqaRealtimeClientCommand struct {
	CommandID          string
	TenantID           string
	VerificationID     string
	CaptureTokenID     string
	RequestFingerprint []byte
	MessageType        string
	StepState          string
	RequirementKey     string
	Artefact           string
	AcquisitionMethod  string
	ResultCode         *string
	Disposition        string
	RejectionCode      *string
	OccurredAt         pgtype.Timestamptz
	ReceivedAt         pgtype.Timestamptz
}

type IdenqaRealtimeEvent struct {
	EventID        string
	TenantID       string
	VerificationID string
	Cursor         int64
	MessageType    string
	CommandID      *string
	CorrelationID  *string
	CausationID    *string
	Payload        []byte
	OccurredAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type IdenqaRealtimeStream struct {
	TenantID           string
	VerificationID     string
	LatestCursor       int64
	LatestExpiresAt    pgtype.Timestamptz
	RetainedFromCursor int64
	UpdatedAt          pgtype.Timestamptz
}

type IdenqaRetentionBinding struct {
	TenantID         string
	AggregateID      string
	DataClass        string
	Region           string
	RetentionSeconds int64
	ExpiresAt        pgtype.Timestamptz
	PolicyDigest     string
	CreatedAt        pgtype.Timestamptz
}

type IdenqaReviewAdministrationHistory struct {
	TenantID      string
	Kind          string
	Reference     string
	Version       int64
	ActorKeyID    string
	Configuration []byte
	RecordedAt    pgtype.Timestamptz
}

type IdenqaReviewAppealHistory struct {
	TenantID   string
	AppealID   string
	Version    int64
	Record     []byte
	RecordedAt pgtype.Timestamptz
}

type IdenqaReviewArbitration struct {
	TenantID    string
	CaseID      string
	CaseVersion int64
	ReviewerID  string
	ActorKeyID  string
	Resolution  string
	ReasonCode  string
	RecordedAt  pgtype.Timestamptz
}

type IdenqaReviewCase struct {
	TenantID              string
	ID                    string
	VerificationID        string
	ChallengedDecisionID  *string
	SupersedingDecisionID *string
	Region                string
	RequiredCertification string
	Oversight             string
	State                 string
	AssignedReviewer      *string
	Version               int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	RoutingRequestID      *string
	PermittedFindings     []byte
}

type IdenqaReviewCaseOperation struct {
	TenantID  string
	CaseID    string
	Version   int64
	Priority  int32
	DueAt     pgtype.Timestamptz
	Language  string
	Reason    string
	Assurance string
	Risk      string
	Sampled   bool
	UpdatedAt pgtype.Timestamptz
}

type IdenqaReviewCaseSetting struct {
	TenantID      string
	CaseID        string
	Configuration []byte
	RecordedAt    pgtype.Timestamptz
}

type IdenqaReviewCorrectionEvaluation struct {
	TenantID         string
	CaseID           string
	CaseVersion      int64
	SnapshotDigest   string
	EvaluationDigest string
	DecisionID       *string
	ActorKeyID       string
	ReviewerID       string
	RecordedAt       pgtype.Timestamptz
}

type IdenqaReviewCorrectionIntake struct {
	TenantID   string
	DecisionID string
	CaseID     string
	RecordedAt pgtype.Timestamptz
}

type IdenqaReviewEvaluation struct {
	TenantID         string
	CaseID           string
	CaseVersion      int64
	VerificationID   string
	SnapshotDigest   string
	EvaluationDigest string
	CaseDigest       string
}

type IdenqaReviewEvaluationRequest struct {
	TenantID    string
	CaseID      string
	CaseVersion int64
	CreatedAt   pgtype.Timestamptz
}

type IdenqaReviewEvidenceAccess struct {
	TenantID     string
	GrantID      string
	RedemptionID string
	CaseID       string
	CaseVersion  int64
	EvidenceID   string
	ReviewerID   string
	Redactions   []byte
	RecordedAt   pgtype.Timestamptz
}

type IdenqaReviewFinding struct {
	TenantID         string
	CaseID           string
	ID               string
	ReviewerID       string
	Resolution       string
	ReasonCode       string
	EvidenceGrantIds []byte
	RecordedAt       pgtype.Timestamptz
}

type IdenqaReviewOperatorAssignment struct {
	TenantID   string
	ApiKeyID   string
	OperatorID string
	Version    int64
	Assignment []byte
	Revoked    bool
	UpdatedAt  pgtype.Timestamptz
}

type IdenqaReviewPolicySetting struct {
	TenantID       string
	PolicyID       string
	PolicyRevision int64
	PolicyDigest   string
	Version        int64
	Configuration  []byte
	UpdatedAt      pgtype.Timestamptz
}

type IdenqaReviewRecapture struct {
	TenantID             string
	CaseID               string
	CaseVersion          int64
	ParentVerificationID string
	ChildVerificationID  string
	CaptureTokenID       string
	PolicySnapshotDigest string
	CreatedAt            pgtype.Timestamptz
}

type IdenqaReviewRecaptureAcknowledgement struct {
	TenantID            string
	CaseID              string
	CaseVersion         int64
	ChildVerificationID string
	DecisionID          string
	ActorKeyID          string
	ReviewerID          string
	RecordedAt          pgtype.Timestamptz
}

type IdenqaReviewRecaptureEvaluationRequest struct {
	TenantID      string
	CaseID        string
	SourceVersion int64
	TargetVersion int64
	DecisionID    string
	ActorKeyID    string
	ReviewerID    string
	RecordedAt    pgtype.Timestamptz
}

type IdenqaSubject struct {
	ID             string
	TenantID       string
	VerificationID string
	CreatedAt      pgtype.Timestamptz
}

type IdenqaSubjectResponse struct {
	ID                        string
	TenantID                  string
	AuthorityID               string
	NoticeID                  string
	SubjectID                 string
	VerificationID            string
	CaptureTokenID            string
	Action                    string
	Locale                    string
	RenderedExperienceVersion *string
	RecordedAt                pgtype.Timestamptz
}

type IdenqaSupportGrant struct {
	TenantID         string
	ID               string
	Grantee          string
	Patterns         []byte
	Permissions      []byte
	Reason           string
	GrantedBy        string
	State            string
	Version          int64
	StartsAt         pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	RevokedBy        *string
	RevocationReason *string
}

type IdenqaTenant struct {
	ID         string
	State      string
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
}

type IdenqaTenantAdminAudit struct {
	Sequence   int64
	TenantID   string
	Action     string
	Actor      string
	Reason     string
	OccurredAt pgtype.Timestamptz
}

type IdenqaVerificationAssurance struct {
	TenantID        string
	VerificationID  string
	ProfileName     *string
	ProfileRevision *int64
	ProfileDigest   *string
}

type IdenqaVerificationAttempt struct {
	ID                     string
	TenantID               string
	VerificationID         string
	CheckID                string
	AttemptNumber          int32
	Fence                  int64
	RunnerKind             string
	RunnerID               string
	RunnerVersion          string
	PackageDigest          string
	ContractMajor          int32
	ContractMinor          int32
	RequestDigest          string
	ConfigurationDigest    string
	State                  string
	StartedAt              pgtype.Timestamptz
	Deadline               pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	FailureClass           *string
	FailureCode            *string
	RetryDisposition       *string
	RetryAfterMilliseconds *int64
	ResultDigest           *string
}

type IdenqaVerificationAttemptDiagnostic struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	Kind           string
	Code           string
	RecordedAt     pgtype.Timestamptz
}

type IdenqaVerificationCheck struct {
	ID             string
	TenantID       string
	VerificationID string
	Name           string
	State          string
	Outcome        *string
	Version        int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type IdenqaVerificationDecision struct {
	ID               string
	TenantID         string
	VerificationID   string
	SnapshotDigest   string
	EvaluationDigest string
	DecisionDigest   string
	Selected         string
	Outcome          string
	Actor            string
	SupersedesID     *string
	DecidedAt        pgtype.Timestamptz
	Canonical        string
}

type IdenqaVerificationInputRequest struct {
	ID             string
	TenantID       string
	VerificationID string
	CaseID         *string
	ReasonCodes    []string
	ActorID        string
	RequestedAt    pgtype.Timestamptz
	SupersededAt   pgtype.Timestamptz
}

type IdenqaVerificationObservation struct {
	ID                  string
	TenantID            string
	VerificationID      string
	CheckID             string
	AttemptID           string
	RunnerKind          string
	RunnerID            string
	RunnerVersion       string
	PackageDigest       string
	ContractMajor       int32
	ContractMinor       int32
	RequestDigest       string
	ConfigurationDigest string
	SignalName          string
	SignalOutcome       string
	ReasonCodes         []string
	RecordedAt          pgtype.Timestamptz
}

type IdenqaVerificationReconciliation struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	Reason         string
	Status         string
	ClaimToken     *string
	LeaseExpiresAt pgtype.Timestamptz
	ClaimCount     int32
	AvailableAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ResolvedAt     pgtype.Timestamptz
}

type IdenqaVerificationResultInbox struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	ResultDigest   string
	ReceivedAt     pgtype.Timestamptz
}

type IdenqaVerificationSession struct {
	ID                    string
	TenantID              string
	State                 string
	Version               int64
	SourceProfileID       string
	SourceProfileRevision int32
	SourceProfileDigest   string
	Requirements          []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	SubjectID             *string
	AuthorityID           *string
	NoticeID              *string
	Region                *string
	PolicyID              *string
	DecisionID            *string
	CaptureCompletedAt    pgtype.Timestamptz
	CompletedDecisionID   *string
	ExpiryDiscoveredAt    pgtype.Timestamptz
	FailureClass          *string
	FailureCode           *string
}

type IdenqaVerificationSessionAudit struct {
	TenantID         string
	VerificationID   string
	AggregateVersion int64
	Action           string
	ActorKeyID       string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaVerificationTransition struct {
	TenantID         string
	EventID          string
	VerificationID   string
	FromState        string
	ToState          string
	ExpectedVersion  int64
	ResultingVersion int64
	DecisionID       *string
	ActorID          string
	CommandDigest    string
	OccurredAt       pgtype.Timestamptz
}

type IdenqaWebhookDelivery struct {
	TenantID         string
	ID               string
	EndpointID       string
	EventID          string
	EventType        string
	Body             []byte
	BodyDigest       string
	State            string
	AttemptCount     int32
	MaxAttempts      int32
	NextAttemptAt    pgtype.Timestamptz
	DeliveredAt      pgtype.Timestamptz
	ReplayOf         *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	LastDiscoveredAt pgtype.Timestamptz
	BodyProvider     *string
	BodyReference    *string
	BodyKeyVersion   *string
	BodyAlgorithm    *string
	PayloadExpiresAt pgtype.Timestamptz
	PayloadExpiredAt pgtype.Timestamptz
	RetainUntil      pgtype.Timestamptz
}

type IdenqaWebhookDeliveryAttempt struct {
	TenantID           string
	DeliveryID         string
	AttemptNumber      int32
	SecretVersion      int64
	SignatureTimestamp int64
	StatusCode         int32
	ErrorClass         string
	RetryAfterMs       int64
	CompletedAt        pgtype.Timestamptz
	ResponseBody       *string
	ResponseTruncated  bool
}

type IdenqaWebhookEndpoint struct {
	TenantID                 string
	ID                       string
	Url                      string
	SecretVersion            int64
	PreviousSecretVersion    *int64
	PreviousSecretValidUntil pgtype.Timestamptz
	DisabledAt               pgtype.Timestamptz
	DisabledReason           *string
	Version                  int64
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	EventTypes               []string
	SchemaVersion            string
}

type IdenqaWebhookEvent struct {
	TenantID         string
	ID               string
	EventType        string
	SchemaVersion    string
	DedupeKey        string
	Body             []byte
	BodyDigest       string
	State            string
	Cursor           string
	DeliveredCount   int32
	CreatedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	BodyProvider     *string
	BodyReference    *string
	BodyKeyVersion   *string
	BodyAlgorithm    *string
	StreamSequence   *int64
	AggregateIds     []string
	PayloadExpiresAt pgtype.Timestamptz
	PayloadExpiredAt pgtype.Timestamptz
	RetainUntil      pgtype.Timestamptz
}

type IdenqaWebhookSecret struct {
	TenantID   string
	EndpointID string
	Version    int64
	Provider   string
	Reference  string
	KeyVersion string
	Algorithm  string
	Ciphertext []byte
	CreatedAt  pgtype.Timestamptz
}

type IdenqaWebsocketConnectionTicket struct {
	ID             string
	TenantID       string
	VerificationID string
	CaptureTokenID string
	Digest         []byte
	DigestVersion  int32
	ClientKind     string
	ClientIdentity string
	Region         string
	Protocol       string
	IssuedAt       pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RedeemedAt     pgtype.Timestamptz
	ConnectionID   *string
}
