// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePolicy = `-- name: ActivatePolicy :one
UPDATE idenqa.policies
SET activation_version = $1,
    active_revision = $2::bigint,
    updated_at = $3
WHERE tenant_id = $4
  AND id = $5
  AND activation_version = $6
  AND $1 = $6 + 1
RETURNING tenant_id, id, activation_version, active_revision, created_at, updated_at
`

type ActivatePolicyParams struct {
	NewVersion      int64
	Revision        int64
	ActivatedAt     pgtype.Timestamptz
	TenantID        string
	PolicyID        string
	ExpectedVersion int64
}

func (q *Queries) ActivatePolicy(ctx context.Context, arg ActivatePolicyParams) (IdenqaPolicy, error) {
	row := q.db.QueryRow(ctx, activatePolicy,
		arg.NewVersion,
		arg.Revision,
		arg.ActivatedAt,
		arg.TenantID,
		arg.PolicyID,
		arg.ExpectedVersion,
	)
	var i IdenqaPolicy
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ActivationVersion,
		&i.ActiveRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActivePolicy = `-- name: FindActivePolicy :one
SELECT
    revisions.tenant_id, revisions.policy_id, revisions.revision, revisions.schema_major, revisions.schema_minor, revisions.digest, revisions.evaluator_major, revisions.evaluator_minor, revisions.evaluator_digest, revisions.canonical, revisions.created_at,
    policies.activation_version,
    activations.previous_revision,
    activations.actor_key_id,
    activations.activated_at
FROM idenqa.policies AS policies
JOIN idenqa.policy_revisions AS revisions
  ON revisions.tenant_id = policies.tenant_id
 AND revisions.policy_id = policies.id
 AND revisions.revision = policies.active_revision
JOIN idenqa.policy_activations AS activations
  ON activations.tenant_id = policies.tenant_id
 AND activations.policy_id = policies.id
 AND activations.activation_version = policies.activation_version
WHERE policies.tenant_id = $1
  AND policies.id = $2
`

type FindActivePolicyParams struct {
	TenantID string
	PolicyID string
}

type FindActivePolicyRow struct {
	TenantID          string
	PolicyID          string
	Revision          int64
	SchemaMajor       int32
	SchemaMinor       int32
	Digest            string
	EvaluatorMajor    int32
	EvaluatorMinor    int32
	EvaluatorDigest   string
	Canonical         string
	CreatedAt         pgtype.Timestamptz
	ActivationVersion int64
	PreviousRevision  *int64
	ActorKeyID        string
	ActivatedAt       pgtype.Timestamptz
}

func (q *Queries) FindActivePolicy(ctx context.Context, arg FindActivePolicyParams) (FindActivePolicyRow, error) {
	row := q.db.QueryRow(ctx, findActivePolicy, arg.TenantID, arg.PolicyID)
	var i FindActivePolicyRow
	err := row.Scan(
		&i.TenantID,
		&i.PolicyID,
		&i.Revision,
		&i.SchemaMajor,
		&i.SchemaMinor,
		&i.Digest,
		&i.EvaluatorMajor,
		&i.EvaluatorMinor,
		&i.EvaluatorDigest,
		&i.Canonical,
		&i.CreatedAt,
		&i.ActivationVersion,
		&i.PreviousRevision,
		&i.ActorKeyID,
		&i.ActivatedAt,
	)
	return i, err
}

const findLatestPolicyDecisionBundle = `-- name: FindLatestPolicyDecisionBundle :one
SELECT
    decisions.id, decisions.tenant_id, decisions.verification_id, decisions.snapshot_digest, decisions.evaluation_digest, decisions.decision_digest, decisions.selected, decisions.outcome, decisions.actor, decisions.supersedes_id, decisions.decided_at, decisions.canonical,
    snapshots.canonical AS snapshot_canonical,
    evaluations.canonical AS evaluation_canonical
FROM idenqa.verification_decisions AS decisions
JOIN idenqa.policy_snapshots AS snapshots
  ON snapshots.tenant_id = decisions.tenant_id
 AND snapshots.verification_id = decisions.verification_id
 AND snapshots.snapshot_digest = decisions.snapshot_digest
JOIN idenqa.policy_evaluations AS evaluations
  ON evaluations.tenant_id = decisions.tenant_id
 AND evaluations.verification_id = decisions.verification_id
 AND evaluations.snapshot_digest = decisions.snapshot_digest
 AND evaluations.evaluation_digest = decisions.evaluation_digest
WHERE decisions.tenant_id = $1
  AND decisions.verification_id = $2
  AND NOT EXISTS (
      SELECT 1
      FROM idenqa.verification_decisions AS successor
      WHERE successor.tenant_id = decisions.tenant_id
        AND successor.verification_id = decisions.verification_id
        AND successor.supersedes_id = decisions.id
  )
LIMIT 1
`

type FindLatestPolicyDecisionBundleParams struct {
	TenantID       string
	VerificationID string
}

type FindLatestPolicyDecisionBundleRow struct {
	ID                  string
	TenantID            string
	VerificationID      string
	SnapshotDigest      string
	EvaluationDigest    string
	DecisionDigest      string
	Selected            string
	Outcome             string
	Actor               string
	SupersedesID        *string
	DecidedAt           pgtype.Timestamptz
	Canonical           string
	SnapshotCanonical   string
	EvaluationCanonical string
}

func (q *Queries) FindLatestPolicyDecisionBundle(ctx context.Context, arg FindLatestPolicyDecisionBundleParams) (FindLatestPolicyDecisionBundleRow, error) {
	row := q.db.QueryRow(ctx, findLatestPolicyDecisionBundle, arg.TenantID, arg.VerificationID)
	var i FindLatestPolicyDecisionBundleRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VerificationID,
		&i.SnapshotDigest,
		&i.EvaluationDigest,
		&i.DecisionDigest,
		&i.Selected,
		&i.Outcome,
		&i.Actor,
		&i.SupersedesID,
		&i.DecidedAt,
		&i.Canonical,
		&i.SnapshotCanonical,
		&i.EvaluationCanonical,
	)
	return i, err
}

const findPolicyAuthoritativeHeader = `-- name: FindPolicyAuthoritativeHeader :one
SELECT
    sessions.region,
    sessions.policy_id,
    authorities.id AS authority_id,
    responses.id AS acknowledgement_id,
    responses.action AS response_action,
    responses.recorded_at AS response_recorded_at
FROM idenqa.verification_sessions AS sessions
JOIN idenqa.processing_authorities AS authorities
  ON authorities.tenant_id = sessions.tenant_id
 AND authorities.id = sessions.authority_id
JOIN LATERAL (
    SELECT id, action, recorded_at
    FROM idenqa.subject_responses
    WHERE tenant_id = authorities.tenant_id
      AND authority_id = authorities.id
      AND verification_id = sessions.id
      AND recorded_at <= $1
    ORDER BY recorded_at DESC, id DESC
    LIMIT 1
) AS responses ON true
WHERE sessions.tenant_id = $2
  AND sessions.id = $3
  AND sessions.created_at <= $1
  AND sessions.region IS NOT NULL
  AND sessions.policy_id IS NOT NULL
  AND authorities.state = 'active'
  AND authorities.valid_from <= $1
  AND authorities.expires_at > $1
`

type FindPolicyAuthoritativeHeaderParams struct {
	EvaluatedAt    pgtype.Timestamptz
	TenantID       string
	VerificationID string
}

type FindPolicyAuthoritativeHeaderRow struct {
	Region             *string
	PolicyID           *string
	AuthorityID        string
	AcknowledgementID  string
	ResponseAction     string
	ResponseRecordedAt pgtype.Timestamptz
}

func (q *Queries) FindPolicyAuthoritativeHeader(ctx context.Context, arg FindPolicyAuthoritativeHeaderParams) (FindPolicyAuthoritativeHeaderRow, error) {
	row := q.db.QueryRow(ctx, findPolicyAuthoritativeHeader, arg.EvaluatedAt, arg.TenantID, arg.VerificationID)
	var i FindPolicyAuthoritativeHeaderRow
	err := row.Scan(
		&i.Region,
		&i.PolicyID,
		&i.AuthorityID,
		&i.AcknowledgementID,
		&i.ResponseAction,
		&i.ResponseRecordedAt,
	)
	return i, err
}

const findPolicyDecisionBundle = `-- name: FindPolicyDecisionBundle :one
SELECT
    decisions.id, decisions.tenant_id, decisions.verification_id, decisions.snapshot_digest, decisions.evaluation_digest, decisions.decision_digest, decisions.selected, decisions.outcome, decisions.actor, decisions.supersedes_id, decisions.decided_at, decisions.canonical,
    snapshots.canonical AS snapshot_canonical,
    evaluations.canonical AS evaluation_canonical
FROM idenqa.verification_decisions AS decisions
JOIN idenqa.policy_snapshots AS snapshots
  ON snapshots.tenant_id = decisions.tenant_id
 AND snapshots.verification_id = decisions.verification_id
 AND snapshots.snapshot_digest = decisions.snapshot_digest
JOIN idenqa.policy_evaluations AS evaluations
  ON evaluations.tenant_id = decisions.tenant_id
 AND evaluations.verification_id = decisions.verification_id
 AND evaluations.snapshot_digest = decisions.snapshot_digest
 AND evaluations.evaluation_digest = decisions.evaluation_digest
WHERE decisions.tenant_id = $1 AND decisions.id = $2
`

type FindPolicyDecisionBundleParams struct {
	TenantID string
	ID       string
}

type FindPolicyDecisionBundleRow struct {
	ID                  string
	TenantID            string
	VerificationID      string
	SnapshotDigest      string
	EvaluationDigest    string
	DecisionDigest      string
	Selected            string
	Outcome             string
	Actor               string
	SupersedesID        *string
	DecidedAt           pgtype.Timestamptz
	Canonical           string
	SnapshotCanonical   string
	EvaluationCanonical string
}

func (q *Queries) FindPolicyDecisionBundle(ctx context.Context, arg FindPolicyDecisionBundleParams) (FindPolicyDecisionBundleRow, error) {
	row := q.db.QueryRow(ctx, findPolicyDecisionBundle, arg.TenantID, arg.ID)
	var i FindPolicyDecisionBundleRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VerificationID,
		&i.SnapshotDigest,
		&i.EvaluationDigest,
		&i.DecisionDigest,
		&i.Selected,
		&i.Outcome,
		&i.Actor,
		&i.SupersedesID,
		&i.DecidedAt,
		&i.Canonical,
		&i.SnapshotCanonical,
		&i.EvaluationCanonical,
	)
	return i, err
}

const findPolicyEvaluation = `-- name: FindPolicyEvaluation :one
SELECT tenant_id, verification_id, snapshot_digest, evaluation_digest, selected, outcome, assurance, canonical FROM idenqa.policy_evaluations
WHERE tenant_id = $1 AND evaluation_digest = $2
`

type FindPolicyEvaluationParams struct {
	TenantID         string
	EvaluationDigest string
}

func (q *Queries) FindPolicyEvaluation(ctx context.Context, arg FindPolicyEvaluationParams) (IdenqaPolicyEvaluation, error) {
	row := q.db.QueryRow(ctx, findPolicyEvaluation, arg.TenantID, arg.EvaluationDigest)
	var i IdenqaPolicyEvaluation
	err := row.Scan(
		&i.TenantID,
		&i.VerificationID,
		&i.SnapshotDigest,
		&i.EvaluationDigest,
		&i.Selected,
		&i.Outcome,
		&i.Assurance,
		&i.Canonical,
	)
	return i, err
}

const findPolicyRevision = `-- name: FindPolicyRevision :one
SELECT tenant_id, policy_id, revision, schema_major, schema_minor, digest, evaluator_major, evaluator_minor, evaluator_digest, canonical, created_at FROM idenqa.policy_revisions
WHERE tenant_id = $1
  AND policy_id = $2
  AND revision = $3
`

type FindPolicyRevisionParams struct {
	TenantID string
	PolicyID string
	Revision int64
}

func (q *Queries) FindPolicyRevision(ctx context.Context, arg FindPolicyRevisionParams) (IdenqaPolicyRevision, error) {
	row := q.db.QueryRow(ctx, findPolicyRevision, arg.TenantID, arg.PolicyID, arg.Revision)
	var i IdenqaPolicyRevision
	err := row.Scan(
		&i.TenantID,
		&i.PolicyID,
		&i.Revision,
		&i.SchemaMajor,
		&i.SchemaMinor,
		&i.Digest,
		&i.EvaluatorMajor,
		&i.EvaluatorMinor,
		&i.EvaluatorDigest,
		&i.Canonical,
		&i.CreatedAt,
	)
	return i, err
}

const findPolicySnapshot = `-- name: FindPolicySnapshot :one
SELECT tenant_id, verification_id, snapshot_digest, policy_id, policy_revision, policy_schema_major, policy_schema_minor, policy_digest, evaluator_major, evaluator_minor, evaluator_digest, authority_id, acknowledgement_id, region, evaluated_at, canonical FROM idenqa.policy_snapshots
WHERE tenant_id = $1 AND snapshot_digest = $2
`

type FindPolicySnapshotParams struct {
	TenantID       string
	SnapshotDigest string
}

func (q *Queries) FindPolicySnapshot(ctx context.Context, arg FindPolicySnapshotParams) (IdenqaPolicySnapshot, error) {
	row := q.db.QueryRow(ctx, findPolicySnapshot, arg.TenantID, arg.SnapshotDigest)
	var i IdenqaPolicySnapshot
	err := row.Scan(
		&i.TenantID,
		&i.VerificationID,
		&i.SnapshotDigest,
		&i.PolicyID,
		&i.PolicyRevision,
		&i.PolicySchemaMajor,
		&i.PolicySchemaMinor,
		&i.PolicyDigest,
		&i.EvaluatorMajor,
		&i.EvaluatorMinor,
		&i.EvaluatorDigest,
		&i.AuthorityID,
		&i.AcknowledgementID,
		&i.Region,
		&i.EvaluatedAt,
		&i.Canonical,
	)
	return i, err
}

const insertPolicy = `-- name: InsertPolicy :execrows
INSERT INTO idenqa.policies (
    tenant_id, id, activation_version, active_revision, created_at, updated_at
) VALUES (
    $1, $2, 0, NULL,
    $3, $3
)
ON CONFLICT DO NOTHING
`

type InsertPolicyParams struct {
	TenantID  string
	PolicyID  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicy, arg.TenantID, arg.PolicyID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPolicyActivation = `-- name: InsertPolicyActivation :exec
INSERT INTO idenqa.policy_activations (
    tenant_id, policy_id, activation_version, revision, previous_revision,
    actor_key_id, activated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7
)
`

type InsertPolicyActivationParams struct {
	TenantID          string
	PolicyID          string
	ActivationVersion int64
	Revision          int64
	PreviousRevision  *int64
	ActorKeyID        string
	ActivatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertPolicyActivation(ctx context.Context, arg InsertPolicyActivationParams) error {
	_, err := q.db.Exec(ctx, insertPolicyActivation,
		arg.TenantID,
		arg.PolicyID,
		arg.ActivationVersion,
		arg.Revision,
		arg.PreviousRevision,
		arg.ActorKeyID,
		arg.ActivatedAt,
	)
	return err
}

const insertPolicyDecision = `-- name: InsertPolicyDecision :execrows
INSERT INTO idenqa.verification_decisions (
    id, tenant_id, verification_id, snapshot_digest, evaluation_digest,
    decision_digest, selected, outcome, actor, supersedes_id, decided_at, canonical
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12
)
ON CONFLICT DO NOTHING
`

type InsertPolicyDecisionParams struct {
	ID               string
	TenantID         string
	VerificationID   string
	SnapshotDigest   string
	EvaluationDigest string
	DecisionDigest   string
	Selected         string
	Outcome          string
	Actor            string
	SupersedesID     *string
	DecidedAt        pgtype.Timestamptz
	Canonical        string
}

func (q *Queries) InsertPolicyDecision(ctx context.Context, arg InsertPolicyDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicyDecision,
		arg.ID,
		arg.TenantID,
		arg.VerificationID,
		arg.SnapshotDigest,
		arg.EvaluationDigest,
		arg.DecisionDigest,
		arg.Selected,
		arg.Outcome,
		arg.Actor,
		arg.SupersedesID,
		arg.DecidedAt,
		arg.Canonical,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPolicyEvaluation = `-- name: InsertPolicyEvaluation :execrows
INSERT INTO idenqa.policy_evaluations (
    tenant_id, verification_id, snapshot_digest, evaluation_digest,
    selected, outcome, assurance, canonical
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
ON CONFLICT DO NOTHING
`

type InsertPolicyEvaluationParams struct {
	TenantID         string
	VerificationID   string
	SnapshotDigest   string
	EvaluationDigest string
	Selected         string
	Outcome          *string
	Assurance        *string
	Canonical        string
}

func (q *Queries) InsertPolicyEvaluation(ctx context.Context, arg InsertPolicyEvaluationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicyEvaluation,
		arg.TenantID,
		arg.VerificationID,
		arg.SnapshotDigest,
		arg.EvaluationDigest,
		arg.Selected,
		arg.Outcome,
		arg.Assurance,
		arg.Canonical,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPolicyRevision = `-- name: InsertPolicyRevision :execrows
INSERT INTO idenqa.policy_revisions (
    tenant_id, policy_id, revision, schema_major, schema_minor, digest,
    evaluator_major, evaluator_minor, evaluator_digest, canonical, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
ON CONFLICT DO NOTHING
`

type InsertPolicyRevisionParams struct {
	TenantID        string
	PolicyID        string
	Revision        int64
	SchemaMajor     int32
	SchemaMinor     int32
	Digest          string
	EvaluatorMajor  int32
	EvaluatorMinor  int32
	EvaluatorDigest string
	Canonical       string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertPolicyRevision(ctx context.Context, arg InsertPolicyRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicyRevision,
		arg.TenantID,
		arg.PolicyID,
		arg.Revision,
		arg.SchemaMajor,
		arg.SchemaMinor,
		arg.Digest,
		arg.EvaluatorMajor,
		arg.EvaluatorMinor,
		arg.EvaluatorDigest,
		arg.Canonical,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPolicySnapshot = `-- name: InsertPolicySnapshot :execrows
INSERT INTO idenqa.policy_snapshots (
    tenant_id, verification_id, snapshot_digest, policy_id, policy_revision,
    policy_schema_major, policy_schema_minor, policy_digest, evaluator_major,
    evaluator_minor, evaluator_digest, authority_id, acknowledgement_id,
    region, evaluated_at, canonical
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16
)
ON CONFLICT DO NOTHING
`

type InsertPolicySnapshotParams struct {
	TenantID          string
	VerificationID    string
	SnapshotDigest    string
	PolicyID          string
	PolicyRevision    int64
	PolicySchemaMajor int32
	PolicySchemaMinor int32
	PolicyDigest      string
	EvaluatorMajor    int32
	EvaluatorMinor    int32
	EvaluatorDigest   string
	AuthorityID       string
	AcknowledgementID string
	Region            string
	EvaluatedAt       pgtype.Timestamptz
	Canonical         string
}

func (q *Queries) InsertPolicySnapshot(ctx context.Context, arg InsertPolicySnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolicySnapshot,
		arg.TenantID,
		arg.VerificationID,
		arg.SnapshotDigest,
		arg.PolicyID,
		arg.PolicyRevision,
		arg.PolicySchemaMajor,
		arg.PolicySchemaMinor,
		arg.PolicyDigest,
		arg.EvaluatorMajor,
		arg.EvaluatorMinor,
		arg.EvaluatorDigest,
		arg.AuthorityID,
		arg.AcknowledgementID,
		arg.Region,
		arg.EvaluatedAt,
		arg.Canonical,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPolicyActivationMetadata = `-- name: ListPolicyActivationMetadata :many
SELECT
    activations.policy_id,
    activations.activation_version,
    activations.revision,
    activations.previous_revision,
    activations.actor_key_id,
    activations.activated_at,
    revisions.schema_major,
    revisions.schema_minor,
    revisions.digest,
    revisions.evaluator_major,
    revisions.evaluator_minor,
    revisions.evaluator_digest,
    revisions.created_at
FROM idenqa.policy_activations AS activations
JOIN idenqa.policy_revisions AS revisions
  ON revisions.tenant_id = activations.tenant_id
 AND revisions.policy_id = activations.policy_id
 AND revisions.revision = activations.revision
WHERE activations.tenant_id = $1
  AND activations.policy_id = $2
  AND (
      $3::bigint = 0 OR
      activations.activation_version < $3
  )
ORDER BY activations.activation_version DESC
LIMIT $4
`

type ListPolicyActivationMetadataParams struct {
	TenantID                string
	PolicyID                string
	BeforeActivationVersion int64
	PageLimit               int32
}

type ListPolicyActivationMetadataRow struct {
	PolicyID          string
	ActivationVersion int64
	Revision          int64
	PreviousRevision  *int64
	ActorKeyID        string
	ActivatedAt       pgtype.Timestamptz
	SchemaMajor       int32
	SchemaMinor       int32
	Digest            string
	EvaluatorMajor    int32
	EvaluatorMinor    int32
	EvaluatorDigest   string
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListPolicyActivationMetadata(ctx context.Context, arg ListPolicyActivationMetadataParams) ([]ListPolicyActivationMetadataRow, error) {
	rows, err := q.db.Query(ctx, listPolicyActivationMetadata,
		arg.TenantID,
		arg.PolicyID,
		arg.BeforeActivationVersion,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPolicyActivationMetadataRow
	for rows.Next() {
		var i ListPolicyActivationMetadataRow
		if err := rows.Scan(
			&i.PolicyID,
			&i.ActivationVersion,
			&i.Revision,
			&i.PreviousRevision,
			&i.ActorKeyID,
			&i.ActivatedAt,
			&i.SchemaMajor,
			&i.SchemaMinor,
			&i.Digest,
			&i.EvaluatorMajor,
			&i.EvaluatorMinor,
			&i.EvaluatorDigest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyAuthoritativeObservations = `-- name: ListPolicyAuthoritativeObservations :many
WITH completed_attempts AS (
    SELECT DISTINCT ON (attempts.check_id)
        attempts.id, attempts.tenant_id, attempts.verification_id, attempts.check_id, attempts.attempt_number, attempts.fence, attempts.runner_kind, attempts.runner_id, attempts.runner_version, attempts.package_digest, attempts.contract_major, attempts.contract_minor, attempts.request_digest, attempts.configuration_digest, attempts.state, attempts.started_at, attempts.deadline, attempts.finished_at, attempts.failure_class, attempts.failure_code, attempts.retry_disposition, attempts.retry_after_milliseconds, attempts.result_digest
    FROM idenqa.verification_attempts AS attempts
    WHERE attempts.tenant_id = $1
      AND attempts.verification_id = $2
      AND attempts.state = 'completed'
      AND attempts.finished_at <= $3
    ORDER BY attempts.check_id, attempts.attempt_number DESC
)
SELECT
    checks.id AS check_id,
    checks.name AS check_name,
    checks.outcome AS check_outcome,
    checks.version AS check_version,
    checks.updated_at AS check_updated_at,
    attempts.id AS attempt_id,
    attempts.attempt_number,
    attempts.runner_kind,
    attempts.runner_id,
    attempts.runner_version,
    attempts.package_digest,
    attempts.contract_major,
    attempts.contract_minor,
    attempts.request_digest,
    attempts.configuration_digest,
    attempts.result_digest,
    observations.id AS observation_id,
    observations.signal_name,
    observations.signal_outcome,
    observations.reason_codes,
    observations.recorded_at
FROM idenqa.verification_checks AS checks
JOIN completed_attempts AS attempts
  ON attempts.tenant_id = checks.tenant_id
 AND attempts.verification_id = checks.verification_id
 AND attempts.check_id = checks.id
JOIN idenqa.verification_observations AS observations
  ON observations.tenant_id = attempts.tenant_id
 AND observations.verification_id = attempts.verification_id
 AND observations.check_id = attempts.check_id
 AND observations.attempt_id = attempts.id
WHERE checks.tenant_id = $1
  AND checks.verification_id = $2
  AND checks.state = 'completed'
  AND checks.updated_at <= $3
  AND observations.recorded_at <= $3
ORDER BY checks.id, observations.recorded_at, observations.id
LIMIT 8193
`

type ListPolicyAuthoritativeObservationsParams struct {
	TenantID       string
	VerificationID string
	EvaluatedAt    pgtype.Timestamptz
}

type ListPolicyAuthoritativeObservationsRow struct {
	CheckID             string
	CheckName           string
	CheckOutcome        *string
	CheckVersion        int64
	CheckUpdatedAt      pgtype.Timestamptz
	AttemptID           string
	AttemptNumber       int32
	RunnerKind          string
	RunnerID            string
	RunnerVersion       string
	PackageDigest       string
	ContractMajor       int32
	ContractMinor       int32
	RequestDigest       string
	ConfigurationDigest string
	ResultDigest        *string
	ObservationID       string
	SignalName          string
	SignalOutcome       string
	ReasonCodes         []string
	RecordedAt          pgtype.Timestamptz
}

// One sentinel row above the in-memory bound makes overflow fail closed rather
// than silently truncating authoritative provenance.
func (q *Queries) ListPolicyAuthoritativeObservations(ctx context.Context, arg ListPolicyAuthoritativeObservationsParams) ([]ListPolicyAuthoritativeObservationsRow, error) {
	rows, err := q.db.Query(ctx, listPolicyAuthoritativeObservations, arg.TenantID, arg.VerificationID, arg.EvaluatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPolicyAuthoritativeObservationsRow
	for rows.Next() {
		var i ListPolicyAuthoritativeObservationsRow
		if err := rows.Scan(
			&i.CheckID,
			&i.CheckName,
			&i.CheckOutcome,
			&i.CheckVersion,
			&i.CheckUpdatedAt,
			&i.AttemptID,
			&i.AttemptNumber,
			&i.RunnerKind,
			&i.RunnerID,
			&i.RunnerVersion,
			&i.PackageDigest,
			&i.ContractMajor,
			&i.ContractMinor,
			&i.RequestDigest,
			&i.ConfigurationDigest,
			&i.ResultDigest,
			&i.ObservationID,
			&i.SignalName,
			&i.SignalOutcome,
			&i.ReasonCodes,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyDecisionBundles = `-- name: ListPolicyDecisionBundles :many
SELECT
    decisions.id, decisions.tenant_id, decisions.verification_id, decisions.snapshot_digest, decisions.evaluation_digest, decisions.decision_digest, decisions.selected, decisions.outcome, decisions.actor, decisions.supersedes_id, decisions.decided_at, decisions.canonical,
    snapshots.canonical AS snapshot_canonical,
    evaluations.canonical AS evaluation_canonical
FROM idenqa.verification_decisions AS decisions
JOIN idenqa.policy_snapshots AS snapshots
  ON snapshots.tenant_id = decisions.tenant_id
 AND snapshots.verification_id = decisions.verification_id
 AND snapshots.snapshot_digest = decisions.snapshot_digest
JOIN idenqa.policy_evaluations AS evaluations
  ON evaluations.tenant_id = decisions.tenant_id
 AND evaluations.verification_id = decisions.verification_id
 AND evaluations.snapshot_digest = decisions.snapshot_digest
 AND evaluations.evaluation_digest = decisions.evaluation_digest
WHERE decisions.tenant_id = $1
  AND decisions.verification_id = $2
  AND (
      $3::text = '' OR
      (decisions.decided_at, decisions.id) < (
          SELECT cursor.decided_at, cursor.id
          FROM idenqa.verification_decisions AS cursor
          WHERE cursor.tenant_id = $1
            AND cursor.verification_id = $2
            AND cursor.id = $3
      )
  )
ORDER BY decisions.decided_at DESC, decisions.id DESC
LIMIT $4
`

type ListPolicyDecisionBundlesParams struct {
	TenantID       string
	VerificationID string
	BeforeID       string
	PageLimit      int32
}

type ListPolicyDecisionBundlesRow struct {
	ID                  string
	TenantID            string
	VerificationID      string
	SnapshotDigest      string
	EvaluationDigest    string
	DecisionDigest      string
	Selected            string
	Outcome             string
	Actor               string
	SupersedesID        *string
	DecidedAt           pgtype.Timestamptz
	Canonical           string
	SnapshotCanonical   string
	EvaluationCanonical string
}

func (q *Queries) ListPolicyDecisionBundles(ctx context.Context, arg ListPolicyDecisionBundlesParams) ([]ListPolicyDecisionBundlesRow, error) {
	rows, err := q.db.Query(ctx, listPolicyDecisionBundles,
		arg.TenantID,
		arg.VerificationID,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPolicyDecisionBundlesRow
	for rows.Next() {
		var i ListPolicyDecisionBundlesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.VerificationID,
			&i.SnapshotDigest,
			&i.EvaluationDigest,
			&i.DecisionDigest,
			&i.Selected,
			&i.Outcome,
			&i.Actor,
			&i.SupersedesID,
			&i.DecidedAt,
			&i.Canonical,
			&i.SnapshotCanonical,
			&i.EvaluationCanonical,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyRevisionMetadata = `-- name: ListPolicyRevisionMetadata :many
SELECT
    policy_id, revision, schema_major, schema_minor, digest,
    evaluator_major, evaluator_minor, evaluator_digest, created_at
FROM idenqa.policy_revisions
WHERE tenant_id = $1
  AND policy_id = $2
  AND ($3::bigint = 0 OR revision < $3)
ORDER BY revision DESC
LIMIT $4
`

type ListPolicyRevisionMetadataParams struct {
	TenantID       string
	PolicyID       string
	BeforeRevision int64
	PageLimit      int32
}

type ListPolicyRevisionMetadataRow struct {
	PolicyID        string
	Revision        int64
	SchemaMajor     int32
	SchemaMinor     int32
	Digest          string
	EvaluatorMajor  int32
	EvaluatorMinor  int32
	EvaluatorDigest string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListPolicyRevisionMetadata(ctx context.Context, arg ListPolicyRevisionMetadataParams) ([]ListPolicyRevisionMetadataRow, error) {
	rows, err := q.db.Query(ctx, listPolicyRevisionMetadata,
		arg.TenantID,
		arg.PolicyID,
		arg.BeforeRevision,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPolicyRevisionMetadataRow
	for rows.Next() {
		var i ListPolicyRevisionMetadataRow
		if err := rows.Scan(
			&i.PolicyID,
			&i.Revision,
			&i.SchemaMajor,
			&i.SchemaMinor,
			&i.Digest,
			&i.EvaluatorMajor,
			&i.EvaluatorMinor,
			&i.EvaluatorDigest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPolicy = `-- name: LockPolicy :one
SELECT tenant_id, id, activation_version, active_revision, created_at, updated_at FROM idenqa.policies
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockPolicyParams struct {
	TenantID string
	PolicyID string
}

func (q *Queries) LockPolicy(ctx context.Context, arg LockPolicyParams) (IdenqaPolicy, error) {
	row := q.db.QueryRow(ctx, lockPolicy, arg.TenantID, arg.PolicyID)
	var i IdenqaPolicy
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ActivationVersion,
		&i.ActiveRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPolicyDecision = `-- name: LockPolicyDecision :one
SELECT id, tenant_id, verification_id, snapshot_digest, evaluation_digest, decision_digest, selected, outcome, actor, supersedes_id, decided_at, canonical FROM idenqa.verification_decisions
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockPolicyDecisionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) LockPolicyDecision(ctx context.Context, arg LockPolicyDecisionParams) (IdenqaVerificationDecision, error) {
	row := q.db.QueryRow(ctx, lockPolicyDecision, arg.TenantID, arg.ID)
	var i IdenqaVerificationDecision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VerificationID,
		&i.SnapshotDigest,
		&i.EvaluationDigest,
		&i.DecisionDigest,
		&i.Selected,
		&i.Outcome,
		&i.Actor,
		&i.SupersedesID,
		&i.DecidedAt,
		&i.Canonical,
	)
	return i, err
}
