// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlgen

import (
	"context"
)

type Querier interface {
	ActivatePolicy(ctx context.Context, arg ActivatePolicyParams) (IdenqaPolicy, error)
	AdvanceRealtimeStream(ctx context.Context, arg AdvanceRealtimeStreamParams) (int64, error)
	BindVerificationAuthority(ctx context.Context, arg BindVerificationAuthorityParams) (int64, error)
	CheckConnection(ctx context.Context) (int64, error)
	ClaimVerificationReconciliation(ctx context.Context, arg ClaimVerificationReconciliationParams) (IdenqaVerificationReconciliation, error)
	ClaimVerificationReconciliationForAttempt(ctx context.Context, arg ClaimVerificationReconciliationForAttemptParams) (IdenqaVerificationReconciliation, error)
	ClaimVerificationResultInbox(ctx context.Context, arg ClaimVerificationResultInboxParams) (int64, error)
	CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (IdenqaIdempotencyRecord, error)
	CompleteVerificationAttempt(ctx context.Context, arg CompleteVerificationAttemptParams) (int64, error)
	CompleteVerificationCapture(ctx context.Context, arg CompleteVerificationCaptureParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (int64, error)
	CreateCaptureProfile(ctx context.Context, arg CreateCaptureProfileParams) error
	CreateCaptureProfileRevision(ctx context.Context, arg CreateCaptureProfileRevisionParams) error
	CreateCaptureToken(ctx context.Context, arg CreateCaptureTokenParams) error
	CreateDeniedEvidenceGrantRedemption(ctx context.Context, arg CreateDeniedEvidenceGrantRedemptionParams) error
	CreateEvidenceAsset(ctx context.Context, arg CreateEvidenceAssetParams) error
	CreateEvidenceGrantRedemptionOutcome(ctx context.Context, arg CreateEvidenceGrantRedemptionOutcomeParams) (int64, error)
	CreateEvidenceObjectReconciliation(ctx context.Context, arg CreateEvidenceObjectReconciliationParams) (int64, error)
	CreateEvidenceProcessingGrant(ctx context.Context, arg CreateEvidenceProcessingGrantParams) error
	CreateEvidenceUploadIntent(ctx context.Context, arg CreateEvidenceUploadIntentParams) error
	CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (int64, error)
	CreateNoticeVersion(ctx context.Context, arg CreateNoticeVersionParams) (IdenqaNoticeVersion, error)
	CreateOutcomeToken(ctx context.Context, arg CreateOutcomeTokenParams) error
	CreatePendingEvidenceGrantRedemption(ctx context.Context, arg CreatePendingEvidenceGrantRedemptionParams) error
	CreateProcessingAuthority(ctx context.Context, arg CreateProcessingAuthorityParams) (IdenqaProcessingAuthority, error)
	CreateSubjectResponse(ctx context.Context, arg CreateSubjectResponseParams) (IdenqaSubjectResponse, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) error
	CreateVerificationSession(ctx context.Context, arg CreateVerificationSessionParams) error
	CreateVerificationSubject(ctx context.Context, arg CreateVerificationSubjectParams) error
	CreateWebSocketConnectionTicket(ctx context.Context, arg CreateWebSocketConnectionTicketParams) (int64, error)
	DeleteExpiredIdempotencyRecord(ctx context.Context, arg DeleteExpiredIdempotencyRecordParams) error
	DeleteExpiredRealtimeEvents(ctx context.Context, arg DeleteExpiredRealtimeEventsParams) ([]string, error)
	DeleteExpiredUnredeemedWebSocketTickets(ctx context.Context, arg DeleteExpiredUnredeemedWebSocketTicketsParams) ([]string, error)
	DisableTenant(ctx context.Context, arg DisableTenantParams) (IdenqaTenant, error)
	EnsureRealtimeStream(ctx context.Context, arg EnsureRealtimeStreamParams) (int64, error)
	FenceVerificationAuthoritySession(ctx context.Context, arg FenceVerificationAuthoritySessionParams) (int64, error)
	FindAPIKey(ctx context.Context, arg FindAPIKeyParams) (IdenqaApiKey, error)
	FindAPIKeyForVerification(ctx context.Context, arg FindAPIKeyForVerificationParams) (FindAPIKeyForVerificationRow, error)
	FindActivePolicy(ctx context.Context, arg FindActivePolicyParams) (FindActivePolicyRow, error)
	FindCaptureContext(ctx context.Context, arg FindCaptureContextParams) (FindCaptureContextRow, error)
	FindCaptureOutcome(ctx context.Context, arg FindCaptureOutcomeParams) (FindCaptureOutcomeRow, error)
	FindCaptureProfile(ctx context.Context, arg FindCaptureProfileParams) (IdenqaCaptureProfile, error)
	FindCaptureProfileRevision(ctx context.Context, arg FindCaptureProfileRevisionParams) (IdenqaCaptureProfileRevision, error)
	FindCaptureToken(ctx context.Context, arg FindCaptureTokenParams) (IdenqaCaptureToken, error)
	FindEvidenceAsset(ctx context.Context, arg FindEvidenceAssetParams) (IdenqaEvidenceAsset, error)
	FindEvidenceGrantRedemption(ctx context.Context, arg FindEvidenceGrantRedemptionParams) (IdenqaEvidenceGrantRedemption, error)
	FindEvidenceGrantRedemptionOutcome(ctx context.Context, arg FindEvidenceGrantRedemptionOutcomeParams) (IdenqaEvidenceGrantRedemptionOutcome, error)
	FindEvidenceObjectReconciliation(ctx context.Context, arg FindEvidenceObjectReconciliationParams) (IdenqaEvidenceObjectReconciliation, error)
	FindEvidenceProcessingGrant(ctx context.Context, arg FindEvidenceProcessingGrantParams) (IdenqaEvidenceProcessingGrant, error)
	FindEvidenceUploadIntent(ctx context.Context, arg FindEvidenceUploadIntentParams) (IdenqaEvidenceUploadIntent, error)
	FindIdempotencyRecord(ctx context.Context, arg FindIdempotencyRecordParams) (IdenqaIdempotencyRecord, error)
	FindLatestCaptureRecoveryToken(ctx context.Context, arg FindLatestCaptureRecoveryTokenParams) (string, error)
	FindLatestPolicyDecisionBundle(ctx context.Context, arg FindLatestPolicyDecisionBundleParams) (FindLatestPolicyDecisionBundleRow, error)
	FindLatestSubjectResponse(ctx context.Context, arg FindLatestSubjectResponseParams) (IdenqaSubjectResponse, error)
	FindNoticeVersion(ctx context.Context, arg FindNoticeVersionParams) (IdenqaNoticeVersion, error)
	FindOutcomeContext(ctx context.Context, arg FindOutcomeContextParams) (FindOutcomeContextRow, error)
	FindOutcomeToken(ctx context.Context, arg FindOutcomeTokenParams) (IdenqaOutcomeToken, error)
	FindOutcomeTokenByVerification(ctx context.Context, arg FindOutcomeTokenByVerificationParams) (IdenqaOutcomeToken, error)
	FindPolicyAuthoritativeHeader(ctx context.Context, arg FindPolicyAuthoritativeHeaderParams) (FindPolicyAuthoritativeHeaderRow, error)
	FindPolicyDecisionBundle(ctx context.Context, arg FindPolicyDecisionBundleParams) (FindPolicyDecisionBundleRow, error)
	FindPolicyEvaluation(ctx context.Context, arg FindPolicyEvaluationParams) (IdenqaPolicyEvaluation, error)
	FindPolicyRevision(ctx context.Context, arg FindPolicyRevisionParams) (IdenqaPolicyRevision, error)
	FindPolicySnapshot(ctx context.Context, arg FindPolicySnapshotParams) (IdenqaPolicySnapshot, error)
	FindProcessingAuthority(ctx context.Context, arg FindProcessingAuthorityParams) (IdenqaProcessingAuthority, error)
	FindProcessingAuthorityByVerification(ctx context.Context, arg FindProcessingAuthorityByVerificationParams) (IdenqaProcessingAuthority, error)
	FindRealtimeClientCommand(ctx context.Context, arg FindRealtimeClientCommandParams) (IdenqaRealtimeClientCommand, error)
	FindRealtimeEventByID(ctx context.Context, arg FindRealtimeEventByIDParams) (IdenqaRealtimeEvent, error)
	FindSubjectResponse(ctx context.Context, arg FindSubjectResponseParams) (IdenqaSubjectResponse, error)
	FindTenant(ctx context.Context, id string) (IdenqaTenant, error)
	FindVerificationCheck(ctx context.Context, arg FindVerificationCheckParams) (IdenqaVerificationCheck, error)
	FindVerificationReconciliationForAttempt(ctx context.Context, arg FindVerificationReconciliationForAttemptParams) (IdenqaVerificationReconciliation, error)
	FindVerificationSession(ctx context.Context, arg FindVerificationSessionParams) (IdenqaVerificationSession, error)
	IncrementEvidenceProcessingGrantUse(ctx context.Context, arg IncrementEvidenceProcessingGrantUseParams) (IdenqaEvidenceProcessingGrant, error)
	InsertAPIKeyAdminAudit(ctx context.Context, arg InsertAPIKeyAdminAuditParams) error
	InsertAuthorityAudit(ctx context.Context, arg InsertAuthorityAuditParams) error
	InsertCaptureProfileAudit(ctx context.Context, arg InsertCaptureProfileAuditParams) error
	InsertEvidenceAssetAudit(ctx context.Context, arg InsertEvidenceAssetAuditParams) error
	InsertEvidenceGrantAccessAttemptAudit(ctx context.Context, arg InsertEvidenceGrantAccessAttemptAuditParams) error
	InsertEvidenceKeyRewrapAudit(ctx context.Context, arg InsertEvidenceKeyRewrapAuditParams) error
	InsertEvidenceObjectReconciliationAudit(ctx context.Context, arg InsertEvidenceObjectReconciliationAuditParams) error
	InsertEvidenceProcessingGrantAudit(ctx context.Context, arg InsertEvidenceProcessingGrantAuditParams) error
	InsertEvidenceUploadIntentAudit(ctx context.Context, arg InsertEvidenceUploadIntentAuditParams) error
	InsertNoticeVersionAudit(ctx context.Context, arg InsertNoticeVersionAuditParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	InsertPolicy(ctx context.Context, arg InsertPolicyParams) (int64, error)
	InsertPolicyActivation(ctx context.Context, arg InsertPolicyActivationParams) error
	InsertPolicyDecision(ctx context.Context, arg InsertPolicyDecisionParams) (int64, error)
	InsertPolicyEvaluation(ctx context.Context, arg InsertPolicyEvaluationParams) (int64, error)
	InsertPolicyRevision(ctx context.Context, arg InsertPolicyRevisionParams) (int64, error)
	InsertPolicySnapshot(ctx context.Context, arg InsertPolicySnapshotParams) (int64, error)
	InsertRealtimeClientCommand(ctx context.Context, arg InsertRealtimeClientCommandParams) (int64, error)
	InsertRealtimeEvent(ctx context.Context, arg InsertRealtimeEventParams) error
	InsertTenantAdminAudit(ctx context.Context, arg InsertTenantAdminAuditParams) error
	InsertVerificationAttempt(ctx context.Context, arg InsertVerificationAttemptParams) (int64, error)
	InsertVerificationAttemptDiagnostic(ctx context.Context, arg InsertVerificationAttemptDiagnosticParams) (int64, error)
	InsertVerificationCheck(ctx context.Context, arg InsertVerificationCheckParams) error
	InsertVerificationObservation(ctx context.Context, arg InsertVerificationObservationParams) error
	InsertVerificationReconciliation(ctx context.Context, arg InsertVerificationReconciliationParams) (int64, error)
	InsertVerificationSessionAudit(ctx context.Context, arg InsertVerificationSessionAuditParams) error
	IsEvidenceObjectReferenced(ctx context.Context, arg IsEvidenceObjectReferencedParams) (bool, error)
	ListAPIKeys(ctx context.Context, tenantID string) ([]IdenqaApiKey, error)
	ListAcceptedEvidenceUploadIntents(ctx context.Context, arg ListAcceptedEvidenceUploadIntentsParams) ([]IdenqaEvidenceUploadIntent, error)
	ListCaptureProfilesAfter(ctx context.Context, arg ListCaptureProfilesAfterParams) ([]IdenqaCaptureProfile, error)
	ListCaptureProfilesFirst(ctx context.Context, arg ListCaptureProfilesFirstParams) ([]IdenqaCaptureProfile, error)
	ListPendingCheckProgressEvents(ctx context.Context, arg ListPendingCheckProgressEventsParams) ([]ListPendingCheckProgressEventsRow, error)
	ListPolicyActivationMetadata(ctx context.Context, arg ListPolicyActivationMetadataParams) ([]ListPolicyActivationMetadataRow, error)
	// One sentinel row above the in-memory bound makes overflow fail closed rather
	// than silently truncating authoritative provenance.
	ListPolicyAuthoritativeObservations(ctx context.Context, arg ListPolicyAuthoritativeObservationsParams) ([]ListPolicyAuthoritativeObservationsRow, error)
	ListPolicyRevisionMetadata(ctx context.Context, arg ListPolicyRevisionMetadataParams) ([]ListPolicyRevisionMetadataRow, error)
	ListRealtimeEvents(ctx context.Context, arg ListRealtimeEventsParams) ([]IdenqaRealtimeEvent, error)
	ListVerificationAttemptDiagnostics(ctx context.Context, arg ListVerificationAttemptDiagnosticsParams) ([]IdenqaVerificationAttemptDiagnostic, error)
	ListVerificationAttempts(ctx context.Context, arg ListVerificationAttemptsParams) ([]IdenqaVerificationAttempt, error)
	ListVerificationObservations(ctx context.Context, arg ListVerificationObservationsParams) ([]IdenqaVerificationObservation, error)
	LoadCaptureProgressPublication(ctx context.Context, arg LoadCaptureProgressPublicationParams) (LoadCaptureProgressPublicationRow, error)
	LoadRealtimeCommandAuthority(ctx context.Context, arg LoadRealtimeCommandAuthorityParams) ([]byte, error)
	LoadRealtimeReplayAuthority(ctx context.Context, arg LoadRealtimeReplayAuthorityParams) (LoadRealtimeReplayAuthorityRow, error)
	LoadRealtimeSessionAuthority(ctx context.Context, arg LoadRealtimeSessionAuthorityParams) (LoadRealtimeSessionAuthorityRow, error)
	LockActiveCaptureProfileRevision(ctx context.Context, arg LockActiveCaptureProfileRevisionParams) (LockActiveCaptureProfileRevisionRow, error)
	LockCaptureTokenForUpload(ctx context.Context, arg LockCaptureTokenForUploadParams) (IdenqaCaptureToken, error)
	LockEvidenceAssetForKeyRewrap(ctx context.Context, arg LockEvidenceAssetForKeyRewrapParams) (IdenqaEvidenceAsset, error)
	LockEvidenceGrantRedemptionID(ctx context.Context, arg LockEvidenceGrantRedemptionIDParams) (bool, error)
	LockEvidenceObjectReconciliation(ctx context.Context, arg LockEvidenceObjectReconciliationParams) (IdenqaEvidenceObjectReconciliation, error)
	LockEvidenceProcessingGrant(ctx context.Context, arg LockEvidenceProcessingGrantParams) (IdenqaEvidenceProcessingGrant, error)
	LockEvidenceUploadIntent(ctx context.Context, arg LockEvidenceUploadIntentParams) (IdenqaEvidenceUploadIntent, error)
	LockNextEvidenceObjectReconciliation(ctx context.Context, arg LockNextEvidenceObjectReconciliationParams) (IdenqaEvidenceObjectReconciliation, error)
	LockPolicy(ctx context.Context, arg LockPolicyParams) (IdenqaPolicy, error)
	LockPolicyDecision(ctx context.Context, arg LockPolicyDecisionParams) (IdenqaVerificationDecision, error)
	LockRealtimeStream(ctx context.Context, arg LockRealtimeStreamParams) (LockRealtimeStreamRow, error)
	LockVerificationCheck(ctx context.Context, arg LockVerificationCheckParams) (IdenqaVerificationCheck, error)
	LockVerificationForAuthority(ctx context.Context, arg LockVerificationForAuthorityParams) (LockVerificationForAuthorityRow, error)
	LockVerificationForUpload(ctx context.Context, arg LockVerificationForUploadParams) (IdenqaVerificationSession, error)
	MarkCheckProgressPublished(ctx context.Context, arg MarkCheckProgressPublishedParams) (int64, error)
	NotifyCheckProgress(ctx context.Context, tenantID string) error
	NotifyRealtimeEvent(ctx context.Context, arg NotifyRealtimeEventParams) error
	PublishCaptureProfileRevision(ctx context.Context, arg PublishCaptureProfileRevisionParams) (IdenqaCaptureProfileRevision, error)
	RedeemWebSocketConnectionTicket(ctx context.Context, arg RedeemWebSocketConnectionTicketParams) (IdenqaWebsocketConnectionTicket, error)
	RefreshRealtimeRetainedFrom(ctx context.Context, arg RefreshRealtimeRetainedFromParams) (int64, error)
	ResolveVerificationReconciliation(ctx context.Context, arg ResolveVerificationReconciliationParams) (int64, error)
	RetainEvidenceObjectReconciliationForAcceptance(ctx context.Context, arg RetainEvidenceObjectReconciliationForAcceptanceParams) (IdenqaEvidenceObjectReconciliation, error)
	RevokeEvidenceProcessingGrant(ctx context.Context, arg RevokeEvidenceProcessingGrantParams) (IdenqaEvidenceProcessingGrant, error)
	RewrapEvidenceAssetKey(ctx context.Context, arg RewrapEvidenceAssetKeyParams) (IdenqaEvidenceAsset, error)
	SaveAPIKeyLifecycle(ctx context.Context, arg SaveAPIKeyLifecycleParams) (int64, error)
	SaveCaptureProfile(ctx context.Context, arg SaveCaptureProfileParams) (IdenqaCaptureProfile, error)
	SaveCaptureProfileDraft(ctx context.Context, arg SaveCaptureProfileDraftParams) (IdenqaCaptureProfileRevision, error)
	SetTenantScope(ctx context.Context, tenantID string) (string, error)
	SupersedeCaptureProfileRevision(ctx context.Context, arg SupersedeCaptureProfileRevisionParams) (IdenqaCaptureProfileRevision, error)
	TransitionEvidenceAsset(ctx context.Context, arg TransitionEvidenceAssetParams) (IdenqaEvidenceAsset, error)
	TransitionEvidenceObjectReconciliation(ctx context.Context, arg TransitionEvidenceObjectReconciliationParams) (IdenqaEvidenceObjectReconciliation, error)
	TransitionEvidenceUploadIntent(ctx context.Context, arg TransitionEvidenceUploadIntentParams) (IdenqaEvidenceUploadIntent, error)
	TransitionProcessingAuthority(ctx context.Context, arg TransitionProcessingAuthorityParams) (IdenqaProcessingAuthority, error)
	TryIdempotencyLock(ctx context.Context, arg TryIdempotencyLockParams) (bool, error)
	UpdateVerificationCheck(ctx context.Context, arg UpdateVerificationCheckParams) (int64, error)
	UpsertRealtimeAcknowledgement(ctx context.Context, arg UpsertRealtimeAcknowledgementParams) (int64, error)
	WithdrawCaptureProfileRevision(ctx context.Context, arg WithdrawCaptureProfileRevisionParams) (IdenqaCaptureProfileRevision, error)
}

var _ Querier = (*Queries)(nil)
