// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: realtime.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRealtimeStream = `-- name: AdvanceRealtimeStream :one
UPDATE idenqa.realtime_streams
SET latest_cursor = latest_cursor + 1,
    latest_expires_at = $1,
    updated_at = $2
WHERE tenant_id = $3
  AND verification_id = $4
RETURNING latest_cursor
`

type AdvanceRealtimeStreamParams struct {
	ExpiresAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TenantID       string
	VerificationID string
}

func (q *Queries) AdvanceRealtimeStream(ctx context.Context, arg AdvanceRealtimeStreamParams) (int64, error) {
	row := q.db.QueryRow(ctx, advanceRealtimeStream,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.TenantID,
		arg.VerificationID,
	)
	var latest_cursor int64
	err := row.Scan(&latest_cursor)
	return latest_cursor, err
}

const createWebSocketConnectionTicket = `-- name: CreateWebSocketConnectionTicket :execrows
WITH active_authority AS MATERIALIZED (
    SELECT tokens.id
    FROM idenqa.capture_tokens AS tokens
    JOIN idenqa.verification_sessions AS sessions
      ON sessions.tenant_id = tokens.tenant_id
     AND sessions.id = tokens.verification_id
    WHERE tokens.tenant_id = $2
      AND tokens.id = $4
      AND tokens.verification_id = $3
      AND tokens.revoked_at IS NULL
      AND tokens.issued_at <= $10
      AND tokens.expires_at >= $11
      AND sessions.state = 'collecting'
      AND sessions.created_at <= $10
      AND sessions.expires_at >= $11
    FOR SHARE OF tokens, sessions
)
INSERT INTO idenqa.websocket_connection_tickets (
    id, tenant_id, verification_id, capture_token_id, digest, digest_version,
    client_kind, client_identity, region, protocol, issued_at, expires_at,
    redeemed_at, connection_id
)
SELECT
    $1, $2, $3,
    $4, $5, 1,
    $6, $7, $8,
    $9, $10, $11, NULL, NULL
FROM active_authority
`

type CreateWebSocketConnectionTicketParams struct {
	ID             string
	TenantID       string
	VerificationID string
	CaptureTokenID string
	Digest         []byte
	ClientKind     string
	ClientIdentity string
	Region         string
	Protocol       string
	IssuedAt       pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateWebSocketConnectionTicket(ctx context.Context, arg CreateWebSocketConnectionTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, createWebSocketConnectionTicket,
		arg.ID,
		arg.TenantID,
		arg.VerificationID,
		arg.CaptureTokenID,
		arg.Digest,
		arg.ClientKind,
		arg.ClientIdentity,
		arg.Region,
		arg.Protocol,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRealtimeEvents = `-- name: DeleteExpiredRealtimeEvents :many
WITH expired AS MATERIALIZED (
    SELECT events.tenant_id, events.verification_id, events.cursor
    FROM idenqa.realtime_events AS events
    WHERE events.tenant_id = $1
      AND events.expires_at <= $2
    ORDER BY events.expires_at, events.verification_id, events.cursor
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
DELETE FROM idenqa.realtime_events AS events
USING expired
WHERE events.tenant_id = expired.tenant_id
  AND events.verification_id = expired.verification_id
  AND events.cursor = expired.cursor
RETURNING events.verification_id
`

type DeleteExpiredRealtimeEventsParams struct {
	TenantID   string
	ObservedAt pgtype.Timestamptz
	BatchSize  int32
}

func (q *Queries) DeleteExpiredRealtimeEvents(ctx context.Context, arg DeleteExpiredRealtimeEventsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteExpiredRealtimeEvents, arg.TenantID, arg.ObservedAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var verification_id string
		if err := rows.Scan(&verification_id); err != nil {
			return nil, err
		}
		items = append(items, verification_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredUnredeemedWebSocketTickets = `-- name: DeleteExpiredUnredeemedWebSocketTickets :many
WITH expired AS MATERIALIZED (
    SELECT candidate.id
    FROM idenqa.websocket_connection_tickets AS candidate
    WHERE candidate.tenant_id = $1
      AND candidate.redeemed_at IS NULL
      AND candidate.expires_at <= $2
    ORDER BY candidate.expires_at, candidate.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
DELETE FROM idenqa.websocket_connection_tickets AS tickets
USING expired
WHERE tickets.tenant_id = $1
  AND tickets.id = expired.id
RETURNING tickets.id
`

type DeleteExpiredUnredeemedWebSocketTicketsParams struct {
	TenantID   string
	ObservedAt pgtype.Timestamptz
	BatchSize  int32
}

func (q *Queries) DeleteExpiredUnredeemedWebSocketTickets(ctx context.Context, arg DeleteExpiredUnredeemedWebSocketTicketsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteExpiredUnredeemedWebSocketTickets, arg.TenantID, arg.ObservedAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureRealtimeStream = `-- name: EnsureRealtimeStream :execrows
INSERT INTO idenqa.realtime_streams (
    tenant_id, verification_id, latest_cursor, latest_expires_at, retained_from_cursor, updated_at
) VALUES (
    $1, $2, 0, NULL, 1, $3
)
ON CONFLICT (tenant_id, verification_id) DO NOTHING
`

type EnsureRealtimeStreamParams struct {
	TenantID       string
	VerificationID string
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) EnsureRealtimeStream(ctx context.Context, arg EnsureRealtimeStreamParams) (int64, error) {
	result, err := q.db.Exec(ctx, ensureRealtimeStream, arg.TenantID, arg.VerificationID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findRealtimeClientCommand = `-- name: FindRealtimeClientCommand :one
SELECT command_id, tenant_id, verification_id, capture_token_id, request_fingerprint, message_type, step_state, requirement_key, artefact, acquisition_method, result_code, disposition, rejection_code, occurred_at, received_at
FROM idenqa.realtime_client_commands
WHERE tenant_id = $1
  AND command_id = $2
`

type FindRealtimeClientCommandParams struct {
	TenantID  string
	CommandID string
}

func (q *Queries) FindRealtimeClientCommand(ctx context.Context, arg FindRealtimeClientCommandParams) (IdenqaRealtimeClientCommand, error) {
	row := q.db.QueryRow(ctx, findRealtimeClientCommand, arg.TenantID, arg.CommandID)
	var i IdenqaRealtimeClientCommand
	err := row.Scan(
		&i.CommandID,
		&i.TenantID,
		&i.VerificationID,
		&i.CaptureTokenID,
		&i.RequestFingerprint,
		&i.MessageType,
		&i.StepState,
		&i.RequirementKey,
		&i.Artefact,
		&i.AcquisitionMethod,
		&i.ResultCode,
		&i.Disposition,
		&i.RejectionCode,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const findRealtimeEventByID = `-- name: FindRealtimeEventByID :one
SELECT event_id, tenant_id, verification_id, cursor, message_type, command_id, correlation_id, causation_id, payload, occurred_at, expires_at
FROM idenqa.realtime_events
WHERE tenant_id = $1
  AND event_id = $2
`

type FindRealtimeEventByIDParams struct {
	TenantID string
	EventID  string
}

func (q *Queries) FindRealtimeEventByID(ctx context.Context, arg FindRealtimeEventByIDParams) (IdenqaRealtimeEvent, error) {
	row := q.db.QueryRow(ctx, findRealtimeEventByID, arg.TenantID, arg.EventID)
	var i IdenqaRealtimeEvent
	err := row.Scan(
		&i.EventID,
		&i.TenantID,
		&i.VerificationID,
		&i.Cursor,
		&i.MessageType,
		&i.CommandID,
		&i.CorrelationID,
		&i.CausationID,
		&i.Payload,
		&i.OccurredAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertRealtimeClientCommand = `-- name: InsertRealtimeClientCommand :execrows
INSERT INTO idenqa.realtime_client_commands (
    command_id, tenant_id, verification_id, capture_token_id,
    request_fingerprint, message_type, step_state, requirement_key,
    artefact, acquisition_method, result_code, disposition, rejection_code,
    occurred_at, received_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13,
    $14, $15
)
ON CONFLICT (command_id) DO NOTHING
`

type InsertRealtimeClientCommandParams struct {
	CommandID          string
	TenantID           string
	VerificationID     string
	CaptureTokenID     string
	RequestFingerprint []byte
	MessageType        string
	StepState          string
	RequirementKey     string
	Artefact           string
	AcquisitionMethod  string
	ResultCode         *string
	Disposition        string
	RejectionCode      *string
	OccurredAt         pgtype.Timestamptz
	ReceivedAt         pgtype.Timestamptz
}

func (q *Queries) InsertRealtimeClientCommand(ctx context.Context, arg InsertRealtimeClientCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRealtimeClientCommand,
		arg.CommandID,
		arg.TenantID,
		arg.VerificationID,
		arg.CaptureTokenID,
		arg.RequestFingerprint,
		arg.MessageType,
		arg.StepState,
		arg.RequirementKey,
		arg.Artefact,
		arg.AcquisitionMethod,
		arg.ResultCode,
		arg.Disposition,
		arg.RejectionCode,
		arg.OccurredAt,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRealtimeEvent = `-- name: InsertRealtimeEvent :exec
INSERT INTO idenqa.realtime_events (
    event_id, tenant_id, verification_id, cursor, message_type, command_id,
    correlation_id, causation_id, payload, occurred_at, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
`

type InsertRealtimeEventParams struct {
	EventID        string
	TenantID       string
	VerificationID string
	Cursor         int64
	MessageType    string
	CommandID      *string
	CorrelationID  *string
	CausationID    *string
	Payload        []byte
	OccurredAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) InsertRealtimeEvent(ctx context.Context, arg InsertRealtimeEventParams) error {
	_, err := q.db.Exec(ctx, insertRealtimeEvent,
		arg.EventID,
		arg.TenantID,
		arg.VerificationID,
		arg.Cursor,
		arg.MessageType,
		arg.CommandID,
		arg.CorrelationID,
		arg.CausationID,
		arg.Payload,
		arg.OccurredAt,
		arg.ExpiresAt,
	)
	return err
}

const listRealtimeEvents = `-- name: ListRealtimeEvents :many
SELECT event_id, tenant_id, verification_id, cursor, message_type, command_id, correlation_id, causation_id, payload, occurred_at, expires_at
FROM idenqa.realtime_events
WHERE tenant_id = $1
  AND verification_id = $2
  AND cursor > $3
  AND expires_at > $4
ORDER BY cursor
LIMIT $5
`

type ListRealtimeEventsParams struct {
	TenantID       string
	VerificationID string
	AfterCursor    int64
	ObservedAt     pgtype.Timestamptz
	PageSize       int32
}

func (q *Queries) ListRealtimeEvents(ctx context.Context, arg ListRealtimeEventsParams) ([]IdenqaRealtimeEvent, error) {
	rows, err := q.db.Query(ctx, listRealtimeEvents,
		arg.TenantID,
		arg.VerificationID,
		arg.AfterCursor,
		arg.ObservedAt,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdenqaRealtimeEvent
	for rows.Next() {
		var i IdenqaRealtimeEvent
		if err := rows.Scan(
			&i.EventID,
			&i.TenantID,
			&i.VerificationID,
			&i.Cursor,
			&i.MessageType,
			&i.CommandID,
			&i.CorrelationID,
			&i.CausationID,
			&i.Payload,
			&i.OccurredAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRealtimeCommandAuthority = `-- name: LoadRealtimeCommandAuthority :one
SELECT sessions.requirements
FROM idenqa.websocket_connection_tickets AS tickets
JOIN idenqa.capture_tokens AS tokens
  ON tokens.tenant_id = tickets.tenant_id
 AND tokens.id = tickets.capture_token_id
 AND tokens.verification_id = tickets.verification_id
JOIN idenqa.verification_sessions AS sessions
  ON sessions.tenant_id = tickets.tenant_id
 AND sessions.id = tickets.verification_id
WHERE tickets.tenant_id = $1
  AND tickets.id = $2
  AND tickets.verification_id = $3
  AND tickets.capture_token_id = $4
  AND tickets.connection_id = $5
  AND tickets.redeemed_at IS NOT NULL
  AND sessions.state = 'collecting'
  AND sessions.created_at <= $6
  AND sessions.expires_at > $6
  AND tokens.revoked_at IS NULL
  AND tokens.issued_at <= $6
  AND tokens.expires_at > $6
FOR SHARE OF sessions, tokens
`

type LoadRealtimeCommandAuthorityParams struct {
	TenantID       string
	TicketID       string
	VerificationID string
	CaptureTokenID string
	ConnectionID   *string
	ObservedAt     pgtype.Timestamptz
}

func (q *Queries) LoadRealtimeCommandAuthority(ctx context.Context, arg LoadRealtimeCommandAuthorityParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadRealtimeCommandAuthority,
		arg.TenantID,
		arg.TicketID,
		arg.VerificationID,
		arg.CaptureTokenID,
		arg.ConnectionID,
		arg.ObservedAt,
	)
	var requirements []byte
	err := row.Scan(&requirements)
	return requirements, err
}

const loadRealtimeReplayAuthority = `-- name: LoadRealtimeReplayAuthority :one
SELECT
    COALESCE(streams.latest_cursor, 0)::bigint AS latest_cursor,
    CASE
        WHEN streams.latest_cursor IS NULL THEN 1
        ELSE GREATEST(
            streams.retained_from_cursor,
            COALESCE(
                (
                    SELECT MIN(events.cursor)
                    FROM idenqa.realtime_events AS events
                    WHERE events.tenant_id = tickets.tenant_id
                      AND events.verification_id = tickets.verification_id
                      AND events.expires_at > $1
                ),
                streams.latest_cursor + 1
            )
        )
    END::bigint AS retained_from_cursor,
    COALESCE(acknowledgements.acknowledged_cursor, 0)::bigint AS acknowledged_cursor
FROM idenqa.websocket_connection_tickets AS tickets
JOIN idenqa.capture_tokens AS tokens
  ON tokens.tenant_id = tickets.tenant_id
 AND tokens.id = tickets.capture_token_id
 AND tokens.verification_id = tickets.verification_id
JOIN idenqa.verification_sessions AS sessions
  ON sessions.tenant_id = tickets.tenant_id
 AND sessions.id = tickets.verification_id
LEFT JOIN idenqa.realtime_streams AS streams
  ON streams.tenant_id = tickets.tenant_id
 AND streams.verification_id = tickets.verification_id
LEFT JOIN idenqa.realtime_acknowledgements AS acknowledgements
  ON acknowledgements.tenant_id = tickets.tenant_id
 AND acknowledgements.verification_id = tickets.verification_id
 AND acknowledgements.capture_token_id = tickets.capture_token_id
WHERE tickets.tenant_id = $2
  AND tickets.id = $3
  AND tickets.verification_id = $4
  AND tickets.capture_token_id = $5
  AND tickets.connection_id = $6
  AND tickets.redeemed_at IS NOT NULL
  AND sessions.created_at <= $1
  AND sessions.expires_at > $1
  AND tokens.revoked_at IS NULL
  AND tokens.issued_at <= $1
  AND tokens.expires_at > $1
`

type LoadRealtimeReplayAuthorityParams struct {
	ObservedAt     pgtype.Timestamptz
	TenantID       string
	TicketID       string
	VerificationID string
	CaptureTokenID string
	ConnectionID   *string
}

type LoadRealtimeReplayAuthorityRow struct {
	LatestCursor       int64
	RetainedFromCursor int64
	AcknowledgedCursor int64
}

func (q *Queries) LoadRealtimeReplayAuthority(ctx context.Context, arg LoadRealtimeReplayAuthorityParams) (LoadRealtimeReplayAuthorityRow, error) {
	row := q.db.QueryRow(ctx, loadRealtimeReplayAuthority,
		arg.ObservedAt,
		arg.TenantID,
		arg.TicketID,
		arg.VerificationID,
		arg.CaptureTokenID,
		arg.ConnectionID,
	)
	var i LoadRealtimeReplayAuthorityRow
	err := row.Scan(&i.LatestCursor, &i.RetainedFromCursor, &i.AcknowledgedCursor)
	return i, err
}

const loadRealtimeSessionAuthority = `-- name: LoadRealtimeSessionAuthority :one
SELECT
    sessions.version AS session_version,
    sessions.expires_at AS session_expires_at
FROM idenqa.websocket_connection_tickets AS tickets
JOIN idenqa.capture_tokens AS tokens
  ON tokens.tenant_id = tickets.tenant_id
 AND tokens.id = tickets.capture_token_id
 AND tokens.verification_id = tickets.verification_id
JOIN idenqa.verification_sessions AS sessions
  ON sessions.tenant_id = tickets.tenant_id
 AND sessions.id = tickets.verification_id
WHERE tickets.tenant_id = $1
  AND tickets.id = $2
  AND tickets.verification_id = $3
  AND tickets.capture_token_id = $4
  AND tickets.connection_id = $5
  AND tickets.redeemed_at IS NOT NULL
  AND sessions.state = 'collecting'
  AND sessions.created_at <= $6
  AND sessions.expires_at > $6
  AND tokens.revoked_at IS NULL
  AND tokens.issued_at <= $6
  AND tokens.expires_at > $6
`

type LoadRealtimeSessionAuthorityParams struct {
	TenantID       string
	TicketID       string
	VerificationID string
	CaptureTokenID string
	ConnectionID   *string
	ObservedAt     pgtype.Timestamptz
}

type LoadRealtimeSessionAuthorityRow struct {
	SessionVersion   int64
	SessionExpiresAt pgtype.Timestamptz
}

func (q *Queries) LoadRealtimeSessionAuthority(ctx context.Context, arg LoadRealtimeSessionAuthorityParams) (LoadRealtimeSessionAuthorityRow, error) {
	row := q.db.QueryRow(ctx, loadRealtimeSessionAuthority,
		arg.TenantID,
		arg.TicketID,
		arg.VerificationID,
		arg.CaptureTokenID,
		arg.ConnectionID,
		arg.ObservedAt,
	)
	var i LoadRealtimeSessionAuthorityRow
	err := row.Scan(&i.SessionVersion, &i.SessionExpiresAt)
	return i, err
}

const lockRealtimeStream = `-- name: LockRealtimeStream :one
SELECT latest_cursor, latest_expires_at, retained_from_cursor
FROM idenqa.realtime_streams
WHERE tenant_id = $1
  AND verification_id = $2
FOR UPDATE
`

type LockRealtimeStreamParams struct {
	TenantID       string
	VerificationID string
}

type LockRealtimeStreamRow struct {
	LatestCursor       int64
	LatestExpiresAt    pgtype.Timestamptz
	RetainedFromCursor int64
}

func (q *Queries) LockRealtimeStream(ctx context.Context, arg LockRealtimeStreamParams) (LockRealtimeStreamRow, error) {
	row := q.db.QueryRow(ctx, lockRealtimeStream, arg.TenantID, arg.VerificationID)
	var i LockRealtimeStreamRow
	err := row.Scan(&i.LatestCursor, &i.LatestExpiresAt, &i.RetainedFromCursor)
	return i, err
}

const notifyRealtimeEvent = `-- name: NotifyRealtimeEvent :exec
SELECT pg_notify(
    'idenqa_realtime_v1',
    $1::text || ':' || $2::text
)
`

type NotifyRealtimeEventParams struct {
	TenantID       string
	VerificationID string
}

func (q *Queries) NotifyRealtimeEvent(ctx context.Context, arg NotifyRealtimeEventParams) error {
	_, err := q.db.Exec(ctx, notifyRealtimeEvent, arg.TenantID, arg.VerificationID)
	return err
}

const redeemWebSocketConnectionTicket = `-- name: RedeemWebSocketConnectionTicket :one
WITH active_authority AS MATERIALIZED (
    SELECT tokens.id
    FROM idenqa.capture_tokens AS tokens
    JOIN idenqa.verification_sessions AS sessions
      ON sessions.tenant_id = tokens.tenant_id
     AND sessions.id = tokens.verification_id
    JOIN idenqa.websocket_connection_tickets AS bound_ticket
      ON bound_ticket.tenant_id = tokens.tenant_id
     AND bound_ticket.capture_token_id = tokens.id
     AND bound_ticket.verification_id = sessions.id
    WHERE bound_ticket.tenant_id = $3
      AND bound_ticket.id = $4
      AND tokens.revoked_at IS NULL
      AND tokens.issued_at <= $1
      AND tokens.expires_at > $1
      AND sessions.state = 'collecting'
      AND sessions.created_at <= $1
      AND sessions.expires_at > $1
    FOR SHARE OF tokens, sessions
)
UPDATE idenqa.websocket_connection_tickets AS tickets
SET redeemed_at = $1,
    connection_id = $2
WHERE tickets.tenant_id = $3
  AND tickets.id = $4
  AND tickets.digest = $5
  AND tickets.digest_version = 1
  AND tickets.client_kind = $6
  AND tickets.client_identity = $7
  AND tickets.region = $8
  AND tickets.protocol = $9
  AND tickets.redeemed_at IS NULL
  AND tickets.connection_id IS NULL
  AND tickets.issued_at <= $1
  AND tickets.expires_at > $1
  AND EXISTS (SELECT 1 FROM active_authority)
RETURNING id, tenant_id, verification_id, capture_token_id, digest, digest_version, client_kind, client_identity, region, protocol, issued_at, expires_at, redeemed_at, connection_id
`

type RedeemWebSocketConnectionTicketParams struct {
	RedeemedAt     pgtype.Timestamptz
	ConnectionID   *string
	TenantID       string
	ID             string
	Digest         []byte
	ClientKind     string
	ClientIdentity string
	Region         string
	Protocol       string
}

func (q *Queries) RedeemWebSocketConnectionTicket(ctx context.Context, arg RedeemWebSocketConnectionTicketParams) (IdenqaWebsocketConnectionTicket, error) {
	row := q.db.QueryRow(ctx, redeemWebSocketConnectionTicket,
		arg.RedeemedAt,
		arg.ConnectionID,
		arg.TenantID,
		arg.ID,
		arg.Digest,
		arg.ClientKind,
		arg.ClientIdentity,
		arg.Region,
		arg.Protocol,
	)
	var i IdenqaWebsocketConnectionTicket
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VerificationID,
		&i.CaptureTokenID,
		&i.Digest,
		&i.DigestVersion,
		&i.ClientKind,
		&i.ClientIdentity,
		&i.Region,
		&i.Protocol,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.ConnectionID,
	)
	return i, err
}

const refreshRealtimeRetainedFrom = `-- name: RefreshRealtimeRetainedFrom :execrows
UPDATE idenqa.realtime_streams AS streams
SET retained_from_cursor = COALESCE(
        (
            SELECT MIN(events.cursor)
            FROM idenqa.realtime_events AS events
            WHERE events.tenant_id = streams.tenant_id
              AND events.verification_id = streams.verification_id
        ),
        streams.latest_cursor + 1
    ),
    updated_at = $1
WHERE streams.tenant_id = $2
  AND streams.verification_id = $3
`

type RefreshRealtimeRetainedFromParams struct {
	UpdatedAt      pgtype.Timestamptz
	TenantID       string
	VerificationID string
}

func (q *Queries) RefreshRealtimeRetainedFrom(ctx context.Context, arg RefreshRealtimeRetainedFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, refreshRealtimeRetainedFrom, arg.UpdatedAt, arg.TenantID, arg.VerificationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRealtimeAcknowledgement = `-- name: UpsertRealtimeAcknowledgement :execrows
INSERT INTO idenqa.realtime_acknowledgements (
    tenant_id, verification_id, capture_token_id, acknowledged_cursor, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5
)
ON CONFLICT (tenant_id, verification_id, capture_token_id) DO UPDATE
SET acknowledged_cursor = GREATEST(
        idenqa.realtime_acknowledgements.acknowledged_cursor,
        EXCLUDED.acknowledged_cursor
    ),
    updated_at = CASE
        WHEN EXCLUDED.acknowledged_cursor > idenqa.realtime_acknowledgements.acknowledged_cursor
            THEN EXCLUDED.updated_at
        ELSE idenqa.realtime_acknowledgements.updated_at
    END
`

type UpsertRealtimeAcknowledgementParams struct {
	TenantID           string
	VerificationID     string
	CaptureTokenID     string
	AcknowledgedCursor int64
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpsertRealtimeAcknowledgement(ctx context.Context, arg UpsertRealtimeAcknowledgementParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRealtimeAcknowledgement,
		arg.TenantID,
		arg.VerificationID,
		arg.CaptureTokenID,
		arg.AcknowledgedCursor,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
