// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO idenqa.tenants (id, state, version, created_at, updated_at, disabled_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTenantParams struct {
	ID         string
	State      string
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.ID,
		arg.State,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DisabledAt,
	)
	return err
}

const disableTenant = `-- name: DisableTenant :one
UPDATE idenqa.tenants
SET state = 'disabled', version = version + 1, updated_at = $3, disabled_at = $3
WHERE id = $1 AND version = $2 AND state = 'active'
RETURNING id, state, version, created_at, updated_at, disabled_at
`

type DisableTenantParams struct {
	ID        string
	Version   int64
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) DisableTenant(ctx context.Context, arg DisableTenantParams) (IdenqaTenant, error) {
	row := q.db.QueryRow(ctx, disableTenant, arg.ID, arg.Version, arg.UpdatedAt)
	var i IdenqaTenant
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const findTenant = `-- name: FindTenant :one
SELECT id, state, version, created_at, updated_at, disabled_at
FROM idenqa.tenants
WHERE id = $1
`

func (q *Queries) FindTenant(ctx context.Context, id string) (IdenqaTenant, error) {
	row := q.db.QueryRow(ctx, findTenant, id)
	var i IdenqaTenant
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const insertTenantAdminAudit = `-- name: InsertTenantAdminAudit :exec
INSERT INTO idenqa.tenant_admin_audit (tenant_id, action, actor, reason, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertTenantAdminAuditParams struct {
	TenantID   string
	Action     string
	Actor      string
	Reason     string
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) InsertTenantAdminAudit(ctx context.Context, arg InsertTenantAdminAuditParams) error {
	_, err := q.db.Exec(ctx, insertTenantAdminAudit,
		arg.TenantID,
		arg.Action,
		arg.Actor,
		arg.Reason,
		arg.OccurredAt,
	)
	return err
}

const setTenantScope = `-- name: SetTenantScope :one
SELECT set_config('idenqa.tenant_id', $1, true)
`

func (q *Queries) SetTenantScope(ctx context.Context, tenantID string) (string, error) {
	row := q.db.QueryRow(ctx, setTenantScope, tenantID)
	var set_config string
	err := row.Scan(&set_config)
	return set_config, err
}
