// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_execution.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimVerificationReconciliation = `-- name: ClaimVerificationReconciliation :one
WITH candidate AS (
    SELECT check_id, attempt_id, reason
    FROM idenqa.verification_reconciliations
    WHERE tenant_id = $4
      AND available_at <= $3
      AND (status = 'pending' OR (status = 'claimed' AND lease_expires_at <= $3))
    ORDER BY available_at, created_at, check_id, attempt_id, reason
    LIMIT 1 FOR UPDATE SKIP LOCKED
)
UPDATE idenqa.verification_reconciliations AS reconciliations
SET status = 'claimed', claim_token = $1, lease_expires_at = $2,
    claim_count = claim_count + 1, updated_at = $3
FROM candidate
WHERE reconciliations.tenant_id = $4
  AND reconciliations.check_id = candidate.check_id
  AND reconciliations.attempt_id = candidate.attempt_id
  AND reconciliations.reason = candidate.reason
RETURNING reconciliations.tenant_id, reconciliations.verification_id, reconciliations.check_id, reconciliations.attempt_id, reconciliations.reason, reconciliations.status, reconciliations.claim_token, reconciliations.lease_expires_at, reconciliations.claim_count, reconciliations.available_at, reconciliations.created_at, reconciliations.updated_at, reconciliations.resolved_at
`

type ClaimVerificationReconciliationParams struct {
	ClaimToken     *string
	LeaseExpiresAt pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	TenantID       string
}

func (q *Queries) ClaimVerificationReconciliation(ctx context.Context, arg ClaimVerificationReconciliationParams) (IdenqaVerificationReconciliation, error) {
	row := q.db.QueryRow(ctx, claimVerificationReconciliation,
		arg.ClaimToken,
		arg.LeaseExpiresAt,
		arg.ClaimedAt,
		arg.TenantID,
	)
	var i IdenqaVerificationReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.VerificationID,
		&i.CheckID,
		&i.AttemptID,
		&i.Reason,
		&i.Status,
		&i.ClaimToken,
		&i.LeaseExpiresAt,
		&i.ClaimCount,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const claimVerificationReconciliationForAttempt = `-- name: ClaimVerificationReconciliationForAttempt :one
UPDATE idenqa.verification_reconciliations
SET status = 'claimed', claim_token = $1,
    lease_expires_at = $2, claim_count = claim_count + 1,
    updated_at = $3
WHERE tenant_id = $4
  AND check_id = $5
  AND attempt_id = $6
  AND available_at <= $3
  AND (
      status = 'pending' OR
      (status = 'claimed' AND lease_expires_at <= $3)
  )
RETURNING tenant_id, verification_id, check_id, attempt_id, reason, status, claim_token, lease_expires_at, claim_count, available_at, created_at, updated_at, resolved_at
`

type ClaimVerificationReconciliationForAttemptParams struct {
	ClaimToken     *string
	LeaseExpiresAt pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	TenantID       string
	CheckID        string
	AttemptID      string
}

func (q *Queries) ClaimVerificationReconciliationForAttempt(ctx context.Context, arg ClaimVerificationReconciliationForAttemptParams) (IdenqaVerificationReconciliation, error) {
	row := q.db.QueryRow(ctx, claimVerificationReconciliationForAttempt,
		arg.ClaimToken,
		arg.LeaseExpiresAt,
		arg.ClaimedAt,
		arg.TenantID,
		arg.CheckID,
		arg.AttemptID,
	)
	var i IdenqaVerificationReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.VerificationID,
		&i.CheckID,
		&i.AttemptID,
		&i.Reason,
		&i.Status,
		&i.ClaimToken,
		&i.LeaseExpiresAt,
		&i.ClaimCount,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const claimVerificationResultInbox = `-- name: ClaimVerificationResultInbox :execrows
INSERT INTO idenqa.verification_result_inbox (
    tenant_id, verification_id, check_id, attempt_id, result_digest, received_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT DO NOTHING
`

type ClaimVerificationResultInboxParams struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	ResultDigest   string
	ReceivedAt     pgtype.Timestamptz
}

func (q *Queries) ClaimVerificationResultInbox(ctx context.Context, arg ClaimVerificationResultInboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimVerificationResultInbox,
		arg.TenantID,
		arg.VerificationID,
		arg.CheckID,
		arg.AttemptID,
		arg.ResultDigest,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeVerificationAttempt = `-- name: CompleteVerificationAttempt :execrows
UPDATE idenqa.verification_attempts
SET state = $1, finished_at = $2,
    failure_class = $3, failure_code = $4,
    retry_disposition = $5,
    retry_after_milliseconds = $6, result_digest = $7
WHERE tenant_id = $8 AND id = $9 AND check_id = $10
  AND fence = $11 AND state = 'running'
`

type CompleteVerificationAttemptParams struct {
	State                  string
	FinishedAt             pgtype.Timestamptz
	FailureClass           *string
	FailureCode            *string
	RetryDisposition       *string
	RetryAfterMilliseconds *int64
	ResultDigest           *string
	TenantID               string
	ID                     string
	CheckID                string
	Fence                  int64
}

func (q *Queries) CompleteVerificationAttempt(ctx context.Context, arg CompleteVerificationAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeVerificationAttempt,
		arg.State,
		arg.FinishedAt,
		arg.FailureClass,
		arg.FailureCode,
		arg.RetryDisposition,
		arg.RetryAfterMilliseconds,
		arg.ResultDigest,
		arg.TenantID,
		arg.ID,
		arg.CheckID,
		arg.Fence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findVerificationCheck = `-- name: FindVerificationCheck :one
SELECT id, tenant_id, verification_id, name, state, outcome, version, created_at, updated_at FROM idenqa.verification_checks
WHERE tenant_id = $1 AND id = $2
`

type FindVerificationCheckParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindVerificationCheck(ctx context.Context, arg FindVerificationCheckParams) (IdenqaVerificationCheck, error) {
	row := q.db.QueryRow(ctx, findVerificationCheck, arg.TenantID, arg.ID)
	var i IdenqaVerificationCheck
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VerificationID,
		&i.Name,
		&i.State,
		&i.Outcome,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findVerificationReconciliationForAttempt = `-- name: FindVerificationReconciliationForAttempt :one
SELECT tenant_id, verification_id, check_id, attempt_id, reason, status, claim_token, lease_expires_at, claim_count, available_at, created_at, updated_at, resolved_at
FROM idenqa.verification_reconciliations
WHERE tenant_id = $1
  AND check_id = $2
  AND attempt_id = $3
`

type FindVerificationReconciliationForAttemptParams struct {
	TenantID  string
	CheckID   string
	AttemptID string
}

func (q *Queries) FindVerificationReconciliationForAttempt(ctx context.Context, arg FindVerificationReconciliationForAttemptParams) (IdenqaVerificationReconciliation, error) {
	row := q.db.QueryRow(ctx, findVerificationReconciliationForAttempt, arg.TenantID, arg.CheckID, arg.AttemptID)
	var i IdenqaVerificationReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.VerificationID,
		&i.CheckID,
		&i.AttemptID,
		&i.Reason,
		&i.Status,
		&i.ClaimToken,
		&i.LeaseExpiresAt,
		&i.ClaimCount,
		&i.AvailableAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertVerificationAttempt = `-- name: InsertVerificationAttempt :execrows
INSERT INTO idenqa.verification_attempts (
    id, tenant_id, verification_id, check_id, attempt_number, fence, runner_kind,
    runner_id, runner_version, package_digest, contract_major, contract_minor,
    request_digest, configuration_digest, state, started_at, deadline, finished_at,
    failure_class, failure_code, retry_disposition, retry_after_milliseconds, result_digest
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21,
    $22, $23
)
ON CONFLICT (tenant_id, id) DO NOTHING
`

type InsertVerificationAttemptParams struct {
	ID                     string
	TenantID               string
	VerificationID         string
	CheckID                string
	AttemptNumber          int32
	Fence                  int64
	RunnerKind             string
	RunnerID               string
	RunnerVersion          string
	PackageDigest          string
	ContractMajor          int32
	ContractMinor          int32
	RequestDigest          string
	ConfigurationDigest    string
	State                  string
	StartedAt              pgtype.Timestamptz
	Deadline               pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	FailureClass           *string
	FailureCode            *string
	RetryDisposition       *string
	RetryAfterMilliseconds *int64
	ResultDigest           *string
}

func (q *Queries) InsertVerificationAttempt(ctx context.Context, arg InsertVerificationAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVerificationAttempt,
		arg.ID,
		arg.TenantID,
		arg.VerificationID,
		arg.CheckID,
		arg.AttemptNumber,
		arg.Fence,
		arg.RunnerKind,
		arg.RunnerID,
		arg.RunnerVersion,
		arg.PackageDigest,
		arg.ContractMajor,
		arg.ContractMinor,
		arg.RequestDigest,
		arg.ConfigurationDigest,
		arg.State,
		arg.StartedAt,
		arg.Deadline,
		arg.FinishedAt,
		arg.FailureClass,
		arg.FailureCode,
		arg.RetryDisposition,
		arg.RetryAfterMilliseconds,
		arg.ResultDigest,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertVerificationAttemptDiagnostic = `-- name: InsertVerificationAttemptDiagnostic :execrows
INSERT INTO idenqa.verification_attempt_diagnostics (
    tenant_id, verification_id, check_id, attempt_id, kind, code, recorded_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
ON CONFLICT DO NOTHING
`

type InsertVerificationAttemptDiagnosticParams struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	Kind           string
	Code           string
	RecordedAt     pgtype.Timestamptz
}

func (q *Queries) InsertVerificationAttemptDiagnostic(ctx context.Context, arg InsertVerificationAttemptDiagnosticParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVerificationAttemptDiagnostic,
		arg.TenantID,
		arg.VerificationID,
		arg.CheckID,
		arg.AttemptID,
		arg.Kind,
		arg.Code,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertVerificationCheck = `-- name: InsertVerificationCheck :exec
INSERT INTO idenqa.verification_checks (
    id, tenant_id, verification_id, name, state, outcome, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
`

type InsertVerificationCheckParams struct {
	ID             string
	TenantID       string
	VerificationID string
	Name           string
	State          string
	Outcome        *string
	Version        int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertVerificationCheck(ctx context.Context, arg InsertVerificationCheckParams) error {
	_, err := q.db.Exec(ctx, insertVerificationCheck,
		arg.ID,
		arg.TenantID,
		arg.VerificationID,
		arg.Name,
		arg.State,
		arg.Outcome,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVerificationObservation = `-- name: InsertVerificationObservation :exec
INSERT INTO idenqa.verification_observations (
    id, tenant_id, verification_id, check_id, attempt_id, runner_kind,
    runner_id, runner_version, package_digest, contract_major, contract_minor,
    request_digest, configuration_digest, signal_name, signal_outcome, reason_codes, recorded_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17
)
`

type InsertVerificationObservationParams struct {
	ID                  string
	TenantID            string
	VerificationID      string
	CheckID             string
	AttemptID           string
	RunnerKind          string
	RunnerID            string
	RunnerVersion       string
	PackageDigest       string
	ContractMajor       int32
	ContractMinor       int32
	RequestDigest       string
	ConfigurationDigest string
	SignalName          string
	SignalOutcome       string
	ReasonCodes         []string
	RecordedAt          pgtype.Timestamptz
}

func (q *Queries) InsertVerificationObservation(ctx context.Context, arg InsertVerificationObservationParams) error {
	_, err := q.db.Exec(ctx, insertVerificationObservation,
		arg.ID,
		arg.TenantID,
		arg.VerificationID,
		arg.CheckID,
		arg.AttemptID,
		arg.RunnerKind,
		arg.RunnerID,
		arg.RunnerVersion,
		arg.PackageDigest,
		arg.ContractMajor,
		arg.ContractMinor,
		arg.RequestDigest,
		arg.ConfigurationDigest,
		arg.SignalName,
		arg.SignalOutcome,
		arg.ReasonCodes,
		arg.RecordedAt,
	)
	return err
}

const insertVerificationReconciliation = `-- name: InsertVerificationReconciliation :execrows
INSERT INTO idenqa.verification_reconciliations (
    tenant_id, verification_id, check_id, attempt_id, reason, status,
    claim_token, lease_expires_at, claim_count, available_at, created_at, updated_at, resolved_at
) VALUES (
    $1, $2, $3,
    $4, $5, 'pending', NULL, NULL, 0,
    $6, $7, $8, NULL
)
ON CONFLICT DO NOTHING
`

type InsertVerificationReconciliationParams struct {
	TenantID       string
	VerificationID string
	CheckID        string
	AttemptID      string
	Reason         string
	AvailableAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertVerificationReconciliation(ctx context.Context, arg InsertVerificationReconciliationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVerificationReconciliation,
		arg.TenantID,
		arg.VerificationID,
		arg.CheckID,
		arg.AttemptID,
		arg.Reason,
		arg.AvailableAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPendingCheckProgressEvents = `-- name: ListPendingCheckProgressEvents :many
SELECT events.id, events.tenant_id, events.aggregate_type, events.aggregate_id, events.aggregate_version, events.event_type, events.schema_version, events.payload, events.occurred_at, events.created_at, events.published_at, sessions.expires_at AS session_expires_at
FROM idenqa.outbox_events AS events
JOIN idenqa.verification_sessions AS sessions
  ON sessions.tenant_id = events.tenant_id
 AND sessions.id = (events.payload ->> 'verification_id')
WHERE events.tenant_id = $1
  AND events.event_type = 'verification.check.progress.v1'
  AND events.schema_version = 1
  AND events.published_at IS NULL
ORDER BY events.created_at, events.id
LIMIT $2
FOR UPDATE OF events SKIP LOCKED
`

type ListPendingCheckProgressEventsParams struct {
	TenantID  string
	BatchSize int32
}

type ListPendingCheckProgressEventsRow struct {
	ID               string
	TenantID         string
	AggregateType    string
	AggregateID      string
	AggregateVersion int64
	EventType        string
	SchemaVersion    int32
	Payload          []byte
	OccurredAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	PublishedAt      pgtype.Timestamptz
	SessionExpiresAt pgtype.Timestamptz
}

func (q *Queries) ListPendingCheckProgressEvents(ctx context.Context, arg ListPendingCheckProgressEventsParams) ([]ListPendingCheckProgressEventsRow, error) {
	rows, err := q.db.Query(ctx, listPendingCheckProgressEvents, arg.TenantID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingCheckProgressEventsRow
	for rows.Next() {
		var i ListPendingCheckProgressEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AggregateType,
			&i.AggregateID,
			&i.AggregateVersion,
			&i.EventType,
			&i.SchemaVersion,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.SessionExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationAttemptDiagnostics = `-- name: ListVerificationAttemptDiagnostics :many
SELECT tenant_id, verification_id, check_id, attempt_id, kind, code, recorded_at FROM idenqa.verification_attempt_diagnostics
WHERE tenant_id = $1 AND check_id = $2
ORDER BY recorded_at, attempt_id, kind
`

type ListVerificationAttemptDiagnosticsParams struct {
	TenantID string
	CheckID  string
}

func (q *Queries) ListVerificationAttemptDiagnostics(ctx context.Context, arg ListVerificationAttemptDiagnosticsParams) ([]IdenqaVerificationAttemptDiagnostic, error) {
	rows, err := q.db.Query(ctx, listVerificationAttemptDiagnostics, arg.TenantID, arg.CheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdenqaVerificationAttemptDiagnostic
	for rows.Next() {
		var i IdenqaVerificationAttemptDiagnostic
		if err := rows.Scan(
			&i.TenantID,
			&i.VerificationID,
			&i.CheckID,
			&i.AttemptID,
			&i.Kind,
			&i.Code,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationAttempts = `-- name: ListVerificationAttempts :many
SELECT id, tenant_id, verification_id, check_id, attempt_number, fence, runner_kind, runner_id, runner_version, package_digest, contract_major, contract_minor, request_digest, configuration_digest, state, started_at, deadline, finished_at, failure_class, failure_code, retry_disposition, retry_after_milliseconds, result_digest FROM idenqa.verification_attempts
WHERE tenant_id = $1 AND check_id = $2
ORDER BY attempt_number
`

type ListVerificationAttemptsParams struct {
	TenantID string
	CheckID  string
}

func (q *Queries) ListVerificationAttempts(ctx context.Context, arg ListVerificationAttemptsParams) ([]IdenqaVerificationAttempt, error) {
	rows, err := q.db.Query(ctx, listVerificationAttempts, arg.TenantID, arg.CheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdenqaVerificationAttempt
	for rows.Next() {
		var i IdenqaVerificationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.VerificationID,
			&i.CheckID,
			&i.AttemptNumber,
			&i.Fence,
			&i.RunnerKind,
			&i.RunnerID,
			&i.RunnerVersion,
			&i.PackageDigest,
			&i.ContractMajor,
			&i.ContractMinor,
			&i.RequestDigest,
			&i.ConfigurationDigest,
			&i.State,
			&i.StartedAt,
			&i.Deadline,
			&i.FinishedAt,
			&i.FailureClass,
			&i.FailureCode,
			&i.RetryDisposition,
			&i.RetryAfterMilliseconds,
			&i.ResultDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationObservations = `-- name: ListVerificationObservations :many
SELECT id, tenant_id, verification_id, check_id, attempt_id, runner_kind, runner_id, runner_version, package_digest, contract_major, contract_minor, request_digest, configuration_digest, signal_name, signal_outcome, reason_codes, recorded_at FROM idenqa.verification_observations
WHERE tenant_id = $1 AND check_id = $2
ORDER BY recorded_at, id
`

type ListVerificationObservationsParams struct {
	TenantID string
	CheckID  string
}

func (q *Queries) ListVerificationObservations(ctx context.Context, arg ListVerificationObservationsParams) ([]IdenqaVerificationObservation, error) {
	rows, err := q.db.Query(ctx, listVerificationObservations, arg.TenantID, arg.CheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdenqaVerificationObservation
	for rows.Next() {
		var i IdenqaVerificationObservation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.VerificationID,
			&i.CheckID,
			&i.AttemptID,
			&i.RunnerKind,
			&i.RunnerID,
			&i.RunnerVersion,
			&i.PackageDigest,
			&i.ContractMajor,
			&i.ContractMinor,
			&i.RequestDigest,
			&i.ConfigurationDigest,
			&i.SignalName,
			&i.SignalOutcome,
			&i.ReasonCodes,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVerificationCheck = `-- name: LockVerificationCheck :one
SELECT id, tenant_id, verification_id, name, state, outcome, version, created_at, updated_at FROM idenqa.verification_checks
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockVerificationCheckParams struct {
	TenantID string
	ID       string
}

func (q *Queries) LockVerificationCheck(ctx context.Context, arg LockVerificationCheckParams) (IdenqaVerificationCheck, error) {
	row := q.db.QueryRow(ctx, lockVerificationCheck, arg.TenantID, arg.ID)
	var i IdenqaVerificationCheck
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VerificationID,
		&i.Name,
		&i.State,
		&i.Outcome,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCheckProgressPublished = `-- name: MarkCheckProgressPublished :execrows
UPDATE idenqa.outbox_events
SET published_at = $1
WHERE tenant_id = $2
  AND id = $3
  AND event_type = 'verification.check.progress.v1'
  AND schema_version = 1
  AND published_at IS NULL
`

type MarkCheckProgressPublishedParams struct {
	PublishedAt pgtype.Timestamptz
	TenantID    string
	ID          string
}

func (q *Queries) MarkCheckProgressPublished(ctx context.Context, arg MarkCheckProgressPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCheckProgressPublished, arg.PublishedAt, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notifyCheckProgress = `-- name: NotifyCheckProgress :exec
SELECT pg_notify('idenqa_check_progress_v1', $1::text)
`

func (q *Queries) NotifyCheckProgress(ctx context.Context, tenantID string) error {
	_, err := q.db.Exec(ctx, notifyCheckProgress, tenantID)
	return err
}

const resolveVerificationReconciliation = `-- name: ResolveVerificationReconciliation :execrows
UPDATE idenqa.verification_reconciliations
SET status = 'resolved', claim_token = NULL, lease_expires_at = NULL,
    updated_at = $1, resolved_at = $1
WHERE tenant_id = $2 AND check_id = $3
  AND attempt_id = $4 AND reason = $5
  AND status = 'claimed' AND claim_token = $6
  AND updated_at <= $1 AND lease_expires_at > $1
`

type ResolveVerificationReconciliationParams struct {
	ResolvedAt pgtype.Timestamptz
	TenantID   string
	CheckID    string
	AttemptID  string
	Reason     string
	ClaimToken *string
}

func (q *Queries) ResolveVerificationReconciliation(ctx context.Context, arg ResolveVerificationReconciliationParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveVerificationReconciliation,
		arg.ResolvedAt,
		arg.TenantID,
		arg.CheckID,
		arg.AttemptID,
		arg.Reason,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVerificationCheck = `-- name: UpdateVerificationCheck :execrows
UPDATE idenqa.verification_checks
SET state = $1, outcome = $2, version = $3, updated_at = $4
WHERE tenant_id = $5 AND id = $6 AND version = $7
`

type UpdateVerificationCheckParams struct {
	State           string
	Outcome         *string
	Version         int64
	UpdatedAt       pgtype.Timestamptz
	TenantID        string
	ID              string
	ExpectedVersion int64
}

func (q *Queries) UpdateVerificationCheck(ctx context.Context, arg UpdateVerificationCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVerificationCheck,
		arg.State,
		arg.Outcome,
		arg.Version,
		arg.UpdatedAt,
		arg.TenantID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
