// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_timeline.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findCaptureJourneyEventDigest = `-- name: FindCaptureJourneyEventDigest :one
SELECT payload_digest FROM idenqa.capture_journey_events
WHERE tenant_id = $1 AND event_id = $2
`

type FindCaptureJourneyEventDigestParams struct {
	TenantID string
	EventID  string
}

func (q *Queries) FindCaptureJourneyEventDigest(ctx context.Context, arg FindCaptureJourneyEventDigestParams) (string, error) {
	row := q.db.QueryRow(ctx, findCaptureJourneyEventDigest, arg.TenantID, arg.EventID)
	var payload_digest string
	err := row.Scan(&payload_digest)
	return payload_digest, err
}

const findVerificationTimelineSession = `-- name: FindVerificationTimelineSession :one
SELECT id FROM idenqa.verification_sessions
WHERE tenant_id = $1 AND id = $2
`

type FindVerificationTimelineSessionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindVerificationTimelineSession(ctx context.Context, arg FindVerificationTimelineSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, findVerificationTimelineSession, arg.TenantID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCaptureJourneyEvent = `-- name: InsertCaptureJourneyEvent :execrows
INSERT INTO idenqa.capture_journey_events (
    tenant_id, verification_id, capture_token_id, event_id, sequence,
    event_type, screen, action, requirement_key, artefact, acquisition_method,
    client_occurred_at, received_at, payload_digest
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    $13, $14
)
ON CONFLICT (tenant_id, event_id) DO NOTHING
`

type InsertCaptureJourneyEventParams struct {
	TenantID          string
	VerificationID    string
	CaptureTokenID    string
	EventID           string
	Sequence          int32
	EventType         string
	Screen            string
	Action            *string
	RequirementKey    *string
	Artefact          *string
	AcquisitionMethod *string
	ClientOccurredAt  pgtype.Timestamptz
	ReceivedAt        pgtype.Timestamptz
	PayloadDigest     string
}

func (q *Queries) InsertCaptureJourneyEvent(ctx context.Context, arg InsertCaptureJourneyEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCaptureJourneyEvent,
		arg.TenantID,
		arg.VerificationID,
		arg.CaptureTokenID,
		arg.EventID,
		arg.Sequence,
		arg.EventType,
		arg.Screen,
		arg.Action,
		arg.RequirementKey,
		arg.Artefact,
		arg.AcquisitionMethod,
		arg.ClientOccurredAt,
		arg.ReceivedAt,
		arg.PayloadDigest,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVerificationTimeline = `-- name: ListVerificationTimeline :many
SELECT event_id, category, source, event_name, status, detail, occurred_at, authoritative FROM (
    SELECT ('origin:' || sessions.id)::text AS event_id, 'lifecycle'::text AS category,
           'core'::text AS source, 'verification.created'::text AS event_name,
           NULL::text AS status, NULL::text AS detail, sessions.created_at AS occurred_at,
           true AS authoritative
    FROM idenqa.verification_sessions AS sessions
    WHERE sessions.tenant_id = $1 AND sessions.id = $2
    UNION ALL
    SELECT transitions.event_id, 'lifecycle', 'core', 'verification.transitioned',
           transitions.to_state, transitions.from_state, transitions.occurred_at, true
    FROM idenqa.verification_transitions AS transitions
    WHERE transitions.tenant_id = $1 AND transitions.verification_id = $2
    UNION ALL
    SELECT events.event_id, 'interaction', 'capture_client', events.event_type,
           events.screen, events.action, events.received_at, false
    FROM idenqa.capture_journey_events AS events
    WHERE events.tenant_id = $1 AND events.verification_id = $2
    UNION ALL
    SELECT responses.id, 'interaction', 'core', ('notice.' || responses.action),
           responses.action, NULL::text, responses.recorded_at, true
    FROM idenqa.subject_responses AS responses
    WHERE responses.tenant_id = $1 AND responses.verification_id = $2
    UNION ALL
    SELECT assets.id, 'evidence', 'core', 'evidence.received', assets.state,
           assets.artefact, assets.created_at, true
    FROM idenqa.evidence_assets AS assets
    WHERE assets.tenant_id = $1 AND assets.verification_id = $2
    UNION ALL
    SELECT attempts.id || ':started', 'processing', 'core', 'check.attempt.started',
           attempts.state, attempts.runner_id, attempts.started_at, true
    FROM idenqa.verification_attempts AS attempts
    WHERE attempts.tenant_id = $1 AND attempts.verification_id = $2
    UNION ALL
    SELECT attempts.id || ':finished', 'processing', 'core', 'check.attempt.finished',
           attempts.state, attempts.failure_code, attempts.finished_at, true
    FROM idenqa.verification_attempts AS attempts
    WHERE attempts.tenant_id = $1 AND attempts.verification_id = $2
      AND attempts.finished_at IS NOT NULL
    UNION ALL
    SELECT observations.id, 'signal', 'core', observations.signal_name,
           observations.signal_outcome, NULL::text, observations.recorded_at, true
    FROM idenqa.verification_observations AS observations
    WHERE observations.tenant_id = $1 AND observations.verification_id = $2
    UNION ALL
    SELECT decisions.id, 'decision', 'core', 'decision.created', decisions.outcome,
           decisions.selected, decisions.decided_at, true
    FROM idenqa.verification_decisions AS decisions
    WHERE decisions.tenant_id = $1 AND decisions.verification_id = $2
) AS timeline
ORDER BY occurred_at, event_id
LIMIT 501
`

type ListVerificationTimelineParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationTimelineRow struct {
	EventID       string
	Category      string
	Source        string
	EventName     string
	Status        *string
	Detail        *string
	OccurredAt    pgtype.Timestamptz
	Authoritative bool
}

func (q *Queries) ListVerificationTimeline(ctx context.Context, arg ListVerificationTimelineParams) ([]ListVerificationTimelineRow, error) {
	rows, err := q.db.Query(ctx, listVerificationTimeline, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationTimelineRow
	for rows.Next() {
		var i ListVerificationTimelineRow
		if err := rows.Scan(
			&i.EventID,
			&i.Category,
			&i.Source,
			&i.EventName,
			&i.Status,
			&i.Detail,
			&i.OccurredAt,
			&i.Authoritative,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
