// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_inspection.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findVerificationInspectionSession = `-- name: FindVerificationInspectionSession :one
SELECT id FROM idenqa.verification_sessions
WHERE tenant_id = $1 AND id = $2
`

type FindVerificationInspectionSessionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindVerificationInspectionSession(ctx context.Context, arg FindVerificationInspectionSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, findVerificationInspectionSession, arg.TenantID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listVerificationInspectionAttempts = `-- name: ListVerificationInspectionAttempts :many
SELECT id, check_id, attempt_number, runner_kind, runner_id, runner_version,
       package_digest, contract_major, contract_minor, request_digest,
       configuration_digest, state, started_at, deadline, finished_at,
       failure_class, failure_code, retry_disposition,
       retry_after_milliseconds, result_digest
FROM idenqa.verification_attempts
WHERE tenant_id = $1 AND verification_id = $2
ORDER BY started_at, check_id, attempt_number
LIMIT 500
`

type ListVerificationInspectionAttemptsParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationInspectionAttemptsRow struct {
	ID                     string
	CheckID                string
	AttemptNumber          int32
	RunnerKind             string
	RunnerID               string
	RunnerVersion          string
	PackageDigest          string
	ContractMajor          int32
	ContractMinor          int32
	RequestDigest          string
	ConfigurationDigest    string
	State                  string
	StartedAt              pgtype.Timestamptz
	Deadline               pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	FailureClass           *string
	FailureCode            *string
	RetryDisposition       *string
	RetryAfterMilliseconds *int64
	ResultDigest           *string
}

func (q *Queries) ListVerificationInspectionAttempts(ctx context.Context, arg ListVerificationInspectionAttemptsParams) ([]ListVerificationInspectionAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listVerificationInspectionAttempts, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationInspectionAttemptsRow
	for rows.Next() {
		var i ListVerificationInspectionAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckID,
			&i.AttemptNumber,
			&i.RunnerKind,
			&i.RunnerID,
			&i.RunnerVersion,
			&i.PackageDigest,
			&i.ContractMajor,
			&i.ContractMinor,
			&i.RequestDigest,
			&i.ConfigurationDigest,
			&i.State,
			&i.StartedAt,
			&i.Deadline,
			&i.FinishedAt,
			&i.FailureClass,
			&i.FailureCode,
			&i.RetryDisposition,
			&i.RetryAfterMilliseconds,
			&i.ResultDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationInspectionChecks = `-- name: ListVerificationInspectionChecks :many
SELECT checks.id, checks.name, checks.state, checks.outcome,
       count(attempts.id)::integer AS attempt_count,
       checks.created_at, checks.updated_at
FROM idenqa.verification_checks AS checks
LEFT JOIN idenqa.verification_attempts AS attempts
  ON attempts.tenant_id = checks.tenant_id AND attempts.check_id = checks.id
WHERE checks.tenant_id = $1
  AND checks.verification_id = $2
GROUP BY checks.tenant_id, checks.id
ORDER BY checks.created_at, checks.id
LIMIT 100
`

type ListVerificationInspectionChecksParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationInspectionChecksRow struct {
	ID           string
	Name         string
	State        string
	Outcome      *string
	AttemptCount int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListVerificationInspectionChecks(ctx context.Context, arg ListVerificationInspectionChecksParams) ([]ListVerificationInspectionChecksRow, error) {
	rows, err := q.db.Query(ctx, listVerificationInspectionChecks, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationInspectionChecksRow
	for rows.Next() {
		var i ListVerificationInspectionChecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.Outcome,
			&i.AttemptCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationInspectionDecisions = `-- name: ListVerificationInspectionDecisions :many
SELECT id, decision_digest, selected, outcome, actor, supersedes_id, decided_at
FROM idenqa.verification_decisions
WHERE tenant_id = $1 AND verification_id = $2
ORDER BY decided_at, id
LIMIT 100
`

type ListVerificationInspectionDecisionsParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationInspectionDecisionsRow struct {
	ID             string
	DecisionDigest string
	Selected       string
	Outcome        string
	Actor          string
	SupersedesID   *string
	DecidedAt      pgtype.Timestamptz
}

func (q *Queries) ListVerificationInspectionDecisions(ctx context.Context, arg ListVerificationInspectionDecisionsParams) ([]ListVerificationInspectionDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listVerificationInspectionDecisions, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationInspectionDecisionsRow
	for rows.Next() {
		var i ListVerificationInspectionDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DecisionDigest,
			&i.Selected,
			&i.Outcome,
			&i.Actor,
			&i.SupersedesID,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationInspectionEvidence = `-- name: ListVerificationInspectionEvidence :many
SELECT id, requirement_key, evidence_type, artefact, acquisition_method,
       assurances, state, integrity, retention_class, created_at, updated_at
FROM idenqa.evidence_assets
WHERE tenant_id = $1 AND verification_id = $2
ORDER BY created_at, id
LIMIT 100
`

type ListVerificationInspectionEvidenceParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationInspectionEvidenceRow struct {
	ID                string
	RequirementKey    string
	EvidenceType      string
	Artefact          string
	AcquisitionMethod string
	Assurances        []string
	State             string
	Integrity         string
	RetentionClass    string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListVerificationInspectionEvidence(ctx context.Context, arg ListVerificationInspectionEvidenceParams) ([]ListVerificationInspectionEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listVerificationInspectionEvidence, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationInspectionEvidenceRow
	for rows.Next() {
		var i ListVerificationInspectionEvidenceRow
		if err := rows.Scan(
			&i.ID,
			&i.RequirementKey,
			&i.EvidenceType,
			&i.Artefact,
			&i.AcquisitionMethod,
			&i.Assurances,
			&i.State,
			&i.Integrity,
			&i.RetentionClass,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationInspectionRetention = `-- name: ListVerificationInspectionRetention :many
SELECT data_class, region, policy_digest, expires_at
FROM idenqa.retention_bindings
WHERE tenant_id = $1 AND aggregate_id = $2
ORDER BY data_class
LIMIT 32
`

type ListVerificationInspectionRetentionParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationInspectionRetentionRow struct {
	DataClass    string
	Region       string
	PolicyDigest string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) ListVerificationInspectionRetention(ctx context.Context, arg ListVerificationInspectionRetentionParams) ([]ListVerificationInspectionRetentionRow, error) {
	rows, err := q.db.Query(ctx, listVerificationInspectionRetention, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationInspectionRetentionRow
	for rows.Next() {
		var i ListVerificationInspectionRetentionRow
		if err := rows.Scan(
			&i.DataClass,
			&i.Region,
			&i.PolicyDigest,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationInspectionWebhooks = `-- name: ListVerificationInspectionWebhooks :many
SELECT events.id AS event_id, events.event_type, events.state AS event_state,
       deliveries.id AS delivery_id, deliveries.state AS delivery_state,
       events.created_at
FROM idenqa.webhook_events AS events
LEFT JOIN idenqa.webhook_deliveries AS deliveries
  ON deliveries.tenant_id = events.tenant_id AND deliveries.event_id = events.id
WHERE events.tenant_id = $1
  AND $2::text = ANY(events.aggregate_ids)
ORDER BY events.created_at DESC, events.id, deliveries.id
LIMIT 100
`

type ListVerificationInspectionWebhooksParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationInspectionWebhooksRow struct {
	EventID       string
	EventType     string
	EventState    string
	DeliveryID    *string
	DeliveryState *string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListVerificationInspectionWebhooks(ctx context.Context, arg ListVerificationInspectionWebhooksParams) ([]ListVerificationInspectionWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listVerificationInspectionWebhooks, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationInspectionWebhooksRow
	for rows.Next() {
		var i ListVerificationInspectionWebhooksRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventType,
			&i.EventState,
			&i.DeliveryID,
			&i.DeliveryState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verificationInspectionHasLegalHold = `-- name: VerificationInspectionHasLegalHold :one
SELECT EXISTS (
  SELECT 1 FROM idenqa.legal_holds
  WHERE tenant_id = $1
    AND aggregate_id = $2
    AND released_at IS NULL
) AS held
`

type VerificationInspectionHasLegalHoldParams struct {
	TenantID       string
	VerificationID string
}

func (q *Queries) VerificationInspectionHasLegalHold(ctx context.Context, arg VerificationInspectionHasLegalHoldParams) (bool, error) {
	row := q.db.QueryRow(ctx, verificationInspectionHasLegalHold, arg.TenantID, arg.VerificationID)
	var held bool
	err := row.Scan(&held)
	return held, err
}
