// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_signal.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findVerificationSignalSession = `-- name: FindVerificationSignalSession :one
SELECT id FROM idenqa.verification_sessions
WHERE tenant_id = $1 AND id = $2
`

type FindVerificationSignalSessionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindVerificationSignalSession(ctx context.Context, arg FindVerificationSignalSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, findVerificationSignalSession, arg.TenantID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listVerificationSignals = `-- name: ListVerificationSignals :many
SELECT id, check_id, attempt_id, runner_kind, runner_id, runner_version,
       contract_major, contract_minor, signal_name, signal_outcome,
       reason_codes, recorded_at
FROM idenqa.verification_observations
WHERE tenant_id = $1 AND verification_id = $2
ORDER BY recorded_at, id
LIMIT 201
`

type ListVerificationSignalsParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationSignalsRow struct {
	ID            string
	CheckID       string
	AttemptID     string
	RunnerKind    string
	RunnerID      string
	RunnerVersion string
	ContractMajor int32
	ContractMinor int32
	SignalName    string
	SignalOutcome string
	ReasonCodes   []string
	RecordedAt    pgtype.Timestamptz
}

func (q *Queries) ListVerificationSignals(ctx context.Context, arg ListVerificationSignalsParams) ([]ListVerificationSignalsRow, error) {
	rows, err := q.db.Query(ctx, listVerificationSignals, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationSignalsRow
	for rows.Next() {
		var i ListVerificationSignalsRow
		if err := rows.Scan(
			&i.ID,
			&i.CheckID,
			&i.AttemptID,
			&i.RunnerKind,
			&i.RunnerID,
			&i.RunnerVersion,
			&i.ContractMajor,
			&i.ContractMinor,
			&i.SignalName,
			&i.SignalOutcome,
			&i.ReasonCodes,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
