// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_session.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCaptureToken = `-- name: CreateCaptureToken :exec
INSERT INTO idenqa.capture_tokens (
    id, tenant_id, verification_id, key_version,
    issued_at, expires_at, revoked_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCaptureTokenParams struct {
	ID             string
	TenantID       string
	VerificationID string
	KeyVersion     int32
	IssuedAt       pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
}

func (q *Queries) CreateCaptureToken(ctx context.Context, arg CreateCaptureTokenParams) error {
	_, err := q.db.Exec(ctx, createCaptureToken,
		arg.ID,
		arg.TenantID,
		arg.VerificationID,
		arg.KeyVersion,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	return err
}

const createVerificationSession = `-- name: CreateVerificationSession :exec
INSERT INTO idenqa.verification_sessions (
    id, tenant_id, state, version, source_profile_id,
    source_profile_revision, source_profile_digest, requirements, region, policy_id, decision_id,
    created_at, updated_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateVerificationSessionParams struct {
	ID                    string
	TenantID              string
	State                 string
	Version               int64
	SourceProfileID       string
	SourceProfileRevision int32
	SourceProfileDigest   string
	Requirements          []byte
	Region                *string
	PolicyID              *string
	DecisionID            *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
}

func (q *Queries) CreateVerificationSession(ctx context.Context, arg CreateVerificationSessionParams) error {
	_, err := q.db.Exec(ctx, createVerificationSession,
		arg.ID,
		arg.TenantID,
		arg.State,
		arg.Version,
		arg.SourceProfileID,
		arg.SourceProfileRevision,
		arg.SourceProfileDigest,
		arg.Requirements,
		arg.Region,
		arg.PolicyID,
		arg.DecisionID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}

const findCaptureContext = `-- name: FindCaptureContext :one
SELECT
    tokens.id AS token_id,
    tokens.tenant_id,
    tokens.verification_id,
    tokens.key_version,
    tokens.issued_at,
    tokens.expires_at AS token_expires_at,
    tokens.revoked_at,
    sessions.state AS session_state,
    sessions.version AS session_version,
    sessions.source_profile_id,
    sessions.source_profile_revision,
    sessions.source_profile_digest,
    sessions.requirements,
    sessions.region,
    sessions.policy_id,
    sessions.decision_id,
    sessions.created_at AS session_created_at,
    sessions.updated_at AS session_updated_at,
    sessions.expires_at AS session_expires_at
FROM idenqa.capture_tokens AS tokens
JOIN idenqa.verification_sessions AS sessions
  ON sessions.tenant_id = tokens.tenant_id
 AND sessions.id = tokens.verification_id
WHERE tokens.tenant_id = $1 AND tokens.id = $2 AND tokens.verification_id = $3
`

type FindCaptureContextParams struct {
	TenantID       string
	ID             string
	VerificationID string
}

type FindCaptureContextRow struct {
	TokenID               string
	TenantID              string
	VerificationID        string
	KeyVersion            int32
	IssuedAt              pgtype.Timestamptz
	TokenExpiresAt        pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	SessionState          string
	SessionVersion        int64
	SourceProfileID       string
	SourceProfileRevision int32
	SourceProfileDigest   string
	Requirements          []byte
	Region                *string
	PolicyID              *string
	DecisionID            *string
	SessionCreatedAt      pgtype.Timestamptz
	SessionUpdatedAt      pgtype.Timestamptz
	SessionExpiresAt      pgtype.Timestamptz
}

func (q *Queries) FindCaptureContext(ctx context.Context, arg FindCaptureContextParams) (FindCaptureContextRow, error) {
	row := q.db.QueryRow(ctx, findCaptureContext, arg.TenantID, arg.ID, arg.VerificationID)
	var i FindCaptureContextRow
	err := row.Scan(
		&i.TokenID,
		&i.TenantID,
		&i.VerificationID,
		&i.KeyVersion,
		&i.IssuedAt,
		&i.TokenExpiresAt,
		&i.RevokedAt,
		&i.SessionState,
		&i.SessionVersion,
		&i.SourceProfileID,
		&i.SourceProfileRevision,
		&i.SourceProfileDigest,
		&i.Requirements,
		&i.Region,
		&i.PolicyID,
		&i.DecisionID,
		&i.SessionCreatedAt,
		&i.SessionUpdatedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const findCaptureToken = `-- name: FindCaptureToken :one
SELECT id, tenant_id, verification_id, key_version, issued_at, expires_at, revoked_at
FROM idenqa.capture_tokens
WHERE tenant_id = $1 AND id = $2 AND verification_id = $3
`

type FindCaptureTokenParams struct {
	TenantID       string
	ID             string
	VerificationID string
}

func (q *Queries) FindCaptureToken(ctx context.Context, arg FindCaptureTokenParams) (IdenqaCaptureToken, error) {
	row := q.db.QueryRow(ctx, findCaptureToken, arg.TenantID, arg.ID, arg.VerificationID)
	var i IdenqaCaptureToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VerificationID,
		&i.KeyVersion,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const findVerificationSession = `-- name: FindVerificationSession :one
SELECT id, tenant_id, state, version, source_profile_id, source_profile_revision, source_profile_digest, requirements, created_at, updated_at, expires_at, subject_id, authority_id, notice_id, region, policy_id, decision_id, capture_completed_at
FROM idenqa.verification_sessions
WHERE tenant_id = $1 AND id = $2
`

type FindVerificationSessionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) FindVerificationSession(ctx context.Context, arg FindVerificationSessionParams) (IdenqaVerificationSession, error) {
	row := q.db.QueryRow(ctx, findVerificationSession, arg.TenantID, arg.ID)
	var i IdenqaVerificationSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.State,
		&i.Version,
		&i.SourceProfileID,
		&i.SourceProfileRevision,
		&i.SourceProfileDigest,
		&i.Requirements,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.SubjectID,
		&i.AuthorityID,
		&i.NoticeID,
		&i.Region,
		&i.PolicyID,
		&i.DecisionID,
		&i.CaptureCompletedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO idenqa.outbox_events (
    id, tenant_id, aggregate_type, aggregate_id, aggregate_version,
    event_type, schema_version, payload, occurred_at, created_at, published_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertOutboxEventParams struct {
	ID               string
	TenantID         string
	AggregateType    string
	AggregateID      string
	AggregateVersion int64
	EventType        string
	SchemaVersion    int32
	Payload          []byte
	OccurredAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	PublishedAt      pgtype.Timestamptz
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.EventType,
		arg.SchemaVersion,
		arg.Payload,
		arg.OccurredAt,
		arg.CreatedAt,
		arg.PublishedAt,
	)
	return err
}

const insertVerificationSessionAudit = `-- name: InsertVerificationSessionAudit :exec
INSERT INTO idenqa.verification_session_audit (
    tenant_id, verification_id, aggregate_version, action,
    actor_key_id, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertVerificationSessionAuditParams struct {
	TenantID         string
	VerificationID   string
	AggregateVersion int64
	Action           string
	ActorKeyID       string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) InsertVerificationSessionAudit(ctx context.Context, arg InsertVerificationSessionAuditParams) error {
	_, err := q.db.Exec(ctx, insertVerificationSessionAudit,
		arg.TenantID,
		arg.VerificationID,
		arg.AggregateVersion,
		arg.Action,
		arg.ActorKeyID,
		arg.OccurredAt,
	)
	return err
}

const lockActiveCaptureProfileRevision = `-- name: LockActiveCaptureProfileRevision :one
SELECT
    profiles.id AS profile_id,
    profiles.tenant_id,
    profiles.name,
    profiles.state AS profile_state,
    profiles.version AS profile_version,
    profiles.latest_revision,
    profiles.draft_revision,
    profiles.published_revision,
    profiles.created_at AS profile_created_at,
    profiles.updated_at AS profile_updated_at,
    profiles.deactivated_at,
    revisions.revision,
    revisions.state AS revision_state,
    revisions.schema_version,
    revisions.registry_schema_version,
    revisions.registry_revision,
    revisions.registry_digest,
    revisions.document,
    revisions.digest,
    revisions.created_at AS revision_created_at,
    revisions.updated_at AS revision_updated_at,
    revisions.published_at,
    revisions.ended_at
FROM idenqa.capture_profiles AS profiles
JOIN idenqa.capture_profile_revisions AS revisions
  ON revisions.tenant_id = profiles.tenant_id
 AND revisions.profile_id = profiles.id
 AND revisions.revision = profiles.published_revision
WHERE profiles.tenant_id = $1
  AND profiles.id = $2
  AND profiles.state = 'active'
  AND revisions.state = 'published'
FOR SHARE OF profiles, revisions
`

type LockActiveCaptureProfileRevisionParams struct {
	TenantID string
	ID       string
}

type LockActiveCaptureProfileRevisionRow struct {
	ProfileID             string
	TenantID              string
	Name                  string
	ProfileState          string
	ProfileVersion        int64
	LatestRevision        int32
	DraftRevision         *int32
	PublishedRevision     *int32
	ProfileCreatedAt      pgtype.Timestamptz
	ProfileUpdatedAt      pgtype.Timestamptz
	DeactivatedAt         pgtype.Timestamptz
	Revision              int32
	RevisionState         string
	SchemaVersion         int32
	RegistrySchemaVersion int32
	RegistryRevision      int32
	RegistryDigest        string
	Document              []byte
	Digest                string
	RevisionCreatedAt     pgtype.Timestamptz
	RevisionUpdatedAt     pgtype.Timestamptz
	PublishedAt           pgtype.Timestamptz
	EndedAt               pgtype.Timestamptz
}

func (q *Queries) LockActiveCaptureProfileRevision(ctx context.Context, arg LockActiveCaptureProfileRevisionParams) (LockActiveCaptureProfileRevisionRow, error) {
	row := q.db.QueryRow(ctx, lockActiveCaptureProfileRevision, arg.TenantID, arg.ID)
	var i LockActiveCaptureProfileRevisionRow
	err := row.Scan(
		&i.ProfileID,
		&i.TenantID,
		&i.Name,
		&i.ProfileState,
		&i.ProfileVersion,
		&i.LatestRevision,
		&i.DraftRevision,
		&i.PublishedRevision,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
		&i.DeactivatedAt,
		&i.Revision,
		&i.RevisionState,
		&i.SchemaVersion,
		&i.RegistrySchemaVersion,
		&i.RegistryRevision,
		&i.RegistryDigest,
		&i.Document,
		&i.Digest,
		&i.RevisionCreatedAt,
		&i.RevisionUpdatedAt,
		&i.PublishedAt,
		&i.EndedAt,
	)
	return i, err
}
