// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_history.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findVerificationLifecycleOrigin = `-- name: FindVerificationLifecycleOrigin :one
SELECT 'collecting'::text AS state, 1::bigint AS version, created_at AS occurred_at
FROM idenqa.verification_sessions
WHERE tenant_id = $1 AND id = $2
`

type FindVerificationLifecycleOriginParams struct {
	TenantID       string
	VerificationID string
}

type FindVerificationLifecycleOriginRow struct {
	State      string
	Version    int64
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) FindVerificationLifecycleOrigin(ctx context.Context, arg FindVerificationLifecycleOriginParams) (FindVerificationLifecycleOriginRow, error) {
	row := q.db.QueryRow(ctx, findVerificationLifecycleOrigin, arg.TenantID, arg.VerificationID)
	var i FindVerificationLifecycleOriginRow
	err := row.Scan(&i.State, &i.Version, &i.OccurredAt)
	return i, err
}

const listVerificationLifecycleTransitions = `-- name: ListVerificationLifecycleTransitions :many
SELECT event_id, from_state, to_state, resulting_version, decision_id, occurred_at
FROM idenqa.verification_transitions
WHERE tenant_id = $1 AND verification_id = $2
ORDER BY resulting_version, event_id
LIMIT 101
`

type ListVerificationLifecycleTransitionsParams struct {
	TenantID       string
	VerificationID string
}

type ListVerificationLifecycleTransitionsRow struct {
	EventID          string
	FromState        string
	ToState          string
	ResultingVersion int64
	DecisionID       *string
	OccurredAt       pgtype.Timestamptz
}

func (q *Queries) ListVerificationLifecycleTransitions(ctx context.Context, arg ListVerificationLifecycleTransitionsParams) ([]ListVerificationLifecycleTransitionsRow, error) {
	rows, err := q.db.Query(ctx, listVerificationLifecycleTransitions, arg.TenantID, arg.VerificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationLifecycleTransitionsRow
	for rows.Next() {
		var i ListVerificationLifecycleTransitionsRow
		if err := rows.Scan(
			&i.EventID,
			&i.FromState,
			&i.ToState,
			&i.ResultingVersion,
			&i.DecisionID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
