package runtimepermissions

import "github.com/jackc/pgx/v5"

const Version = "idenqa.core/postgres-runtime-permissions/v1"

// Statements returns the exact least-privilege PostgreSQL grants required by
// this Core release. The role is quoted as an identifier before composition;
// callers execute the statements only through an administrative connection.
func Statements(role string) []string {
	identifier := pgx.Identifier{role}.Sanitize()
	statements := []string{
		"REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA idenqa FROM " + identifier,
		"REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA idenqa FROM " + identifier,
		"REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA idenqa FROM " + identifier,
		"REVOKE ALL PRIVILEGES ON SCHEMA idenqa FROM " + identifier,
		"REVOKE ALL PRIVILEGES ON public.schema_migrations FROM " + identifier,
		"GRANT SELECT, INSERT ON idenqa.evidence_temporal_frames TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT ON idenqa.pack_release_states, idenqa.pack_release_history TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.review_recapture_evaluation_requests,idenqa.capture_recoveries, idenqa.capture_recovery_uploads TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.model_registries TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.model_registry_revisions, idenqa.model_registry_history TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT ON public.schema_migrations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT USAGE ON SCHEMA idenqa TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.tenants TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.api_keys TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.capture_profiles TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.capture_profile_revisions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.capture_profile_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE, DELETE ON idenqa.idempotency_records TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.verification_sessions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.verification_checks TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.verification_attempts TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_ready_provider_captures(timestamptz,integer,text,text,text) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.provider_requests TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.provider_dispatches TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.provider_registrations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.provider_registration_history TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.provider_async_operations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.provider_health_snapshots TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, DELETE ON idenqa.provider_dispatch_leases TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE, DELETE ON idenqa.provider_dispatch_admissions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.provider_callback_receipts TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.resolve_provider_callback(text) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.model_requests TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.model_dispatches TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.verification_observations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.capture_journey_events TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.verification_attempt_diagnostics TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.verification_result_inbox TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.verification_reconciliations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.policy_snapshots TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.policy_evaluations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.policy_routing_receipts TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.verification_input_requests TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.review_recapture_acknowledgements, idenqa.review_recaptures, idenqa.review_evaluation_requests,idenqa.review_evaluations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.review_operator_assignments,idenqa.review_policy_settings,idenqa.review_case_operations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.review_administration_history,idenqa.review_case_settings,idenqa.review_evidence_access,idenqa.review_arbitrations,idenqa.review_correction_evaluations,idenqa.review_correction_intakes,idenqa.review_appeal_history TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.review_command_receipts TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.review_evidence_session_bootstraps,idenqa.review_evidence_sessions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_expired_review_appeals(timestamptz,integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_ready_review_evaluations(timestamptz,integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.verification_decisions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.policies TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.policy_revisions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.policy_activations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.webhook_endpoints TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.webhook_secrets TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.webhook_deliveries TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.webhook_delivery_attempts TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.webhook_events TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.audit_heads TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.audit_records TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.api_request_logs TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.audit_keys TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.audit_checkpoints TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.retention_bindings TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.legal_holds TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.deletion_requests TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.deletion_targets TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.deletion_tombstones TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.review_cases TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.review_findings TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.appeals TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.capture_tokens TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.outcome_tokens TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.experiences TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.experience_revisions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.experience_targeting TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.experience_events TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.experience_session_pins TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE, DELETE ON idenqa.websocket_connection_tickets TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.realtime_client_commands TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.realtime_streams TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE, DELETE ON idenqa.realtime_events TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.realtime_acknowledgements TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.verification_session_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.capture_document_selection_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.verification_transitions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.notice_versions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.notice_version_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.subjects TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.processing_authorities TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.authority_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.subject_responses TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.evidence_assets TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.evidence_asset_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.evidence_key_rewrap_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.evidence_upload_intents TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.evidence_upload_intent_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.evidence_object_reconciliations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.evidence_object_reconciliation_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.evidence_processing_grants TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.evidence_grant_redemptions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.evidence_grant_redemption_outcomes TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.evidence_processing_grant_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT INSERT ON idenqa.evidence_grant_access_attempt_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.outbox_events TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_due_verification_reconciliations(timestamptz, integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_pending_check_progress_tenants(integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.identity_subjects TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE, DELETE ON idenqa.identity_keys,idenqa.identity_current TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, DELETE ON idenqa.identity_record_values,idenqa.identity_identifier_tokens TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.assurance_profiles,idenqa.verification_assurance TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.policy_assurance_assignments TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.identity_subject_verifications,idenqa.identity_records,idenqa.identity_record_edges,idenqa.identity_record_evidence,idenqa.identity_configurations,idenqa.identity_receipts TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_expired_identity_tenants(timestamptz,integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.fraud_configurations,idenqa.fraud_receipts,idenqa.fraud_proposals TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.fraud_keys TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, DELETE ON idenqa.fraud_links TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_expired_fraud_tenants(timestamptz,integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_ready_verification_captures(timestamptz, integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_ready_webhook_deliveries(timestamptz, integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_ready_webhook_events(timestamptz, integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.expire_webhook_data(timestamptz, integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_due_verification_expirations(timestamptz, integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_ready_policy_authorships(timestamptz, integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_due_privacy_deletions(timestamptz, integer) TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.proposals TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.accepted_commands TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.proposal_mode_configs TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.prompt_registry,idenqa.generative_model_registry,idenqa.impact_assessments TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.proposal_generation_usage TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.proposal_generation_activations TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.proposal_generation_activation_history TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.privacy_requests TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.privacy_request_events,idenqa.privacy_request_decisions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.privacy_restrictions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.privacy_disclosures TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.processor_inventory TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.processor_inventory_revisions TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.hmac_key_domains,idenqa.hmac_keys TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.support_grants,idenqa.break_glass_requests TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.break_glass_uses TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.key_rewrap_state TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.key_rewrap_audit TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT ON idenqa.key_destruction_verifications,idenqa.key_destruction_schedules TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT SELECT, INSERT, UPDATE ON idenqa.key_recovery_ceremonies TO " + pgx.Identifier{role}.Sanitize(),
		"GRANT EXECUTE ON FUNCTION idenqa.list_key_rewrap_tenants(text, integer) TO " + pgx.Identifier{role}.Sanitize(),
	}
	return statements
}
